<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>


<div class="content1">
    <?php include VIEW . 'messages.phtml' ?>

    <section class="h-100">
        <div class="container h-100">
            <div class="row justify-content-lg-center ">
                <div class="card-wrapper col-md-10 col-sm-6">

                    <div class="card fat">
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-md-6 pull-right" >
                                    <div
data-tilt>
                                        <img src="/images/login.png" alt="IMG"  width="110%" >
                                    </div>
                                </div>
                                <div class="col-md-6 pull-left">
                                    <h4 class="card-title">Login</h4>
                                    <form method="POST" class="my-login-validation" novalidate="" action="/home/postLogin">
                                        <div class="form-group">
                                            <label for="user_email">User Name:</label>
                                            <input type="username" value="<?php Helper::old('username'); ?>"
                                                   class="form-control" placeholder="Enter email" id="user_email"
                                                   name="username" required>

                                            <div class="invalid-feedback">
                                                User Name is invalid
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="password">Password

                                            </label>
                                            <label for="password">Password:</label>
                                            <input type="password" class="form-control" placeholder="Enter password"
                                                   id="password" name="password" data-eye>
                                            <div class="invalid-feedback">
                                                Password is required
                                            </div>

                                        </div>

                                        <div class="form-group ml-4">
                                            <div class="custom-checkbox custom-control">
                                                <input type="checkbox" name="remember" id="remember" class="custom-control-input">
                                                <label for="remember" class="custom-control-label">Remember Me</label>
                                            </div>




                                        </div>

                                        <div class="form-group m-0">
                                            <button type="submit"  name="submit" class="btn btn-primary btn-block">
                                                Login
                                            </button>
                                        </div>
                                        <div class="mt-4 text-center">
                                            Don't have an account?

                                            <a href="/home/register/student" > Regsiter as Student ,</a>
                                            <a href="/home/register/university" > Regsiter as University, </a>

                                        </div>
                                        <div class="footer text-center">
                                            Copyright &copy; 2020 &mdash; StepForward
                                         <br>   <a href="forgot.html" >
                                                Forgot Password ?
                                            </a>
                                        </div>
                                    </form>
                                </div>
                            </div>


                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>


</div>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'readImageFile.phtml' ?>

<script>
    $('#role_name').on('change', function () {
        var selection = $(this).val();
        switch (selection) {
            case "student":
                $("#student").show()
                $("#university").hide()
                break;
            case "university":
                $("#university").show()
                $("#student").hide()

        }
    });


    readFile('#user_image', '#user_image_dev');
    readFile('#document', '#university_document_dev');


</script>

<script> openCity(event, '<?php if (isset($this->view_data['active'])) echo $this->view_data['active']?>') </script>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>


