<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>


<div class="content1">
    <?php include VIEW . 'messages.phtml' ?>

    <section class="h-100">
        <div class="container h-100">
            <div class="row justify-content-lg-center ">
                <div class="card-wrapper col-md-5 col-sm-6">
                    <div class="brand">
                        <img src="/img/logo.jpg" alt="logo">
                    </div>
                    <div class="card fat">
                        <div class="card-body ">
                            <h4 class="card-title">Login</h4>
                            <form method="POST" class="my-login-validation" novalidate="" action="/home/postLogin">
                                <div class="form-group">
                                    <label for="user_email">User Name:</label>
                                    <input type="username" value="<?php Helper::old('username'); ?>"
                                                                              class="form-control" placeholder="Enter email" id="user_email"
                                                                            name="username" required>

                                    <div class="invalid-feedback">
                                       User Name is invalid
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="password">Password

                                    </label>
                                    <label for="password">Password:</label>
                                                                       <input type="password" class="form-control" placeholder="Enter password"
                                                                             id="password" name="password" data-eye>
                                    <div class="invalid-feedback">
                                        Password is required
                                    </div>

                                </div>

                                <div class="form-group ml-4">
                                    <div class="custom-checkbox custom-control">
                                        <input type="checkbox" name="remember" id="remember" class="custom-control-input">
                                        <label for="remember" class="custom-control-label">Remember Me</label>
                                    </div>

                                        <a href="forgot.html" class="float-left">
                                            Forgot Password?
                                        </a>


                                </div>
                                <br>

                                <div class="form-group m-0">
                                    <button type="submit"  name="submit" class="btn btn-primary btn-block">
                                        Login
                                    </button>
                                </div>
                                <div class="mt-4 text-center">
                                    Don't have an account?

                                    <a href="/home/register/student" > Regsiter as Student ,</a>
                                    <a href="/home/register/university" > Regsiter as University</a>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="footer">
                        Copyright &copy; 2020 &mdash; StepForward
                    </div>
                </div>
            </div>
        </div>
    </section>

<!--    <div id="singUP" class="tabcontent">-->
<!--        <div class="row">-->
<!--            <div class="col-xl-8 ">-->
<!--                <div class="card">-->
<!--                    <div class="card-body">-->
<!--                        <form method="post" action="/admin/singUp" enctype="multipart/form-data">-->
<!--                            <div class="row">-->
<!--                                <div class=" col-12">-->
<!---->
<!--                                    <h2 class="text-center">Sign Up</h2>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                            <div class="row">-->
<!--                                <div class="col-md-6">-->
<!--                                    <label for="user_email">Email address:</label>-->
<!--                                    <input type="email" class="form-control" placeholder="Enter email" id="user_email"-->
<!--                                           value="--><?php //Helper::old('user_email'); ?><!--"-->
<!--                                           name="user_email">-->
<!--                                    --><?php //echo Message::getInputErrorMessage('user_email') ?>
<!--                                    <label for="user_password">Password:</label>-->
<!--                                    <input type="password" class="form-control" placeholder="Enter password"-->
<!--                                           id="user_password" name="user_password">-->
<!--                                    --><?php //echo Message::getInputErrorMessage('user_password') ?>
<!---->
<!---->
<!--                                    <label for="user_password">Confirm Password:</label>-->
<!--                                    <input type="password" class="form-control" placeholder="Enter password"-->
<!--                                           id="password_confirmation" name="password_confirmation">-->
<!--                                    --><?php //echo Message::getInputErrorMessage('password_confirmation') ?>
<!---->
<!--                                    <label for="user_full_name">User Full Name:</label>-->
<!--                                    <input type="text" class="form-control" placeholder="Enter User Full Name"-->
<!--                                           value="--><?php //Helper::old('user_full_name'); ?><!--"-->
<!--                                           id="user_full_name" name="user_full_name">-->
<!--                                    --><?php //echo Message::getInputErrorMessage('user_full_name') ?>
<!--                                    <label for="user_name">User Name:</label>-->
<!--                                    <input type="text" class="form-control" placeholder="Enter User Name" id="user_name"-->
<!--                                           value="--><?php //Helper::old('user_name'); ?><!--"-->
<!--                                           name="user_name">-->
<!--                                    --><?php //echo Message::getInputErrorMessage('user_name') ?>
<!---->
<!--                                </div>-->
<!---->
<!--                                <div class="col-md-6">-->
<!--                                    <label for="user_image">User Image:</label>-->
<!--                                    <div class="custom-file">-->
<!---->
<!--                                        <input type="file" class="custom-file-input" name="user_image" id="user_image">-->
<!--                                        <label class="custom-file-label" for="user_image">Choose file</label>-->
<!--                                    </div>-->
<!--                                    <div id="user_image_dev">-->
<!--                                        --><?php //if (array_key_exists('news', $this->view_data)) { ?>
<!--                                            <img src="--><?php //echo($this->view_data['user']['user_image']); ?><!--"-->
<!--                                                 width="100px">-->
<!---->
<!--                                        --><?php //} ?>
<!--                                    </div>-->
<!--                                    <label for="user_phone">User Phone:</label>-->
<!--                                    <input type="phone" class="form-control" placeholder="Enter User Phone"-->
<!--                                           value="--><?php //Helper::old('user_phone'); ?><!--"-->
<!--                                           id="user_phone" name="user_phone">-->
<!---->
<!--                                    <label for="user_gender">User Gender:</label>-->
<!---->
<!--                                    <select class="form-control" id="user_gender" name="user_gender">-->
<!--                                        <option value="male" selected>Male</option>-->
<!--                                        <option value="female">Female</option>-->
<!---->
<!--                                    </select>-->
<!---->
<!---->
<!--                                    <label for="role_name">Register as:</label>-->
<!--                                    <select class="form-control" id="role_name" name="role_name">-->
<!--                                        <option value="student">student</option>-->
<!--                                        <option value="university">university</option>-->
<!---->
<!--                                    </select>-->
<!---->
<!--                                </div>-->
<!---->
<!---->
<!--                            </div>-->
<!--                            <div class="row">-->
<!--                                <div class="col-md-12">-->
<!--                                    <div id="student">-->
<!--                                        <label for="user_qualification">User Qualification:</label>-->
<!--                                        <input type="text" class="form-control" placeholder="Enter User Qualification"-->
<!--                                               id="user_qualification" name="user_qualification">-->
<!--                                    </div>-->
<!--                                    <div id="university" style="display: none">-->
<!--                                        <label for="user_image">University Document:</label>-->
<!---->
<!--                                        <div class="custom-file ">-->
<!---->
<!--                                            <input type="file" class="custom-file-input" name="document"-->
<!--                                                   id="document">-->
<!--                                            <label class="custom-file-label" for="user_image">Choose file</label>-->
<!---->
<!--                                        </div>-->
<!--                                        <div id="university_document_dev">-->
<!--                                            --><?php //if (array_key_exists('user', $this->view_data)) { ?>
<!--                                                <img src="--><?php //echo($this->view_data['user']['user_image']); ?><!--"-->
<!--                                                     width="100px">-->
<!---->
<!--                                            --><?php //} ?>
<!--                                        </div>-->
<!---->
<!--                                    </div>-->
<!---->
<!--                                </div>-->
<!--                            </div>-->
<!--                            <div class="row">-->
<!--                                <div class="col-md-6">-->
<!--                                    <br> <input type="submit" class="btn btn-primary " name="submit">-->
<!---->
<!--                                </div>-->
<!--                            </div>-->
<!---->
<!--                        </form>-->
<!---->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--            </div>-->
<!---->
<!---->
<!--        </div>-->
<!---->
<!---->
<!--    </div>-->


</div>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.php' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'readImageFile.phtml' ?>

<script>
    $('#role_name').on('change', function () {
        var selection = $(this).val();
        switch (selection) {
            case "student":
                $("#student").show()
                $("#university").hide()
                break;
            case "university":
                $("#university").show()
                $("#student").hide()

        }
    });


    readFile('#user_image', '#user_image_dev');
    readFile('#document', '#university_document_dev');


</script>

<script> openCity(event, '<?php if (isset($this->view_data['active'])) echo $this->view_data['active']?>') </script>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>


