<div class="bg_color_1">
    <div class="container margin_61_35">
        <div class="row">
            <div class="col-md-4">
                <a href="/home/contact" class="boxed_list">
                    <i class="pe-7s-help2"></i>
                    <h4>Need Help? Contact us</h4>
                    <p>Cum appareat maiestatis interpretaris et, et sit.</p>
                </a>
            </div>
            <div class="col-md-4">
                <a href="#0" class="boxed_list">
                    <i class="pe-7s-wallet"></i>
                    <h4>Payments and Refunds</h4>
                    <p>Qui ea nemore eruditi, magna prima possit eu mei.</p>
                </a>
            </div>
            <div class="col-md-4">
                <a href="#0" class="boxed_list">
                    <i class="pe-7s-note2"></i>
                    <h4>Quality Standards</h4>
                    <p>Hinc vituperata sed ut, pro laudem nonumes ex.</p>
                </a>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<footer>
    <div class="container margin_120_95">
        <div class="row">
            <div class="col-lg-5 col-md-12 p-r-5">
                <h1 id="site">Step Forward</h1>
                <!--                <p><img src="../img/" width="149" height="42" data-retina="true" alt=""></p>-->
                <!--                <p>Mea nibh meis philosophia eu. Duis legimus efficiantur ea sea. Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu. Nihil facilisi indoctum an vix, ut delectus expetendis vis.</p>-->
                <div class="follow_us">
                    <ul>
                        <li>Follow us</li>
                        <li><a href="#0"><i class="ti-facebook"></i></a></li>
                        <li><a href="#0"><i class="ti-twitter-alt"></i></a></li>
                        <li><a href="#0"><i class="ti-google"></i></a></li>
                        <li><a href="#0"><i class="ti-pinterest"></i></a></li>
                        <li><a href="#0"><i class="ti-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 ml-lg-auto">
                <h5>Useful links</h5>
                <ul class="links">
                    <li><a href="/home/home">home</a></li>
                    <li><a href="#0">About</a></li>
                    <li><a href="/home/contact">
                            Contact Us
                        </a></li>
                </ul>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5>Contact with Us</h5>
                <ul class="contacts">
                    <li><a href="tel://61280932400"><i class="ti-mobile"></i> + 61 23 8093 3400</a></li>
                    <li><a href="mailto:info@udema.com"><i class="ti-email"></i> info@stepforward.com</a></li>
                </ul>
                <div id="newsletter">
                    <h6>Newsletter</h6>
                    <div id="message-newsletter"></div>
                    <form method="post" action="/home/newsletter" name="newsletter_form" id="newsletter_form">
                        <div class="form-group">
                            <input type="email" name="email_newsletter" id="email_newsletter" class="form-control"
                                   placeholder="Your email">
                            <input type="submit" value="Submit" id="submit-newsletter">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!--/row-->
        <hr>
        <div class="row">
            <div class="col-md-8">
                <ul id="additional_links">
                    <li><a href="#0">Terms and conditions</a></li>
                    <li><a href="#0">Privacy</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <div id="copy"> Step Forward<!--<i class="icon-monument"></i>--> ©2020</div>
            </div>
        </div>
    </div>
</footer>

<!--<script src="../js/jquery-2.2.3.min.js"></script>-->
<script src="/design/site/js/jquery-3.3.1.min.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>-->


<script src="/design/site/js/popper.min.js"></script>

<!-- Popper -->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<script src="/design/site/js/bootstrap.bundle.js"></script>
<script src="/design/site/js/bootstrap.bundle.min.js"></script>
<script src="/design/site/js/bootstrap.js"></script>
<script src="/design/site/js/bootstrap.min.js"></script>
<script>
    $('#carouselExampleControls').carousel({
        interval: false
    });

</script>
<!--<script src="ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>-->
<script src="/design/site/js/scroll-top.js"></script>

<!-- COMMON SCRIPTS -->

<script src="/design/site/js/common_scripts.js"></script>
<script src="/design/site/js/main.js"></script>
<script src="/design/site/js/validate.js"></script>

<!--===============================================================================================-->
<script src="/design/site/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<!--<script src="/design/site/vendor/bootstrap/js/bootstrap.min.js"></script>-->
<!--===============================================================================================-->
<script src="/design/site/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="/design/site/vendor/daterangepicker/moment.min.js"></script>
<script src="/design/site/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="/design/site/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="/design/site/js/main-contact.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics-->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>

<script src="/design/site/js/web.js"></script>
<script src="/design/site/js/coursel.js"></script>
<script src="/design/site/js/scriptprofile.js"></script>

<script>
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover();
    });
</script>
<?php (Message::getMessage('errors')); ?>
