

<!--<script src="../js/jquery-2.2.3.min.js"></script>-->
<script src="/design/site/js/jquery-3.3.1.min.js"></script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>-->


<script src="/design/site/js/popper.min.js"></script>

<!-- Popper -->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<script src="/design/site/js/bootstrap.bundle.js"></script>
<script src="/design/site/js/bootstrap.bundle.min.js"></script>
<script src="/design/site/js/bootstrap.js"></script>
<script src="/design/site/js/bootstrap.min.js"></script>
<script>
    $('#carouselExampleControls').carousel({
        interval: false
    });

</script>
<!--<script src="ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>-->
<script src="/design/site/js/scroll-top.js"></script>

<!-- COMMON SCRIPTS -->

<script src="/design/site/js/common_scripts.js"></script>
<script src="/design/site/js/main.js"></script>
<script src="/design/site/js/validate.js"></script>

<!--===============================================================================================-->
<script src="/design/site/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<!--<script src="/design/site/vendor/bootstrap/js/bootstrap.min.js"></script>-->
<!--===============================================================================================-->
<script src="/design/site/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="/design/site/vendor/daterangepicker/moment.min.js"></script>
<script src="/design/site/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="/design/site/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="/design/site/js/main-contact.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics-->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>

<script src="/design/site/js/web.js"></script>
<script src="/design/site/js/coursel.js"></script>
<script src="/design/site/js/scriptprofile.js"></script>
<script>
    $(document).ready(function () {

        $('.navbar .dropdown-item').on('click', function (e) {
            var $el = $(this).children('.dropdown-toggle');
            var $parent = $el.offsetParent(".dropdown-menu");
            $(this).parent("li").toggleClass('open');

            if (!$parent.parent().hasClass('navbar-nav')) {
                if ($parent.hasClass('show')) {
                    $parent.removeClass('show');
                    $el.next().removeClass('show');
                    $el.next().css({"top": -999, "left": -999});

                } else {
                    $parent.parent().find('.show').removeClass('show');
                    $parent.addClass('show');
                    $el.next().addClass('show');
                    $el.next().css({"top": $el[0].offsetTop, "left": $parent.outerWidth() - 4});
                    e.preventDefault();
                    e.stopPropagation();
                }

            }
        });

        $('.navbar .dropdown').on('hidden.bs.dropdown', function () {
            $(this).find('li.dropdown').removeClass('show open');
            $(this).find('ul.dropdown-menu').removeClass('show open');
        });

    });

</script>
<script>

    $(document).ready(function () {
        $('[data-toggle="popover"]').popover();
    });
</script>


<?php (Message::getMessage('errors')); ?>
