<html lang="en">
<head>
    <title>E-Learning</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="/design/site/css/bootstrap.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/design/site/css/bootstrap.min.css">

    <!-- GOOGLE WEB FONT -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800" rel="stylesheet">

    <!-- BASE CSS -->
    <link href="/design/site/css/style.css" rel="stylesheet">
    <link href="/design/site/css/vendors.css" rel="stylesheet">
    <link href="/design/site/css/icon_fonts/css/all_icons.min.css" rel="stylesheet">

    <!-- YOUR CUSTOM CSS -->
    <link href="/design/site/css/custom.css" rel="stylesheet">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="/images/icons/favicon.ico"/>
    <!--===============================================================================================-->
    <!--    <link rel="stylesheet" type="text/css" href="../vendor/bootstrap/css/bootstrap.min.css">-->
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/design/site/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/design/site/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/design/site/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/design/site/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/design/site/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/design/site/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/design/site/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/design/site/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/design/site/css/util-contact.css">
    <link rel="stylesheet" type="text/css" href="/design/site/css/main-contact.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" href="/design/site/css/style-header.css">
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top head" id="main_navbar">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>

    </button>
    <center><a class="navbar-brand" href="#">Step Forward</a></center>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

        <ul class="navbar-nav mr-auto mt-2 mt-lg-0" id="nav">
            <li class="nav-item active">
                <a class="nav-link navmy" href="/home/home"><i class="icon-home"></i>Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ">
                <a  class="nav-link navmy" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="icon-th"></i>Categories
                </a>

            </li>

<!--            <li class="nav-item">-->
<!---->
<!--                 -->
<!---->
<!--            </li>-->

        </ul>
        <div class="visible-lg-block visible-xl-block header-right-divider"></div>
        <form class="navbar-form search">
            <div class="form-group">
                <div class="input-icons">
                    <i class="icon-search icon"></i>
                    <input class="form-control sea" type="text" placeholder="search any thing">
                </div>
            </div>
        </form>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0 two">

            <!--    /* after session*/-->




            <?php if (!isset($_SESSION['user'])) { ?>
                <li class="nav-item dropdown heart">
                    <a class="nav-link  dropdown-toggle" title="my_cart" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="icon-cart mycart"></i>
                        <span class="badge badge-danger badge-counter">3</span>
                    </a>
                    <div class="dropdown-menu dm" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Cart is empty <br></a>
                        <a class="dropdown-item" id="link" href="/home/cart1">Keep Shopping</a>
                    </div>
                </li>
                <li class="nav-item">
                    <!--        <a href="#" class="nav-link"><button  type="submit" class="btn  btn-quaternary" data-toggle="modal" data-target="#loginModal">Log In</button>-->
                    <!--        </a>-->
                    <a href="/admin/login" class=" btn btn-danger btn-quaternary btn-block nav-link">Log In </a>

                </li>
                <li class="nav-item">
                    <!--        <a href="#"class="nav-link"><button  type="submit" class=" btn btn-danger btnn" data-toggle="modal" data-target="#signupModal">Sign Up</button>-->
                    <!--        </a>-->
                    <a href="/admin/register" class="btn btn-danger btnn btn-block nav-link">Sign Up </a>

                </li>
            <?php } else { ?>
                    <li class="nav-item"><a href="" class="nav-link"> </a></li>
                    <li class="nav-item dropdown heart">
                        <a class="nav-link  dropdown-toggle" title="" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            MyCourses

                        </a>
                        <div class="dropdown-menu dm" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#"> <br></a>
                            <a class="dropdown-item"  href="">no courses</a>
                            <a class=" btn dropdown-item btn-primary"  href="/home/mycourses">see</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown heart">
                        <a class="nav-link  dropdown-toggle" title="wish list" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class=" icon_heart_alt  mycart"></i>
                            <span class="badge badge-danger badge-counter">3</span>
                        </a>
                        <div class="dropdown-menu dm" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">wishList is empty <br></a>
                            <a class="dropdown-item"  id="link" href="/home/wish-list">Wish List</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown heart">
                        <a class="nav-link  dropdown-toggle" title="notification" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="icon-bell-alt mycart"></i>
                            <span class="badge badge-danger badge-counter">3</span>
                        </a>
                        <div class="dropdown-menu dm" aria-labelledby="navbarDropdown">
                            <i class=" icon_setting"></i>
                            <a class="dropdown-item" href="#">notification</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item">No notification</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown heart">
                        <a class="nav-link  dropdown-toggle" title="my_cart" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="icon-cart mycart"></i>
                            <span class="badge badge-danger badge-counter">3</span>
                        </a>
                        <div class="dropdown-menu dm" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Cart is empty <br></a>
                            <a class="dropdown-item"  id="link" href="/home/cart1">Keep Shopping</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown heart">
                        <a class="nav-link  dropdown-toggle" title="information user" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="icon-user mycart"></i>
                            <span class="badge badge-danger badge-counter">3</span>
                        </a>
                        <div class="dropdown-menu dm" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item"   href="">profile</a>
                            <a href="/admin/logout" class="btn btn-danger btn-block"> logout </a>
                            <a class="dropdown-item"   href="">Message</a>
                        </div>
                    </li>

                <!--    /* end after session*/-->

            <?php } ?>
            <!--    /* end befor session*/-->
        </ul>


    </div>
</nav>

<!--sign up-->
<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content login">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Log In Your Site Account</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="name" class="col-form-label">Full Name:</label>
                        <input type="text" class="form-control" id="email" name="name">
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-form-label">Email:</label>
                        <input type="text" class="form-control" id="email" name="email">
                    </div>
                    <div class="form-group">
                        <label for="password" class="col-form-label">Password:</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    <button type="submit" class="btn btn-danger btn-block" data-dismiss="modal"> Sign Up</button>
                </form>
                <hr>
                <center>Already have an account? <a href="#" id="log" data-toggle="modal" data-target="#loginModal">Log
                        In</a></center>
            </div>

        </div>
    </div>
</div>

<!--login-->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content login">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Log In Your Site Account</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="email" class="col-form-label">Email:</label>
                        <input type="text" class="form-control" id="email" name="email">
                    </div>
                    <div class="form-group">
                        <label for="password" class="col-form-label">Password:</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    <button type="submit" class="btn btn-danger btn-block" data-dismiss="modal">Log In</button>
                </form>
                <center>or <a data-toggle="modal" data-target="#forgotModal" href="#" id="forget"> Forgot
                        Password</a><br><br></center>
                <center>Don't have an account? <a href="#" data-toggle="modal" data-target="#signupModal" id="signup">Sign
                        Up</a></center>
            </div>

        </div>
    </div>
</div>
<div class="modal fade" id="forgotModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content login">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Forgot Password</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="email" class="col-form-label">Email:</label>
                        <input type="text" class="form-control" id="email" name="email">
                    </div>

                    <button type="submit" data-toggle="modal" data-target="#newpwModal" class="btn btn-danger btn-block"
                            data-dismiss="modal">Reset Password
                    </button>
                </form>
                <center>or <a data-toggle="modal" data-target="#loginModal" href="#" id="login1">Log In</a><br><br>
                </center>

            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="newpwModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content login">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Forgot Password</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="password" class="col-form-label"> New Password:</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>

                    <button type="submit" class="btn btn-danger btn-block" data-dismiss="modal">Save Change</button>
                </form>


            </div>

        </div>
    </div>
</div>
</body>