</div>


<div class="jumbotron text-center" style="margin-bottom:0">
    <p>Footer</p>
    <div class="container text-right text-center">
        <hr class=" featurette-divider">
        <div class="row" style="margin-bottom:5px;">
            <div class="col-md-4 tmp">
                <h5>مواقع مشابهة</h5>
                <ul type="none" class="dis">
                    <li><a href="#">www.samsung.com</a></li>
                    <li><a href="#">www.apple.com</a></li>
                </ul>

            </div>
            <div class="col-md-4 tmp">
                <h5>تفاعل معنا على شبكات التواصل الأجتماعي</h5>

            </div>
            <div class="col-md-4 text-center">
                <h5>من نحن؟</h5>
                <ul class="dis list-unstyle">
                    <li><a href="../useres/about.php">عنا</a></li>
                    <li><a href="../useres/contact.php">إتصل بنا</a></li>
                </ul>
            </div>

        </div>
        <div align="center">
            <h4>جميع الحقوق محفوضة &copy 2019 </h4>
        </div>
    </div>

</div>


<div class='navbar navbar-inverse navbar-fixed-top'>
    <div class='container text-center'>
        <div class='navbar-header'>
            <button type='button' class='navbar-toggle collapsed' data-toggle='collapse'
                    data-target='#navbarsection'
                    aria-expanded='false' aria-controls='navbar'>
                <span class='sr-only'>Toggle navigation</span>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
            </button>
        </div>
        <div class='navbar-collapse collapse' id='navbarsection'>
            <ul class='nav navbar-nav navbar-left'>
                <li><a href='index.php'>الرئيسية </a></li>
                <li class='dropdown '>
                    <a href='' class='dropdown-toggle' data-toggle='dropdown'>
                        التصنيفات
                        <i class='fa fa-caret-down'></i></a>
                    <ul class='dropdown-menu'>
                        <li><a href='pages.php?cat_id=1'>????? </a></li>
                        <li><a href='pages.php?cat_id=2'>????? </a></li>
                        <li><a href='pages.php?cat_id=3'>?????? </a></li>
                    </ul>
                </li>
            </ul>
            <div class='navbar-collapse navbar-right' id='navbarsection'>
                <ul class='nav navbar-nav navbar-left'>
                    <li><a href='register.php'> التسجيل في موقعنا <i
                                    class='glyphicon glyphicon-edit'></i></a></li>
                    <li><a href='login.php'> تسجيل دخول <i class='glyphicon glyphicon-log-in'></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php (Message::getMessage('errors')); ?>
<br>
<br>
<br>


</div>


</body>

</html>
