<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>

<link href="/design/dashboard/lib/google-code-prettify/bin/prettify.min.css" rel="stylesheet">

<!-- Select2 -->
<link href="/design/dashboard/lib/select2/dist/css/select2.min.css" rel="stylesheet">
<!-- Switchery -->
<link href="/design/dashboard/lib/switchery/dist/switchery.min.css" rel="stylesheet">
<!-- starrr -->
<link href="/design/dashboard/lib/starrr/dist/starrr.css" rel="stylesheet">
<link rel="stylesheet" href="/design/dashboard/lib/jquery-ui/jquery-ui.css">


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<!-- Start Main-content -->
<div class="container">

    <div class="row bg-white mb-4 ">
        <div class="text-right mt-auto col-6">
            <h3><i class="fa fa-list" style="color:#ec3901"></i> ادارة الاقسام </h3>
        </div>
    </div>

    <?php include VIEW . 'messages.phtml' ?>
    <form action="/admin/categories/store" method="post">
        <div class="form-group">
            <label for="course_title">اسم القسم :</label>
            <input type="text" class="form-control" id="course_title" placeholder="اسم القسم"
                   value="<?php Helper::old('category_name'); ?>"
                   name="category_name">
            <?php echo Message::getInputErrorMessage('category_name') ?>

        </div>

        <div class="form-group">
            <label for="course__description">الوصف:</label>
            <textarea type="text" rows="7" class="form-control" id="course__description" name="category_description">
            </textarea>
        </div>



        <div class="form-group">
            <label for="main_category_parents">القسم الرئيسي (الاب):</label>

            <select class="select2" id="main_category_parents" name="main_category_parents"
                    data-placeholder="Major" style="width: 100%;">
                <option value="0" selected> اختيار القسم الرئيسي</option>
                <?php if (array_key_exists('MainCategories', $this->view_data)) {
                    foreach ($this->view_data['MainCategories'] as $category) { ?>

                        <option value="<?php echo $category['category_id'] ?>"> <?php echo $category['category_name'] ?> </option>

                    <?php }
                } ?>

            </select>
        </div>


        <div class="form-group">
            <label for="sub_category">القسم الفرعي(المتفرع من الاب): </label>

            <select id="sub_category" class="select2" name="sub_category_parents"
                    data-placeholder="Field" style="width: 100%;">
                <option value="0" selected> اختيار القسم الفرعي</option>
            </select>
        </div>




        <!---->
        <!--        <label for="category_visibility">Category Visibility:</label>-->
        <!--        <div class="custom-control custom-radio">-->
        <!--            <input type="radio" class="custom-control-input" id="course_visibility" name="category_visibility"-->
        <!--                   value="yes">-->
        <!--            <label class="custom-control-label" for="category_visibility">yes</label><br>-->
        <!--            <input type="radio" class="custom-control-input" id="course_visibility" name="category_visibility"-->
        <!--                   value="no">-->
        <!--            <label class="custom-control-label" for="category_visibility">no</label>-->
        <!--        </div>-->
        <!--        -->


        <button type="submit" name="submit" class="btn btn-success btn-block">اضافة</button>
    </form>
    <br>

</div>


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<script src="/design/dashboard/lib/jquery.tagsinput/src/jquery.tagsinput.js"></script>
<!-- Select2 -->
<script src="/design/dashboard/lib/select2/dist/js/select2.full.min.js"></script>
<!-- Parsley -->
<script src="/design/dashboard/lib/parsleyjs/dist/parsley.min.js"></script>
<script src="/design/dashboard/lib/parsleyjs/dist/i18n/ar.js"></script>

<!-- jQuery autocomplete -->
<script src="/design/dashboard/lib/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>

<script src="/design/dashboard/lib/jquery-ui/jquery-ui.js"></script>

<script>

    $(function () {
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2').select2()
    })
</script>
<script>


    fetchCategories('#main_category_parents', '#sub_category');
    fetchCategories('#sub_category', '#sub_sub_category');

    function fetchCategories(input, select) {

        $(document).on('change', input, function () {
            var data = 'category_parents=' + encodeURIComponent($(this).val());
            var url = '/admin/Categories/fetchSubCategories';
            $.ajax({
                url: url,//   var url=$('#news').attr('action');
                method: 'POST',
                dataType: 'json',// data type that i want to return
                data: data,// var form=$('#news').serialize();
                success: function (data) {
                    $(select).html(data);

                }, error:
                    function (xhr, status, error) {
                        $(select).html(xhr.responseText);
                    }
            });
            return (false);
        });
    }


</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>
