<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>

<link href="/design/dashboard/lib/google-code-prettify/bin/prettify.min.css" rel="stylesheet">

<!-- Select2 -->
<link href="/design/dashboard/lib/select2/dist/css/select2.min.css" rel="stylesheet">
<!-- Switchery -->
<link href="/design/dashboard/lib/switchery/dist/switchery.min.css" rel="stylesheet">
<!-- starrr -->
<link href="/design/dashboard/lib/starrr/dist/starrr.css" rel="stylesheet">
<link rel="stylesheet" href="/design/dashboard/lib/jquery-ui/jquery-ui.css">


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<div class="content">
    <h2 class="text-center"><i class="fa  fa-list"></i> Categories Add</h2>
    <form action="#" method="post">
        <div class="form-group">
            <label for="course_title">Category Name:</label>
            <input type="text" class="form-control" id="course_title" name="course_title">
        </div>
        <div class="form-group">
            <label for="course__description">Category Description:</label>
            <input type="text" class="form-control" id="course__description" name="course__description">
        </div>



        <div class="form-group">
            <label for="category_parents">Main Category(Major):</label>

            <select class="select2" name="category_parents[]" multiple="multiple"
                    data-placeholder="Major" style="width: 100%;">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>


            </select>
        </div>


        <div class="form-group">
            <label for="sub_category_parents">Sub Main Category(Field): </label>

            <select class="select2" name="sub_category_parents[]" multiple="multiple"
                    data-placeholder="Field" style="width: 100%;">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>


            </select>
        </div>



        <!--        <div class="form-group">-->
        <!--            <label for="exampleInputFile">الاقسام </label>-->
        <!---->
        <!--            <select class="select2 @error('categories2')  is-invalid @enderror" name="categories[]" multiple="multiple"-->
        <!--                    data-placeholder="التصنيفات" style="width: 100%;">-->
        <!--                --><?php //foreach(Helper::getCategories() as $category){ ?>
        <!--                    <option value="--><?php //echo $category['id']; ?><!--"-->
        <!--                        -->
        <?php // if (array_key_exists('news', $this->view_data) and in_array($category['id'], json_decode($this->view_data['news']['categories2']))) echo 'selected';?><!-- >-->
        <?php //echo $category['name_ar']; ?><!-- </option>-->
        <!---->
        <!--                --><?php //} ?>
        <!---->
        <!---->
        <!--            </select>-->
        <!--        </div>-->

        <div class="form-group">
            <label for="sub_sub_category">Sub Sub Category(Subject): </label>

            <select class="select2" name="sub_sub_category[]" multiple="multiple"
                    data-placeholder="Subject" style="width: 100%;">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>


            </select>
        </div>

        <div class="form-group">
            <label for="category_description">Category Description:</label>
            <textarea class="form-control" id="category_description" name="category_description">
                </textarea>
        </div>



        <label for="category_visibility">Category Visibility:</label>
        <div class="custom-control custom-radio">
            <input type="radio" class="custom-control-input" id="course_visibility" name="category_visibility"
                   value="yes">
            <label class="custom-control-label" for="category_visibility">yes</label><br>
            <input type="radio" class="custom-control-input" id="course_visibility" name="category_visibility"
                   value="no">
            <label class="custom-control-label" for="category_visibility">no</label>
        </div>
        <button type="submit" name="submit" class="btn btn-primary">Submit</button>
    </form>
    <br>

</div>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.php' ?>
<script src="/design/dashboard/lib/jquery.tagsinput/src/jquery.tagsinput.js"></script>
<!-- Switchery -->
<script src="/design/dashboard/lib/switchery/dist/switchery.min.js"></script>
<!-- Select2 -->
<script src="/design/dashboard/lib/select2/dist/js/select2.full.min.js"></script>
<!-- Parsley -->
<script src="/design/dashboard/lib/parsleyjs/dist/parsley.min.js"></script>
<script src="/design/dashboard/lib/parsleyjs/dist/i18n/ar.js"></script>
<!-- Autosize -->
<script src="/design/dashboard/lib/autosize/dist/autosize.min.js"></script>
<!-- jQuery autocomplete -->
<script src="/design/dashboard/lib/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
<!-- starrr -->
<script src="/design/dashboard/lib/starrr/dist/starrr.js"></script>

<script src="/design/dashboard/lib/jquery-ui/jquery-ui.js"></script>

<script>

    $(function () {
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2').select2()
    })
</script>
<script>


    $(document).on('change', '#logo', function () {


        if (window.File && window.FileReader && window.FileList && window.Blob) //check File API supported browser
        {
            var data = $(this)[0].files; //this file data
            $('#logo_image').html('');
            $.each(data, function (index, file) { //loop though each file
                if (/(\.|\/)(gif|jpe?g|png)$/i.test(file.type)) { //check supported file type
                    var fRead = new FileReader(); //new filereader
                    fRead.onload = (function (file) { //trigger function on successful read
                        return function (e) {
                            var img = $('<img/>').addClass('thumb').attr('src', e.target.result); //create image element
                            $('#logo_image').append(img); //append image to output element
                        };
                    })(file);
                    fRead.readAsDataURL(file); //URL representing the file's data.
                }
            });
        } else {
            alert("Your browser doesn't support File API!"); //if File API is absent
        }
    });

    CKEDITOR.replace('editor', {filebrowserImageBrowseUrl: '/file-manager/ckeditor'});
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>

