<?php use auth\Permissions;

include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableCss.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<!-- Start Main-content -->
<div class="container">
    <div class="row bg-white mb-4 ">
        <div class="text-right  mt-auto col-6">
            <h3><i class="fa fa-list" style="color:#ec3901"></i> ادارة الاقسام </h3>
        </div>
    </div>
    <?php include VIEW . 'messages.phtml' ?>


    <div class="row mb-4">
        <div class="col-6 text-right">
            <?php if (Permissions::getInstaince()->hasPermision('category_create') == true) { ?>
                <a href="/admin/categories/create" class="btn btn-success"><i class="fa fa-plus"> </i> إنشاء قسم
                    جديد</a>
            <?php } ?>
        </div>
        <div class="col-6 text-left">
            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                        id="dashboard_daterangepicker">
                    <i class="	fas fa-bullseye"></i> ترتيب حسب
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Day</a>
                    <a class="dropdown-item" href="#">Week</a>
                    <a class="dropdown-item" href="#">Month</a>
                    <a class="dropdown-item" href="#">Range</a>
                </div>
            </div>
        </div>
    </div>


    <br>
    <table id="example1" class="table table-bordered table-striped">
        <thead class="thead-dark font-size-16">
        <tr>
            <th> #</th>
            <th>اسم القسم</th>
            <th>الوصف</th>
            <th>القسم الاب</th>
            <?php if (Permissions::getInstaince()->hasPermision('category_edit') == true
                or Permissions::getInstaince()->hasPermision('category_delete') == true
            ) { ?>
                <th>الاعدادات</th>
            <?php } ?>

        </tr>
        </thead>

        <tbody>
        <?php if (array_key_exists('categories', $this->view_data)) {
            foreach ($this->view_data['categories'] as $k => $category) { ?>


                <tr>
                    <td><?php echo $k ?></td>
                    <td><?php echo $category['category_name'] ?></td>
                    <td><?php echo $category['category_description'] ?></td>

                    <td> <?php echo Helper::getCategoryName(str_replace('level3_', '', $category['category_parents'])) ?></td>

                    <td>
                        <a href="" data-id="<?php echo $category['category_id'] ?>"
                           data-visibility="<?php echo $category['category_visibility'] ?>"
                           class="btn_visibility"><?php echo ($category['category_visibility'] == '1') ? ' <i class="fa fa-eye"> </i>' : '  <i class="fa fa-eye-slash"> </i>' ?> </a>
                    </td>
                    <td>
                        <a href="" data-id="<?php echo $category['category_id'] ?>"
                           data-status="<?php echo $category['category_status'] ?>"

                    </td>
                    <?php if ($this->view_data['deleted'] == false) { ?>

                        <?php if (Permissions::getInstaince()->hasPermision('category_edit') == true
                            or Permissions::getInstaince()->hasPermision('category_delete') == true
                        ) { ?>
                            <td>
                                <?php if (Permissions::getInstaince()->hasPermision('category_edit') == true) { ?>
                                    <a href="/admin/categories/edit/<?php echo $category['id'] ?>"><i
                                                class="fa fa-edit"></i></a>
                                <?php } ?>
                                <?php if (Permissions::getInstaince()->hasPermision('category_delete') == true) { ?>

                                    <a href="/admin/categories/delete/<?php echo $category['id'] ?>"
                                       onclick="return confirm('هل أنت متأكد من الحذف');"><i
                                                class="fa fa-trash-restore"></i></a>
                                <?php } ?>
                            </td>
                        <?php } ?>

                    <?php } else { ?>

                        <!--                        <th>{{getUserName( $category['deleted_by'] )?></th>-->
                        <!--                        <td>--><?php //echo $category['deleted_at'] ?><!--</td>-->

                        <td class="text-center">
                            <a href="{{  route('admin.universities.restore',encrypt( $category['']id)) }}"
                               class="btn btn-primary"><i
                                        class="fa fa-arrow-up"></i></a>
                        </td>

                    <?php } ?>


                </tr>
            <?php }
        } ?>
    </table>
</div>
<!-- End Main-content -->

</div>
<!-- End Content -->
</div>
</div>


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableJs.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'active.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'visibility.phtml' ?>

<script>

    Active('categories');
    Visible('categories');
    $(function () {
        $('#example1').DataTable({
            language: {url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Arabic.json"},
            dom: "Blfrtip",
            buttons: [{extend: "copy", text: "نسخ", className: "btn-sm"}, {
                extend: "csv",
                text: "ملف CSV",
                className: "btn-sm"
            }, {extend: "excel", text: "اکسل", className: "btn-sm"}, {
                extend: "pdfHtml5",
                text: "ملف PDF",
                className: "btn-sm"
            }, {extend: "print", text: "طباعة", className: "btn-sm"}],
            responsive: !0
        });
    });
</script>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>




