<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableCss.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>

<div class="content">
    <h2 class="text-center"><i class="fa fa-list"></i> Categories Manage</h2>
    <?php include VIEW . 'messages.phtml' ?>
    <div class="row fa-pull-right">
        <div class="col-8">
            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                        id="dashboard_daterangepicker">
                    <i class="	fas fa-bullseye"></i> sorting data by
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Day</a>
                    <a class="dropdown-item" href="#">Week</a>
                    <a class="dropdown-item" href="#">Month</a>
                    <a class="dropdown-item" href="#">Range</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-4"><a href="/admin/categories/create" class="btn btn-primary "><i class="fa fa-plus"> </i> Add</a>
    </div>
    <table id="example1" class="table table-bordered table-striped">
        <thead class="thead-dark font-size-18">
        <tr>
            <th> #</th>
            <th>Category Name</th>
            <th>description</th>
            <th>Category Parents</th>
            <th>Category Visibility</th>
            <th>Category Status</th>
            <th>update</th>
            <th>delete</th>
        </tr>
        </thead>

        <tbody>
        <?php if (array_key_exists('categories', $this->view_data)) {
            foreach ($this->view_data['categories'] as $k => $category) { ?>


                <tr>
                    <td><?php echo $k ?></td>
                    <td><?php echo $category['category_name'] ?></td>
                    <td><?php echo $category['category_description'] ?></td>

                    <td> <?php echo Helper::getCategoryName(str_replace('level3_', '', $category['category_parents'])) ?></td>

                    <td>
                        <button data-id="<?php echo $category['category_id'] ?>"
                                data-visibility="<?php echo $category['category_visibility'] ?>"
                                class="btn btn-success btn_visibility"><?php echo ($category['category_visibility'] == '1') ? ' <i class="fa fa-eye"> </i>' : '  <i class="fa fa-eye-slash"> </i>' ?> </button>
                    </td>
                    <td>
                        <button data-id="<?php echo $category['category_id'] ?>"
                                data-status="<?php echo $category['category_status'] ?>"
                                class="btn btn-success active"><?php echo ($category['category_status'] == '1') ? '<i class=\'fas fa-check\'></i>' : '<i class=\'ion ion-close\'></i>' ?> </button>
                    </td>


                    <?php if ($this->view_data['deleted'] == false) { ?>
                        <td><a href="Categories.php?do=edit" class="btn btn-success"><i class="fa fa-edit"></i></a></td>

                        <td>
                            <a href="/admin/universities/delete/<?php echo $category['id'] ?>"
                               onclick="return confirm('هل أنت متأكد من الحذف');" class="btn btn-danger"><i
                                        class="fa fa-trash"></i></a>

                        </td>
                    <?php } else { ?>
                        <th>{{getUserName( $category['deleted_by'] )?></th>
                        <td><?php echo $category['deleted_at'] ?></td>


                        <td class="text-center">
                            <a href="{{  route('admin.universities.restore',encrypt( $category['']id)) }}"
                               class="btn btn-primary"><i
                                        class="fa fa-arrow-up"></i></a>
                        </td>

                    <?php } ?>


                </tr>
            <?php }
        } ?>
    </table>
</div>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.php' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableJs.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'active.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'visibility.phtml' ?>

<script>

    Active('categories');
    Visible('categories');
    $(function () {
        $('#example1').DataTable({
            language: {url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Arabic.json"},
            dom: "Blfrtip",
            buttons: [{extend: "copy", text: "copy", className: "btn-sm"}, {
                extend: "csv",
                text: " CSV",
                className: "btn-sm"
            }, {extend: "excel", text: "excel", className: "btn-sm"}, {
                extend: "pdfHtml5",
                text: " PDF",
                className: "btn-sm"
            }, {extend: "print", text: "print", className: "btn-sm"}],
            responsive: !1
        });
    });
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>




