<script>
    function Active(controller) {
        $(document).on('click', '.btn_active', function () {
            var data = 'status=' + encodeURIComponent($(this).attr('data-status')) + '&data_id=' + encodeURIComponent($(this).attr('data-id'));
            var url = '/admin/' + controller + '/active';
            var _this = $(this);
            $.ajax({
                url: url,//   var url=$('#news').attr('action');
                method: 'POST',
                dataType: 'json',// data type that i want to return
                data: data,// var form=$('#news').serialize();
                success: function (data) {
                    if (data == 1) {
                        _this.text("Active");
                        _this.attr("data-status", data);
                    } else {
                        _this.text("Deny");
                        _this.attr("data-status", data);
                    }
                },
                error: function (xhr, status, error) {
                    alert(xhr.responseText);
                }
            });
            return (false);
        });

    }

</script>
