<script>

    function AddToWish(controller, page = 'home') {
        $(document).on('click', '.addToWishList', function () {
            var id = $(this).attr('data-id');
            var data = 'status=' + encodeURIComponent($(this).attr('data-status')) + '&id=' + encodeURIComponent(id);

            var url = controller + '/insertCourseUser';
            var _this = $(this);
            $.ajax({
                url: url,//   var url=$('#news').attr('action');
                method: 'POST',
                dataType: 'json',// data type that i want to return
                data: data,// var form=$('#news').serialize();
                success: function (data) {
                    if (data > 0) {
                        if (_this.attr('data-status') == 1) {
                            _this.attr('class', 'wish_bt addToWishList');
                            _this.attr('data-status', 0);
                            _this.attr('onclick', "confirm('هل تريد اضافة هذا الكورس الى المفضلة ')");
                            $('#n_whishList_items').text(parseInt($('#n_whishList_items').text()) - 1);
                            if (page == 'whishList')
                                $('#course_' + id).remove();
                        } else {
                            _this.attr('class', 'wish_bt_active addToWishList');
                            _this.attr('data-status', 1);
                            _this.attr('onclick', "confirm('هل تريد الغاء هذا الكورس من المفضلة ')");
                            $('#n_whishList_items').text(parseInt($('#n_whishList_items').text()) + 1);

                        }

                    }
                },
                error: function (xhr, status, error) {
                    alert(xhr.responseText);
                }
            });
            return (false);
        });
    }

    function Active(controller) {
        $('.active').on('click', function () {
            var data = 'status=' + encodeURIComponent($(this).attr('data-status')) + '&data_id=' + encodeURIComponent($(this).attr('data-id'));
            var url = '/admin/' + controller + '/active';
            var _this = $(this);
            $.ajax({
                url: url,//   var url=$('#news').attr('action');
                method: 'POST',
                dataType: 'json',// data type that i want to return
                data: data,// var form=$('#news').serialize();
                success: function (data) {
                    if (data == 1) {
                        _this.html("<i class='fa fa-check text-primary'></i>");
                        _this.attr("data-status", data);
                    } else {
                        _this.html("<i class='ion ion-close text-danger'></i>");
                        _this.attr("data-status", data);
                    }
                },
                error: function (xhr, status, error) {
                    alert(xhr.responseText);
                }
            });
            return (false);
        });
    }


</script>
