<link href="/design/dashboard/lib/dataTable/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="/design/dashboard/lib/dataTable/data-table/css/buttons.dataTables.min.css" rel="stylesheet">
<link href="/design/dashboard/lib/dataTable/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet">
<link href="/design/dashboard/lib/dataTable/data-table/extensions/responsive/css/responsive.dataTables.css" rel="stylesheet">

