<script src="/design/dashboard/lib/dataTable/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/design/dashboard/lib/dataTable/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="/design/dashboard/lib/dataTable/data-table/js/jszip.min.js"></script>
<script src="/design/dashboard/lib/dataTable/data-table/js/pdfmake.min.js"></script>
<script src="/design/dashboard/lib/dataTable/data-table/js/vfs_fonts.min.js"></script>
<script src="/design/dashboard/lib/dataTable/data-table/extensions/buttons/js/dataTables.buttons.min.js"></script>
<script src="/design/dashboard/lib/dataTable/data-table/extensions/buttons/js/buttons.flash.min.js"></script>
<script src="/design/dashboard/lib/dataTable/data-table/extensions/buttons/js/jszip.min.js"></script>
<script src="/design/dashboard/lib/dataTable/data-table/extensions/buttons/js/vfs_fonts.min.js"></script>
<script src="/design/dashboard/lib/dataTable/data-table/extensions/buttons/js/vfs_fonts.min.js"></script>
<script src="/design/dashboard/lib/dataTable/data-table/extensions/buttons/js/buttons.colVis.min.js"></script>
<script src="/design/dashboard/lib/dataTable/datatables.net-buttons/js/buttons.print.min.js"></script>
<script src="/design/dashboard/lib/dataTable/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="/design/dashboard/lib/dataTable/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/design/dashboard/lib/dataTable/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="/design/dashboard/lib/dataTable/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>



