<link href="/design/dashboard/lib/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link href="/design/dashboard/lib/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
<link href="/design/dashboard/lib/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
<link href="/design/dashboard/lib/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
<link href="/design/dashboard/lib/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
<link href="/design/dashboard/lib/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

