<script src="/design/dashboard/js/jquery-3.3.1.min.js"></script>
<script src="/design/dashboard/js/popper.min.js"></script>
<script src="/design/dashboard/js/bootstrap.min.js"></script>
<script src="/design/dashboard/js/all.min.js"></script>
<script src="/design/dashboard/js/echarts-en.min.js"></script>
<script src="/design/dashboard/js/anime.min.js"></script>
<script src="/design/dashboard/js/dash.js"></script>
<script src="/design/dashboard/js/design.js"></script>
<script src="/design/dashboard/js/main.js"></script>
<script src="/design/dashboard/js/my-login.js"></script>
<script src="/design/dashboard/js/validate.js"></script>
<script src="/design/dashboard/lib/tinymce/jquery.tinymce.min.js" referrerpolicy="origin"></script>
<script src="/design/dashboard/lib/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
<script>
        tinymce.init({
            selector : 'textarea',
            plugins : 'image',
            toolbar : 'image',

            images_upload_url : 'upload.php',
            automatic_uploads : false,

            images_upload_handler : function(blobInfo, success, failure) {
                var xhr, formDa ta;

                xhr = new XMLHttpRequest();
                xhr.withCredentials = false;
                xhr.open('POST', 'upload.php');

                xhr.onload = function() {
                    var json;

                    if (xhr.status != 200) {
                        failure('HTTP Error: ' + xhr.status);
                        return;
                    }

                    json = JSON.parse(xhr.responseText);

                    if (!json || typeof json.file_path != 'string') {
                        failure('Invalid JSON: ' + xhr.responseText);
                        return;
                    }

                    success(json.file_path);
                };

                formData = new FormData();
                formData.append('file', blobInfo.blob(), blobInfo.filename());

                xhr.send(formData);
            },
        });
    </script>
<?php (Message::getMessage('errors')); ?>
<?php Session::delete('oldFormData'); ?>

