<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?php echo(isset($this->pageTitle) ? $this->pageTitle : 'page'); ?> </title>

    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->

    <link rel="stylesheet" href="/design/dashboard/css/fontawesome.min.css">
    <link rel="stylesheet" href="/design/dashboard/css/bootstrap.css">

    <link rel="stylesheet" href="/design/dashboard/css/dash.css">

    <link rel="stylesheet" href="/design/dashboard/css/login.css">
    <link rel="stylesheet" href="/design/dashboard/css/ionicons.css">
    <link rel="stylesheet" href="/design/dashboard/css/bootstrap-extend.css">
    <link rel="stylesheet" href="/design/dashboard/css/anime.css">
