<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableCss.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterHead.phtml' ?>
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">الاقسام الرئيسية</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active">الاقسام</li>
                    <li class="breadcrumb-item"><a href="/admin/index">البداية </a></li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<div class="d-flex justify-content-end">
    <a href="/admin/categories/create" class="btn btn-primary"><i class="fa fa-plus"></i></a>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <!-- /.card-header -->
        <div class="x_content">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>الاسم العربي</th>
                    <th>الاسم االانجليزي</th>
                    <th>القسم الرئيسي</th>
                    <?php if ($this->view_data['deleted'] == false) { ?>

                        <th>عدد الاقسام</th>
                        <th> القائمة الرئيسية</th>
                        <th>تعرض سلايدات</th>
                        <th>الترتيب</th>
                        <th>الحالة</th>

                        <th>تعديل</th>
                    <?php } else { ?>

                        <th>حذفة بواسطة</th>
                        <th>تاريخ الحذف</th>
                        <th>استعادة</th>
                    <?php } ?>

                    <th>حذف</th>
                </tr>
                </thead>

                <tbody>
                <?php if (array_key_exists('categories2', $this->view_data)) {
                    foreach ($this->view_data['categories2'] as $category) { ?>

                        <tr>
                            <td><?php echo $category['name_ar'] ?></td>
                            <td><?php echo $category['name_en'] ?></td>
                            <td><?php echo Helper::getCategoryName($category['parent']) ?></td>


                            <?php if ($this->view_data['deleted'] == false) { ?>


                                <td><?php echo $category['section_count'] ?></td>

                                <td><?php echo ($category['isMain'] == '1') ? 'نعم' : 'لا' ?></td>
                                <td><?php echo ($category['hasSlides'] == '1') ? 'نعم' : 'لا' ?></td>
                                <td><?php echo $category['sort'] ?></td>
                                <td><?php echo ($category['status'] == '1') ? 'مفعل' : 'معطل' ?></td>


                                <td class="text-center">
                                    <a href="/admin/categories/edit/<?php echo $category['id'] ?>"
                                       class="btn btn-primary"><i
                                                class="fa fa-pencil"></i></a>
                                </td>

                            <?php } else { ?>
                                <th>{{getUserName( $category['deleted_by'] )?></th>
                                <td><?php echo $category['deleted_at'] ?></td>


                                <td class="text-center">
                                    <a href="{{  route('admin.categories.restore',encrypt( $category['']id)) }}"
                                       class="btn btn-primary"><i
                                                class="fa fa-arrow-up"></i></a>
                                </td>

                            <?php } ?>


                            <td class="text-center">
                                <a href="/admin/categories/delete/<?php echo $category['id'] ?>"
                                   onclick="return confirm('هل أنت متأكد من الحذف');" class="btn btn-danger"><i
                                            class="fa fa-trash"></i></a>
                            </td>


                        </tr>
                    <?php }
                } ?>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
</div>


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.blade.php' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableJs.phtml' ?>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterFooter.blade.php' ?>
<script>


    $(function () {
        $('#example1').DataTable({
            language: {url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Arabic.json"},
            dom: "Bfrtip",
            buttons: [{extend: "copy", text: "نسخ", className: "btn-sm"}, {
                extend: "csv",
                text: "ملف CSV",
                className: "btn-sm"
            }, {extend: "excel", text: "اکسل", className: "btn-sm"}, {
                extend: "pdfHtml5",
                text: "ملف PDF",
                className: "btn-sm"
            }, {extend: "print", text: "طباعة", className: "btn-sm"}],
            responsive: !0
        });
    });
</script>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>


