<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>



<div class="row about-us">
        <div class="col-md-4">
            <div class="about-img">
                <div class=logo>
                    <img src="/images/logo.png" >

                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="aboutUS-text">
                <span >من نحن</span >
                <span >تأسست اكاديمية كورسات للتدريب عن بعد في عام 2020م وهدفها الرئيس تقدبم الخدمات التدريبية  وهي بهذا تسعى لتقديم خدماتها في المحيط المحلي لوطننا الغالي. إيمانا منها في وضع بصمة في حقل تنمية

                        وتطوير المتدربين ولتقديم خدمات متميزة تجمع بين حاجات المتدرب، وبين كل ما هو جديد في مجال التدريب والتطوير
                        . الأكاديمية كورسات للتدريب والتطوير تقدم التدريب<br>
                        بشقيه الكمي واللفظي في اختبار القدرات  وهدفها تحسين مستويات ابنائنا المتدربين ، لقد أخذنا على عاتقنا في الأكاديمية , نقل الخبرات إلى المتدربين مستعينين بذوي الخبرة المؤهلين بالشهادات والخبرة العملية في مجال التدريب، لجعل خدماتنا التدريبية  تدريباً عمليا ومناسباً لاحتياجات المتدربين والمتقدمين للاختبارات المستقبلية .</span >
            </div>

        </div>


</div>


<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>

