<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>

<div class="container">
    <div class="card" id="aboutCard">

        <div class="card-body"  id="about">
            <div class="row">
                <div class="col-6" id="aboutTitle">
                    <img src="/images/logo.png" width="400">
                </div>
                </div>

            <div class="row">
                <div class="col-10 text-left" id="textContact">
                   <span >من نحن</span >



                </div>
            </div>
            <div class="row">
                <div class="col-6 text-right mt-20" id="definition">
                    <span >تأسست الأكاديمية كورسات للتدريب عن بعد في عام 2020م وهدفها الرئيس تقدبم الخدمات التدريبية  وهي بهذا تسعى لتقديم خدماتها في المحيط المحلي لوطننا الغالي. إيمانا منها في وضع بصمة في حقل تنمية

                        وتطوير المتدربين ولتقديم خدمات متميزة تجمع بين حاجات المتدرب، وبين كل ما هو جديد في مجال التدريب والتطوير
                        . الأكاديمية كورسات للتدريب والتطوير تقدم التدريب<br>
                        بشقيه الكمي واللفظي في اختبار القدرات  وهدفها تحسين مستويات ابنائنا المتدربين ، لقد أخذنا على عاتقنا في الأكاديمية , نقل الخبرات إلى المتدربين مستعينين بذوي الخبرة المؤهلين بالشهادات والخبرة العملية في مجال التدريب، لجعل خدماتنا التدريبية  تدريباً عمليا ومناسباً لاحتياجات المتدربين والمتقدمين للاختبارات المستقبلية .</span >
                </div>
            </div>
            </div>
        </div>

    </div>

<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>

