<!-- /main_menu -->
<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>

<main>
    <section id="hero_in" class="cart_section">
        <div class="wrapper">
            <div class="container">
                <div class="bs-wizard clearfix">




                    <div class="bs-wizard-step disabled">
                        <div class="text-center bs-wizard-stepnum">الانتهاء</div>

                        <a href="#0" class="bs-wizard-dot"></a>
                    </div>
                    <div class="bs-wizard-step disabled">
                        <div class="text-center bs-wizard-stepnum">الدفع</div>
                        <div class="progress">
                            <div class="progress-bar"></div>
                        </div>
                        <a href="#0" class="bs-wizard-dot"></a>
                    </div>
                    <div class="bs-wizard-step active">
                        <div class="text-center bs-wizard-stepnum">سلتك</div>

                        <a href="#0" class="bs-wizard-dot"></a>
                    </div>
                </div>
                <!-- End bs-wizard -->
            </div>
        </div>
    </section>
    <!--/hero_in-->

    <div class="bg_color_1">
        <div class="container margin_61_35">
            <div class="row">
                <div class="col-lg-8">
                    <div class="box_cart">
                        <table class="table table-striped cart-list">
                            <thead>
                            <tr>
                                <th>
                                   الكورسات
                                </th>
                                <th>
                                    التخفيض
                                </th>
                                <th>
                                    السعر
                                </th>
                                <th>
                                   العمل
                                </th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php foreach ($this->view_data['cartElements'] as $course) { ?>
                                <tr id="cartElement<?php echo $course['course_id'] ?>">
                                    <td>
                                        <div class="thumb_cart">
                                            <img src="<?php echo $course['courses_image'] ?>"
                                                 alt="Image">
                                        </div>
                                        <span class="item_cart"><?php echo $course['course_title'] ?></span>
                                    </td>
                                    <td>
                                        0%
                                    </td>
                                    <td>
                                        <strong><?php echo $course['course_price'] ?>$</strong>
                                    </td>
                                    <td class="options" style="width:5%; text-align:center;">
                                        <button onclick="deleteFromCart('<?php echo $course['course_id'] ?>','<?php echo $course['course_price'] ?>')">
                                            <i
                                                    class="icon-trash"></i></button>
                                    </td>
                                </tr>
                            <?php } ?>

                            </tbody>
                        </table>
                        <div class="cart-options clearfix">
                            <div class="float-left">
                                <div class="apply-coupon">
                                    <div class="form-group">
                                        <input type="text" name="coupon-code" value="" placeholder="كود الكوبون"
                                               class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <button type="button" class="btn_1 outline">تطبيق الكوبون</button>
                                    </div>
                                </div>
                            </div>
                            <div class="float-right fix_mobile">
                                <button type="button" class="btn_1 outline">تحديث السلة</button>
                            </div>
                        </div>
                        <!-- /cart-options -->
                    </div>
                </div>
                <!-- /col -->

                <aside class="col-lg-4" id="sidebar">
                    <div class="box_detail">
                        <div id="total_cart">
                            المجموع <span
                                    class="float-right"><span
                                        id="total_price"> <?php echo($this->view_data['total']); ?> </span> $</span>
                        </div>
                        <div class="add_bottom_30">Lorem ipsum dolor sit amet, sed vide <strong>moderatius</strong> ad.
                            Ex eius soleat sanctus pro, enim conceptam in quo, <a href="#0">brute convenire</a>
                            appellantur an mei.
                        </div>
                        <a href="/home/cart2" class="btn_1 full-width">الدفع</a>
                        <a href="/home/courses_grid_sidebar" class="btn_1 full-width outline"><i class="icon-right"></i>
                           متابعة السوق</a>
                    </div>
                </aside>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /bg_color_1 -->
</main>
<!--/main-->

<script>
    function deleteFromCart(id, price) {
        var name = 'cartElements[' + id + ']';
        document.cookie = name + '=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/';
        $('#cartElement' + id).remove();
        $('#total_price').text(parseInt($('#total_price').text()) - parseInt(price));
        $('#n_cart_items').text(parseInt($('#n_cart_items').text()) - 1);
        // document.cookie = name + '=; Max-Age=-99999999;';
    }


</script>
<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>


