<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>
<!-- /main_menu -->

<main>
    <section id="hero_in" class="cart_section">
        <div class="wrapper">
            <div class="container">
                <div class="bs-wizard clearfix">

                    <div class="bs-wizard-step active">
                        <div class="text-center bs-wizard-stepnum">الانتهاء</div>

                        <a href="#0" class="bs-wizard-dot"></a>
                    </div>
                    <div class="bs-wizard-step">
                        <div class="text-center bs-wizard-stepnum">الدفع</div>
                        <div class="progress">
                            <div class="progress-bar"></div>
                        </div>
                        <a href="/home/cart2" class="bs-wizard-dot"></a>
                    </div>
                    <div class="bs-wizard-step">
                        <div class="text-center bs-wizard-stepnum">سلتك</div>

                        <a href="/home/cart1" class="bs-wizard-dot"></a>
                    </div>
                </div>
                <!-- End bs-wizard -->
                <div id="confirm">
                <h4>الطلب جاهز!</h4>
                    <p>سوف يصلك تأكيد الاستلام عبر الايميل التالي  mail@example.com</p>
                </div>
            </div>
        </div>
    </section>
    <!--/hero_in-->
</main>
<!--/main-->
<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>



