<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>
<!-- /main_menu -->

<main>
    <section id="hero_in" class="cart_section">
        <div class="wrapper">
            <div class="container">
                <div class="bs-wizard clearfix">




                    <div class="bs-wizard-step disabled">
                        <div class="text-center bs-wizard-stepnum">الانتهاء</div>

                        <a href="#0" class="bs-wizard-dot"></a>
                    </div>
                    <div class="bs-wizard-step active">
                        <div class="text-center bs-wizard-stepnum">الدفع</div>
                        <div class="progress">
                            <div class="progress-bar"></div>
                        </div>
                        <a href="#0" class="bs-wizard-dot"></a>
                    </div>
                    <div class="bs-wizard-step">
                        <div class="text-center bs-wizard-stepnum">سلتك</div>

                        <a href="/home/cart1" class="bs-wizard-dot"></a>
                    </div>
                </div>
                <!-- End bs-wizard -->
            </div>
        </div>
    </section>
    <!--/hero_in-->

    <div class="bg_color_1">
        <div class="container margin_61_35">
            <div class="row">

                <!-- /col -->
                <div class="col-lg-8">
                    <div class="box_cart">
                        <div class="message">
                            <p>المستخدم؟ <a href="#0">اضغط هنا لتسجيل الدخول</a></p>
                        </div>
                        <div class="form_title">
                            <h3><strong>1</strong>تفاصيل المستخدم</h3>

                        </div>
                        <div class="step">
                            <div class="row">
                                <div class="col-sm-6">
									<span class="input">
										<input class="input_field" type="text">
										<label class="input_label">
											<span class="input__label-content">الاسم الاول</span>
										</label>
									</span>
                                </div>
                                <div class="col-sm-6">
									<span class="input">
										<input class="input_field" type="text">
										<label class="input_label">
											<span class="input__label-content">الاسم الاخير</span>
										</label>
									</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
									<span class="input">
										<input class="input_field" type="email">
										<label class="input_label">
											<span class="input__label-content">الاميل</span>
										</label>
									</span>
                                </div>
                                <div class="col-sm-6">
									<span class="input">
										<input class="input_field" type="email">
										<label class="input_label">
											<span class="input__label-content">تأكيد الايميل</span>
										</label>
									</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
									<span class="input">
										<input class="input_field" type="text">
										<label class="input_label">
											<span class="input__label-content">الهاتف</span>
										</label>
									</span>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <!--End step -->

                        <div class="form_title">
                            <h3><strong>2</strong>بيانات الدفع</h3>

                        </div>
                        <div class="step">
							<span class="input">
								<input class="input_field" type="text">
								<label class="input_label">
								  <span class="input__label-content">اسم البطاقة</span>
								</label>
							</span>
                            <div class="row">
                                <div class="col-md-6">
									<span class="input">
										<input class="input_field" type="text">
										<label class="input_label">
										  <span class="input__label-content">رقم البطاقة</span>
										</label>
									</span>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <img src="/img/payments.png" alt="Cards" class="cards">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 add_top_30">
                                    <label>تاريخ الانتهاء</label>
                                    <div class="row">
                                        <div class="col-md-6">
											<span class="input">
												<input class="input_field" type="text">
												<label class="input_label">
												  <span class="input__label-content">شهر</span>
												</label>
											</span>
                                        </div>
                                        <div class="col-md-6">
											<span class="input">
												<input class="input_field" type="text">
												<label class="input_label">
												  <span class="input__label-content">سنه</span>
												</label>
											</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 add_top_30">
                                    <div class="form-group">
                                        <label>رمز الامان الخاص بالبطاقة</label>
                                        <div class="row">
                                            <div class="col-md-4">
												<span class="input">
													<input class="input_field" type="text">
													<label class="input_label">
													  <span class="input__label-content"></span>
													</label>
												</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                            <!--End row -->


                        <hr>
                        <!--End step -->

                        <div class="form_title">
                            <h3><strong>3</strong>عنوان الحساب</h3>

                        </div>
                        <div class="step">
                            <div class="row">
                                <div class="col-md-6 col-sm-6">
									<span class="input">
										<input class="input_field" type="text">
										<label class="input_label">
											<span class="input__label-content">المدينة</span>
										</label>
									</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-6">
									<span class="input">
										<input class="input_field" type="text">
										<label class="input_label">
											<span class="input__label-content">اسم الشارع الاول</span>
										</label>
									</span>
                                </div>
                                <div class="col-md-6 col-sm-6">
									<span class="input">
										<input class="input_field" type="text">
										<label class="input_label">
											<span class="input__label-content">اسم الشارع الثاني</span>
										</label>
									</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
									<span class="input">
										<input class="input_field" type="text">
										<label class="input_label">
											<span class="input__label-content">المدينة</span>
										</label>
									</span>
                                </div>
                                <div class="col-md-3">
									<span class="input">
										<input class="input_field" type="text">
										<label class="input_label">
											<span class="input__label-content">الحالة</span>
										</label>
									</span>
                                </div>
                                <div class="col-md-3">
									<span class="input">
										<input class="input_field" type="text">
										<label class="input_label">
											<span class="input__label-content">كود البوست </span>
										</label>
									</span>
                                </div>
                            </div>
                            <!--End row -->
                        </div>
                        <hr>
                        <!--End step -->

                    </div>
                </div>
                <aside class="col-lg-4" id="sidebar">
                    <div class="box_detail">
                        <div id="total_cart">
                            المجموع <span class="float-right">69.00$</span>
                        </div>
                        <div class="add_bottom_30">Lorem ipsum dolor sit amet, sed vide <strong>moderatius</strong> ad. Ex eius soleat sanctus pro, enim conceptam in quo, <a href="#0">brute convenire</a> appellantur an mei.</div>
                        <a href="/home/cart3" class="btn_1 full-width">الدفع</a>
                        <a href="/home/courses_grid_sidebar" class="btn_1 full-width outline"><i class="icon-right"></i>متابعة التسوق</a>
                    </div>
                </aside>
            </div>

            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /bg_color_1 -->
</main>
<!--/main-->
<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>



