
<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>
<div class="container-contact100">
    <div class="wrap-contact100">
<!--        <button class="btn-hide-contact100">-->
<!--            <i class="zmdi zmdi-close"></i>-->
<!--        </button>-->

        <div class="contact100-form-title" style="background-image: url(/images/contact-us.jpg);">
            <span>Contact Us</span>
        </div>

        <form class="contact100-form validate-form">
            <div class="wrap-input100 validate-input">
                <input id="name" class="input100" type="text" name="name" placeholder="Full name">
                <span class="focus-input100"></span>
                <label class="label-input100" for="name">
                    <span class="icon-user m-b-2"></span>
                </label>
            </div>


            <div class="wrap-input100 validate-input">
                <input id="email" class="input100" type="text" name="email" placeholder="Eg. example@email.com">
                <span class="focus-input100"></span>
                <label class="label-input100" for="email">
                    <span class="icon-mail  m-b-5"></span>
                </label>
            </div>


            <div class="wrap-input100 validate-input">
                <input id="phone" class="input100" type="text" name="phone" placeholder="Eg. +976 800 000000">
                <span class="focus-input100"></span>
                <label class="label-input100" for="phone">
                    <span class="icon-phone m-b-2"></span>
                </label>
            </div>


            <div class="wrap-input100 validate-input">
                <textarea id="message" class="input100" name="message" placeholder="Your comments..."></textarea>
                <span class="focus-input100"></span>
                <label class="label-input100 rs1" for="message">
                    <span class="icon-chat"></span>
                </label>
            </div>

            <div class="container-contact100-form-btn">
                <button class="contact100-form-btn">
                    Send Now
                </button>
            </div>
        </form>
    </div>
</div>
<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>

