<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>

    <body>
<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
<main>
<!--    <section id="hero_in" class="courses">-->
<!--        <div class="wrapper">-->
<!--            <div class="container">-->
<!--               <img src="/img/1.jpg">-->
<!--                <h1 class="fadeInUp"><span></span>Online courses</h1>-->
<!--            </div>-->
<!--        </div>-->
<!--    </section>-->
    <!--/hero_in-->
    <div class="filters_listing">
        <div class="container head-courses">
            <ul class="clearfix">
                <li>
                    <div class="switch-field">
                        <input type="radio" id="all" name="listing_filter" value="all" checked>
                        <label for="all">All</label>
                        <input type="radio" id="popular" name="listing_filter" value="popular">
                        <label for="popular">Popular</label>
                        <input type="radio" id="latest" name="listing_filter" value="latest">
                        <label for="latest">Latest</label>
                    </div>
                </li>
                <li>
                    <div class="layout_view">
                        <a href="#0" class="active"><i class="icon-th"></i></a>
                        <a href="/home/courses_list"><i class="icon-th-list"></i></a>
                    </div>
                </li>
<!--                <li>-->
<!--                    <select name="orderby" class="selectbox">-->
<!--                        <option value="category">Category</option>-->
<!--                        <option value="category 2">Literature</option>-->
<!--                        <option value="category 3">Architecture</option>-->
<!--                        <option value="category 4">Economy</option>-->
<!--                    </select>-->
<!--                </li>-->
            </ul>
        </div>
        <!-- /container -->
    </div>
    <!-- /filters -->

    <div class="container margin_61_35">
        <div class="row">
            <div class="col-xl-4 col-lg-6 col-md-6">
                <div class="box_grid wow">
                    <figure class="block-reveal">
                        <div class="block-horizzontal"></div>
                        <a href="#0" class="wish_bt"></a>
                        <a href="home/course_detail"><img src="/img/1.jpg" class="img-fluid" alt=""></a>
                        <div class="price">$54</div>
                        <div class="preview"><span>Preview course</span></div>
                    </figure>
                    <div class="wrapper">
                        <small>Category</small>
                        <h3>Persius delenit has cu</h3>
                        <p>Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.</p>
                        <div class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i> <small>(145)</small></div>
                    </div>
                    <ul>
                        <li><i class="icon_clock_alt"></i> 1h 30min</li>
                        <li><i class="icon_like"></i> 890</li>
                        <li><a href="/home/course_detail">Enroll now</a></li>
                    </ul>
                </div>
            </div>
            <!-- /box_grid -->
            <div class="col-xl-4 col-lg-6 col-md-6">
                <div class="box_grid wow">
                    <figure class="block-reveal">
                        <div class="block-horizzontal"></div>
                        <a href="#0" class="wish_bt"></a>
                        <a href="course_detail"><img src="http://via.placeholder.com/800x533/ccc/fff/course__list_2.jpg" class="img-fluid" alt=""></a>
                        <div class="price">$45</div>
                        <div class="preview"><span>Preview course</span></div>
                    </figure>
                    <div class="wrapper">
                        <small>Category</small>
                        <h3>At deseruisse scriptorem</h3>
                        <p>Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.</p>
                        <div class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i> <small>(145)</small></div>
                    </div>
                    <ul>
                        <li><i class="icon_clock_alt"></i> 1h 30min</li>
                        <li><i class="icon_like"></i> 890</li>
                        <li><a href="/home/course_detail">Enroll now</a></li>
                    </ul>
                </div>
            </div>
            <!-- /box_grid -->
            <div class="col-xl-4 col-lg-6 col-md-6">
                <div class="box_grid wow">
                    <figure class="block-reveal">
                        <div class="block-horizzontal"></div>
                        <a href="#0" class="wish_bt"></a>
                        <a href="/home/course_detail"><img src="http://via.placeholder.com/800x533/ccc/fff/course__list_3.jpg" class="img-fluid" alt=""></a>
                        <div class="price">$39</div>
                        <div class="preview"><span>Preview course</span></div>
                    </figure>
                    <div class="wrapper">
                        <small>Category</small>
                        <h3>Ea vel semper quaerendum</h3>
                        <p>Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.</p>
                        <div class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i> <small>(145)</small></div>
                    </div>
                    <ul>
                        <li><i class="icon_clock_alt"></i> 1h 30min</li>
                        <li><i class="icon_like"></i> 890</li>
                        <li><a href="/home/course_detail">Enroll now</a></li>
                    </ul>
                </div>
            </div>
            <!-- /box_grid -->
            <div class="col-xl-4 col-lg-6 col-md-6">
                <div class="box_grid wow">
                    <figure class="block-reveal">
                        <div class="block-horizzontal"></div>
                        <a href="#0" class="wish_bt"></a>
                        <a href="/home/course_detail"><img src="http://via.placeholder.com/800x533/ccc/fff/course__list_4.jpg" class="img-fluid" alt=""></a>
                        <div class="price">$60</div>
                        <div class="preview"><span>Preview course</span></div>
                    </figure>
                    <div class="wrapper">
                        <small>Category</small>
                        <h3>Ei has exerci graecis</h3>
                        <p>Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.</p>
                        <div class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i> <small>(145)</small></div>
                    </div>
                    <ul>
                        <li><i class="icon_clock_alt"></i> 1h 30min</li>
                        <li><i class="icon_like"></i> 890</li>
                        <li><a href="/home/course_detail">Enroll now</a></li>
                    </ul>
                </div>
            </div>
            <!-- /box_grid -->
            <div class="col-xl-4 col-lg-6 col-md-6">
                <div class="box_grid wow">
                    <figure class="block-reveal">
                        <div class="block-horizzontal"></div>
                        <a href="#0" class="wish_bt"></a>
                        <a href="/home/course_detail"><img src="http://via.placeholder.com/800x533/ccc/fff/course__list_5.jpg" class="img-fluid" alt=""></a>
                        <div class="price">$45</div>
                        <div class="preview"><span>Preview course</span></div>
                    </figure>
                    <div class="wrapper">
                        <small>Category</small>
                        <h3>Decore tractatos</h3>
                        <p>Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.</p>
                        <div class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i> <small>(145)</small></div>
                    </div>
                    <ul>
                        <li><i class="icon_clock_alt"></i> 1h 30min</li>
                        <li><i class="icon_like"></i> 890</li>
                        <li><a href="/home/course_detail">Enroll now</a></li>
                    </ul>
                </div>
            </div>
            <!-- /box_grid -->
            <div class="col-xl-4 col-lg-6 col-md-6">
                <div class="box_grid wow">
                    <figure class="block-reveal">
                        <div class="block-horizzontal"></div>
                        <a href="#0" class="wish_bt"></a>
                        <a href="/home/course_detail"><img src="http://via.placeholder.com/800x533/ccc/fff/course__list_6.jpg" class="img-fluid" alt=""></a>
                        <div class="price">$39</div>
                        <div class="preview"><span>Preview course</span></div>
                    </figure>
                    <div class="wrapper">
                        <small>Category</small>
                        <h3>Eam id legimus torquatos</h3>
                        <p>Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.</p>
                        <div class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i> <small>(145)</small></div>
                    </div>
                    <ul>
                        <li><i class="icon_clock_alt"></i> 1h 30min</li>
                        <li><i class="icon_like"></i> 890</li>
                        <li><a href="/home/course_detail">Enroll now</a></li>
                    </ul>
                </div>
                <!-- /box_grid -->
            </div>
        </div>
        <!-- /row -->
        <p class="text-center"><a href="#0" class="btn_1 rounded add_top_30">Load more</a></p>
    </div>
    <!-- /container -->

    <!-- /bg_color_1 -->
</main>
<!--/main-->



</body>
</html>
<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
