<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>كورسات</title>

    <!-- Bootstrap 4.0-->
    <link rel="stylesheet" href="/design/site/css/bootstrap.css">
    <link rel="stylesheet" href="/design/site/css/bootstrap-rtl.min.css">
    <link rel="stylesheet" href="/design/site/fonts/font-awesome-4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="/design/site/css/custom.css">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="nav">
    <div class="container-fluid">
        <div class="row">
            <div class="col-4">
                <div class="hamburger">
                    <i class="fa fa-bars"></i>
                </div>
            </div>
            <div class="col-4">
                <div class="user-icon"></div>
            </div>
            <div class="col-4">
                <div class="user-icons">
                    <ul class="user-icons-list">
                        <?php if (!isset($_SESSION['user'])) { ?>
                            <li class="icon-login"><i class="fa fa-user"></i>
                                <form method="POST" class="my-login-validation login-form" action="/home/postLogin"
                                      id='first_form'>
                                    <div class="login-heading">تسجيل الدخول</div>
                                    <div class="input-group user-email">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fa fa-user"></i></span>
                                        </div>
                                        <input type="text" value="<?php Helper::old('username'); ?>" id="user_email" name="username" class="form-control"
                                               placeholder="ادخل بريدك الالكتروني او اسم المستخدم">
                                    </div>

                                    <div class="input-group user-password">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fa fa-key"></i></span>
                                        </div>
                                        <input type="password" class="form-control" placeholder="ادخل كلمة المرور"
                                               id="password" name="password">
                                    </div>
                                    <button id="login-btn">تسجيل الدخول</button>
                                    <div class="create-new">
                                        لايوجد لديك حساب ؟ يمكنك التسجيل
                                        <a href="/home/register/student"> كطالب</a>
                                        <a href="/home/register/university"> او كجامعة</a>
                                    </div>
                                </form>
                            </li>
                        <?php } elseif (isset($_SESSION['user'])) { ?>
                            <li><i class="fa fa-heart"></i><span><?php echo Helper::wishListCount() ?></span></li>
                            <li class="shopping-cart">
                                <i class="fa fa-shopping-cart"></i><span id="n_cart_items"><?php echo isset($_COOKIE['cartElements']) ? count($_COOKIE['cartElements']) : 0 ?></span>
                            </li>
                            <li><i class="fa fa-bell"></i><span>0</span></li>
                            <li>
                                <div class="user-name">
                                    <i class="fa fa-user"></i>
                                    <span> طاهر السماوي</span>
                                    <div class="user-settings">
                                        <ul>
                                            <li><a href="/profile"><i class="fa fa-user"></i> عرض الملف الشخصي</a></li>
                                            <li><a href="/admin/logout"><i class="fa fa-sign-out"></i> تسجيل الخروج</a>
                                            </li>
                                        </ul>

                                    </div>
                                </div>
                            </li>
                        <?php } ?>
                    </ul>


                </div>
            </div>

        </div>
    </div>


</div>

<?php //include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>


<!-- Start Content  -->
<div class="content">
    <div class="container-fluid">
        <div class="row ">
            <!-- Start Sidebar-->
            <div class="col-2 sidebar">
                <div class="logo-site">
                    <img src="/images/logo-color.png">
                </div>
                <div class="logo-site-small">
                    <img src="/images/logo-icon.png">
                </div>
                <ul>
                    <li><a href="#" class="active">
                            <span class="icon"><i class="fa fa-home"></i></span>
                            <span class="title">الصفحة الرئيسية</span>
                        </a>
                    </li>

                    <li><a href="#">
                            <span class="icon"><i class="fa fa-star"></i></span>
                            <span class="title">المفضلة</span>
                        </a></li>

                    <li><a href="#">
                            <span class="icon"><i class="fa fa-line-chart"></i></span>
                            <span class="title">مستوى التقدم</span>

                        </a></li>

                    <li><a href="#">
                            <span class="icon"><i class="fa fa-cog"></i></span>
                            <span class="title">الأعدادات</span>
                        </a>
                    </li>


                    <li><a href="#">
                            <span class="icon"><i class="fa fa-book"></i></span>
                            <span class="title">الصفحة الرئيسية</span>
                        </a></li>
                    <li><a href="#">
                            <span class="icon"><i class="fa fa-book"></i></span>
                            <span class="title">الصفحة الرئيسية</span>
                        </a></li>
                    <li><a href="#">
                            <span class="icon"><i class="fa fa-book"></i></span>
                            <span class="title">من نحن </span>
                        </a></li>
                </ul>

            </div>
            <!-- End Sidebar-->
            <?php include VIEW . 'messages.phtml'; ?>
            <!-- Start main-content-->
            <div class="col-6">
                <div class="video-section">
                    <div class="row row-cols-1">
                        <div class="col">
                            <div class="view-video">
                                <video controls>
                                    <source src="/videos/1580903859______What Is Version Control- - YouTube.webm" type="video/webm">
                                </video>
                            </div>

                            <div class="video-details">
                                <div class="course-details">
                                    <?php $course = $this->view_data['course'][0]; ?>
                                    <h6 class="video-name">  <?php echo $course['course_title']?></h6>
                                    <span class="teacher-name"> مختار غالب</span> |
                                    <span class="university-name"> اكاديمية البرمجة</span>
                                </div>
                            </div>

                            <div class="course-details">
                                <ul class="tabs-list">
                                    <li class="active" data-content=".course-description">محتويات الكورس</li>
                                    <li data-content=".rating-comments">التقييمات والمراجعة</li>
                                    <li data-content=".course-resource">الملفات المرفقة</li>
                                </ul>
                                <div class="course-description">
                                    <?php echo html_entity_decode($course['course_description']) ?>
                                </div>

                                <div class="rating-comments">

                                    <div class="row mt-5">
                                        <div class="col-4">
                                            <div class="rating-course">
                                                <span class="average-rating">
                                                     <?php
                                                     $numberStarts=isset($this->view_data['averageRating'][0]['average_rating'])?$this->view_data['averageRating'][0]['average_rating']:0;
                                                     echo isset($numberStarts)? $numberStarts:"0";
                                                     ?>
                                                </span>

                                                <span class="number-stars">
                                                    <?php Helper::getNumberStars($numberStarts); ?>
                                                </span>


                                                <span class="count-rating">
                                                     من اجمالي
                                            <?php  echo isset($this->view_data['averageRating'][0]['total_rating'])? $this->view_data['averageRating'][0]['total_rating']:"0";   ?>
                                            تقييم
                                        </span>
                                            </div>
                                        </div>
                                        <div class="col-8">
                                            <?php
                                            for($i= 5 ;$i>0;$i--)  {
                                                $percentageRating=isset($this->view_data['percentageRating'][$i])?$this->view_data['percentageRating'][$i]:0;
                                                ?>
                                                <div class="progress-rating row">
                                                    <div class="col-8">
                                                        <div class="progress">
                                                            <div class="progress-bar" role="progressbar"
                                                                 style="width:<?php echo isset($percentageRating)? $percentageRating:"0"; ?>%">
                                                                <?php echo isset($percentageRating)? $percentageRating."%":"0"   ; ?>
                                                            </div>
                                                        </div>

                                                    </div>
                                                    <div class="col-4">
                                                        <?php Helper::getNumberStars($i); ?>
                                                    </div>

                                                </div>
                                            <?php }
                                            ?>
                                        </div>
                                    </div>

                                    <hr class="my-5">

                                    <div class="list_rating">
                                        <?php
                                        foreach ($this->view_data['AllRatings'] as $rating) { ?>
                                            <div class="row">
                                                <div class="col-2">
                                                    <div class="user-img">
                                                        <img src="<?php echo $rating['user_image']; ?> " alt="">
                                                    </div>
                                                </div>

                                                <div class="col-10">
                                                    <div class="rating-info">
                                                        <div class="user-info">
                                                            <span class="user-name" ><?php echo $rating['user_full_name']; ?></span>
                                                            <span class="user-rating"  ><?php Helper::getNumberStars($rating['rating_number']);?></span>
                                                        </div>
                                                        <div class="rating-date">
                                                            <?php echo  $rating['rating_date']; ?>
                                                        </div>
                                                        <div class="comment">
                                                            <?php echo $rating['comment_text']; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php }?>
                                    </div>

                                    <?php if (isset($_SESSION['user'])) {// if user log in .. show input form

                                    // if user has not rating .. show input form
                                    $ID_UserHasRated = isset($this->view_data['checkIfUserHasRated'][0]['user_id']);
                                    if(!($ID_UserHasRated == Session::get('userID')) ){
                                    ?>
                                    <div class="rating-input-container">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <div class="user-img">
                                                    <img src="<?php echo Session::get('user')['user_image']; ?> " alt="">
                                                </div>
                                            </div>

                                            <div class="col-md-10">
                                                <div class="user-rating">
                                                    <div class="user-info">
                                                        <?php echo Session::get('user')['user_full_name']; ?>
                                                    </div>
                                                    <div class="rate">
                                                        <ul>
                                                            <i data-number-rating="1" class="btn-1 rate-btn fa fa-star"></i>
                                                            <i data-number-rating="2" class="btn-2 rate-btn fa fa-star"></i>
                                                            <i data-number-rating="3" class="btn-3 rate-btn fa fa-star"></i>
                                                            <i data-number-rating="4" class="btn-4 rate-btn fa fa-star "></i>
                                                            <i data-number-rating="5" class="btn-5 rate-btn fa fa-star "></i>
                                                        </ul>
                                                    </div>

                                                    <div class="input-group mb-3">
                                                        <textarea type="text" placeholder="اضف تقييمك حول الكورس(اختياري)"
                                                               class="form-control comment_input" name="comment_text"
                                                               rows="4"
                                                               data-course="<?php echo $course['course_id']; ?>"
                                                               data-rating-number="5>"
                                                               data-image-user="<?php echo(Session::get('user')['user_image']) ?>"
                                                               data-user-name="<?php echo(Session::get('user')['user_full_name']) ?>"
                                                               data-rating-date="<?php echo date("Y-m-d h:i:sa") ?>" data-user-ID="<?php echo(Session::get('userID')) ?>">
                                                        </textarea>
                                                    </div>

                                                    <button  id="add_rating"
                                                            name="add_rating">
                                                        <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
                                                        اضافة تقييم
                                                    </button>




                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php }}?>

                                </div>







                                <div class="course-resource">
                                    <i class="fa fa-file"></i>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
            <!-- End main-content-->


            <div class="col-4">
                <div class="course-chapters">
                    <div class="course-name">
                        <h6><?php echo $course['course_title']?></h6>
                    </div>
                    <div class="chapter-head">
                        <span>تفاصيل الدورة</span>
                        <span><i class="fa fa-play-circle-o"></i><?php echo $this->view_data['course_count'] ?> -
                     <i class="fa fa-clock-o"></i> <?php echo $this->view_data['course_duration'] ?></span>
                    </div>
                    <hr>

                    <ul class="list-chapters">
                        <?php $num=1;
                        foreach ($this->view_data['lessons'] as $k => $chapter) { ?>

                        <li class="chapter-detail">
                            <span class="num"><?php echo $num?></span>
                                <span class="chapter_name"><?php echo $k ?></span>
                                <span class="chapter_number_lessons"><i class="fa fa-play-circle-o"></i> <?php echo count($chapter['lessons']) ?> </span>
                                <span class="chapter_duration"><?php echo $chapter['duration'] ?> </span>
                            <span class="show-video"><i class="fa fa-plus"></i></span>
                        </li>
                        <ul class="list-lessons">
                            <?php foreach ($chapter['lessons'] as $lesson) {
                                $file = Helper::getVideoDeatils(substr($lesson['resources_video'], 1)); ?>
                                <li>
                                <span class="video-name"><i class="fa fa-play-circle-o"></i>
                                    <a href="#" data-video="<?php echo Helper::SITE_URL(). $lesson['resources_video'] ?>"
                                    ><?php echo Helper::getVideoName($lesson['resources_video']) ?>
                                </a></span>

                                    <span class="video-duration"> <?php echo gmdate("H:i:s", $file['playtime_seconds']) ?></span>
                                </li>

                            <?php } ?>


                        </ul>
                        <?php $num++; }?>


                    </ul>
                </div>

            </div>


        </div>
    </div>
</div>
<!-- End Content  -->


<!-- jQuery 3 -->
<script src="/design/site/js/jquery-3.3.1.min.js"></script>
<!-- popper -->
<script src="/design/site/js/popper.min.js"></script>
<!-- Bootstrap 4.0-->
<script src="/design/site/js/bootstrap.js"></script>

<script src="/design/site/js/main.js"></script>

<?php //include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'ratings.phtml' ?>

<script>
    addRating();
    deleteRating();
</script>


</body>

</html>
