<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>
<style type="text/css">
    div.guide {
        margin: 12px 24px;
    }

    div.guide span {
        color: #ff0000;
        font: italic 14px Arial, Helvetica, sans-serif;
    }

    div.guide p {
        color: #000000;
        font: 14px Arial, Helvetica, sans-serif;
    }

    div.guide pre {
        color: #990000;
    }

    div.guide p.title {
        color: #df501f;
        font: 18px Arial, Helvetica, sans-serif;
    }
</style>

<main>
    <!--		<section id="hero_in" class="courses">-->
    <!--			<div class="wrapper">-->
    <!--				<div class="container">-->
    <!--					<h1 class="fadeInUp"><span></span>Online course detail</h1>-->
    <!--				</div>-->
    <!--			</div>-->
    <!--		</section>-->
    <!--/hero_in-->
    <?php $course = $this->view_data['course'][0]; ?>
    <div class="bg_color_1">
        <nav class="secondary_nav">
            <div class="container">
                <ul class="clearfix">
                    <li><a href="#description" class="active">Description</a></li>
                    <li><a href="#lessons">Lessons</a></li>
                    <li><a href="#reviews">Reviews</a></li>
                </ul>
            </div>
        </nav>
        <div class="container margin_61_35">
            <div class="row">
                <div class="col-lg-8">

                    <section id="description">
                        <?php echo $course['course_description'] ?>
                    </section>
                    <!-- /section -->
                    <!--						--><?php //print_r($this->view_data['lessons'])?>
                    <section id="lessons">
                        <div class="intro_title">
                            <h2>Lessons</h2>
                            <ul>
                                <li><?php echo $this->view_data['course_count'] ?> lessons</li>

                                <li>  <?php echo $this->view_data['course_duration'] ?> </li>
                            </ul>
                        </div>
                        <div id="accordion_lessons" role="tablist" class="add_bottom_45">

                            <?php foreach ($this->view_data['lessons'] as $k => $chapter) { ?>

                                <div class="card">
<!--                                    <div class="card-header" role="tab" id="headingOne">-->
<!--                                        <h5 class="mb-0">-->
<!--                                            <a data-toggle="collapse"-->
<!--                                               href="#--><?php //echo $k ?><!--" aria-expanded="true"-->
<!--                                               aria-controls="collapseOne"><i class="indicator ti-plus"></i>-->
<!--                                                --><?php //echo $k ?><!--     </a>-->
<!---->
<!--                                        </h5>-->
<!--                                    </div>-->
                                    <div class="intro_title card-header" role="tab" id="headingOne">
                                        <a data-toggle="collapse"
                                               href="#<?php echo $k ?>" aria-expanded="true"
                                               aria-controls="collapseOne"><i class="indicator ti-plus"></i>
                                                <?php echo $k ?>     </a>

                                        <ul>
                                            <li><?php echo count($chapter['lessons']) ?> lessons</li>

                                            <li>  <?php echo $chapter['duration'] ?> </li>
                                        </ul>
                                    </div>

                                    <div id="<?php echo $k ?>" class="collapse "
                                         role="tabpanel"
                                         aria-labelledby="headingOne"
                                         data-parent="#accordion_lessons">
                                        <div class="card-body">
                                            <div class="list_lessons">
                                                <ul>
                                                    <?php foreach ($chapter['lessons'] as $lesson) {
                                                        $file = Helper::getVideoDeatils(substr($lesson['resources_video'], 1)); ?>
                                                        <li>
                                                            <a class="video">
                                                                <div style="display:none;margin:0 auto;"
                                                                     class="html5gallery" data-html5player="true"
                                                                     data-width="340" data-height="172"
                                                                     data-resizemode="fill" data-showsocialmedia="false"
                                                                     data-src="<?php echo $lesson['resources_video'] ?>"
                                                                     data-webm="<?php echo $lesson['resources_video'] ?>"></div>
                                                                <?php echo Helper::getVideoName($lesson['resources_video']) ?>
                                                            </a>
                                                            <span><?php echo gmdate("H:i:s", $file['playtime_seconds']) ?></span>
                                                        </li>
                                                    <?php } ?>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>

                            <!--    <div class="card">
                                    <div class="card-header" role="tab" id="headingTwo">
                                        <h5 class="mb-0">
                                            <a class="collapsed" data-toggle="collapse" href="#collapseTwo"
                                               aria-expanded="false" aria-controls="collapseTwo">
                                                <i class="indicator ti-plus"></i>Generative Modeling Review
                                            </a>
                                        </h5>
                                    </div>
                                    <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo"
                                         data-parent="#accordion_lessons">
                                        <div class="card-body">
                                            <div class="list_lessons">
                                                <ul>
                                                    <li><a href="https://www.youtube.com/watch?v=LDgd_gUcqCw" class="video">Health
                                                            Science</a><span>00:59</span></li>
                                                    <li><a href="https://www.youtube.com/watch?v=LDgd_gUcqCw" class="video">Health
                                                            and Social Care</a><span>00:59</span></li>
                                                    <li><a href="https://www.youtube.com/watch?v=LDgd_gUcqCw" class="video">History</a><span>00:59</span>
                                                    </li>
                                                    <li><a href="https://www.youtube.com/watch?v=LDgd_gUcqCw" class="video">Healthcare
                                                            Science</a><span>00:59</span></li>
                                                    <li><a href="#0" class="txt_doc">Audiology</a><span>00:59</span></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                             -->


                        </div>
                        <!-- /accordion -->
                    </section>
                    <!-- /section -->

                    <section id="reviews">
                        <h2>Reviews</h2>
                        <div class="reviews-container">
                            <div class="row">
                                <div class="col-lg-3">
                                    <div id="review_summary">
                                        <strong>4.7</strong>
                                        <div class="rating">
                                            <i class="icon_star voted"></i><i class="icon_star voted"></i><i
                                                    class="icon_star voted"></i><i class="icon_star voted"></i><i
                                                    class="icon_star"></i>
                                        </div>
                                        <small>Based on 4 reviews</small>
                                    </div>
                                </div>
                                <div class="col-lg-9">
                                    <div class="row">
                                        <div class="col-lg-10 col-9">
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" style="width: 90%"
                                                     aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                        <div class="col-lg-2 col-3"><small><strong>5 stars</strong></small></div>
                                    </div>
                                    <!-- /row -->
                                    <div class="row">
                                        <div class="col-lg-10 col-9">
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" style="width: 95%"
                                                     aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                        <div class="col-lg-2 col-3"><small><strong>4 stars</strong></small></div>
                                    </div>
                                    <!-- /row -->
                                    <div class="row">
                                        <div class="col-lg-10 col-9">
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" style="width: 60%"
                                                     aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                        <div class="col-lg-2 col-3"><small><strong>3 stars</strong></small></div>
                                    </div>
                                    <!-- /row -->
                                    <div class="row">
                                        <div class="col-lg-10 col-9">
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" style="width: 20%"
                                                     aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                        <div class="col-lg-2 col-3"><small><strong>2 stars</strong></small></div>
                                    </div>
                                    <!-- /row -->
                                    <div class="row">
                                        <div class="col-lg-10 col-9">
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" style="width: 0"
                                                     aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                        <div class="col-lg-2 col-3"><small><strong>1 stars</strong></small></div>
                                    </div>
                                    <!-- /row -->
                                </div>
                            </div>
                            <!-- /row -->
                        </div>

                        <hr>

                        <div class="reviews-container">

                            <div class="review-box clearfix">
                                <figure class="rev-thumb"><img
                                            src="http://via.placeholder.com/150x150/ccc/fff/avatar1.jpg" alt="">
                                </figure>
                                <div class="rev-content">
                                    <div class="rating">
                                        <i class="icon_star voted"></i><i class="icon_star voted"></i><i
                                                class="icon_star voted"></i><i class="icon_star voted"></i><i
                                                class="icon_star"></i>
                                    </div>
                                    <div class="rev-info">
                                        Admin – April 03, 2016:
                                    </div>
                                    <div class="rev-text">
                                        <p>
                                            Sed eget turpis a pede tempor malesuada. Vivamus quis mi at leo pulvinar
                                            hendrerit. Cum sociis natoque penatibus et magnis dis
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <!-- /review-box -->
                            <div class="review-box clearfix">
                                <figure class="rev-thumb"><img
                                            src="http://via.placeholder.com/150x150/ccc/fff/avatar2.jpg" alt="">
                                </figure>
                                <div class="rev-content">
                                    <div class="rating">
                                        <i class="icon-star voted"></i><i class="icon_star voted"></i><i
                                                class="icon_star voted"></i><i class="icon_star voted"></i><i
                                                class="icon_star"></i>
                                    </div>
                                    <div class="rev-info">
                                        Ahsan – April 01, 2016:
                                    </div>
                                    <div class="rev-text">
                                        <p>
                                            Sed eget turpis a pede tempor malesuada. Vivamus quis mi at leo pulvinar
                                            hendrerit. Cum sociis natoque penatibus et magnis dis
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <!-- /review-box -->
                            <div class="review-box clearfix">
                                <figure class="rev-thumb"><img
                                            src="http://via.placeholder.com/150x150/ccc/fff/avatar3.jpg" alt="">
                                </figure>
                                <div class="rev-content">
                                    <div class="rating">
                                        <i class="icon-star voted"></i><i class="icon_star voted"></i><i
                                                class="icon_star voted"></i><i class="icon_star voted"></i><i
                                                class="icon_star"></i>
                                    </div>
                                    <div class="rev-info">
                                        Sara – March 31, 2016:
                                    </div>
                                    <div class="rev-text">
                                        <p>
                                            Sed eget turpis a pede tempor malesuada. Vivamus quis mi at leo pulvinar
                                            hendrerit. Cum sociis natoque penatibus et magnis dis
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <!-- /review-box -->
                        </div>
                        <!-- /review-container -->
                    </section>
                    <!-- /section -->
                </div>
                <!-- /col -->

                <aside class="col-lg-4" id="sidebar">
                    <div class="box_detail">
                        <figure>
                            <a class="video"><i
                                        class="arrow_triangle-right"></i>
                                <img alt="" src="/images/site/<?php echo $course['courses_image'] ?>"
                                     class="img-fluid"><span>View course preview</span></a>
                        </figure>

                        <div class="price">
                            $ <?php echo $course['course_price'] ?> <span
                                    class="original_price"><em>$<?php echo $course['course_price'] ?></em>60% <?php echo $course['course_price'] ?></span>
                        </div>
                        <a href="/home/cart1" class="btn_1 full-width">Purchase</a>
                        <a href="#0" class="btn_1 full-width outline"><i class="icon_heart"></i> Add to wishlist</a>
                        <div id="list_feat">
                            <h3>What's includes</h3>
                            <ul>
                                <li><i class="icon_mobile"></i>Mobile support</li>
                                <li><i class="icon_archive_alt"></i>Lesson archive</li>
                                <li><i class="icon_mobile"></i>Mobile support</li>
                                <li><i class="icon_chat_alt"></i>Tutor chat</li>
                                <li><i class="icon_document_alt"></i>Course certificate</li>
                            </ul>
                        </div>
                    </div>
                </aside>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /bg_color_1 -->
</main>
<!--/main-->
<script type=”text/javascript” src=”//cdn.jsdelivr.net/afterglow/latest/afterglow.min.js”></script>
<script type="text/javascript" src="/design/dashboard/lib/html5gallery/html5gallery.js"></script>
<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
