<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml'

?>

<body>


<button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
<main>


    <div class="filters_listing">

    </div>
    <!-- /filters -->
    <div class="row" style="margin-top: 20px">
        <div class="container">

            <div class="row">

                <div class=" card col-lg-12 col-md-12 col-ms-12" style="border-bottom: red">
                    <h2><?php echo Helper::getCategoryName($this->view_data['category_id']) ?> Courses</h2>

                </div>
                <div class="col-lg-12 col-md-12 col-ms-12">
                    <?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'coursesView.phtml' ?>
                </div>

            </div>


        </div>
    </div>

    <!-- /container -->

    <!-- /bg_color_1 -->
</main>
<!--/main-->

<script>

    function addToCart(id) {
        document.cookie = 'item_id[' + id + ']=' + id;
        alert(id);


    }

    function addToWhishLish(id) {
        document.cookie = 'item_whishlish_id[' + id + ']=' + id;
        alert(id);

    }


</script>

<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'active.phtml' ?>

<script>
    AddToWish('/courses');
    // AddToWish('courses');

</script>