<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>


<main>
    <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
    NextCopy

<?php if (array_key_exists('latestCourses', $this->view_data)) {
    ?>
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <?php      foreach ($this->view_data['latestCourses'] as $k=> $course) { ?>

            <li data-target="#carouselExampleCaptions" data-slide-to="<?php echo $course['course_id']?>"   <?php if ($k==0) echo ' class="active"'?> ></li>

            <?php     } ?>
        </ol>
        <div class="carousel-inner">
    <?php      foreach ($this->view_data['latestCourses'] as $k=> $course) { ?>
            <div class="carousel-item  <?php if ($k==0) echo'active' ?> ">
                <img src="/images/site/<?php echo $course['courses_image'] ?>" class="d-block w-100" alt="..." height="70%">
                <div class="carousel-caption d-none d-md-block">
                    <h5><?php echo $course['course_title'] ?></h5>
                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                </div>
            </div>
    <?php     } ?>

        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <?php     } ?>
   <div class="row" style="margin-top: 20px">
       <div class="container">

           <?php include VIEW . 'messages.phtml' ?>


           <div class="row">

               <div class=" card col-lg-12 col-md-12 col-ms-12" style="border-bottom: red">
                   <h2>Popular Courses</h2>

               </div>
               <div class="col-lg-12 col-md-12 col-ms-12">

<?php if (array_key_exists('latestCourses', $this->view_data)) {
    ?>
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                           <div class="carousel-inner">
                               <div class="carousel-item active">
                                   <div class="row">
                                <?php      foreach ($this->view_data['latestCourses'] as $k=> $course) { ?>

<?php if($k<3){
   ?>
    <div class="col-md-4 col-sm-2 col-4">
                                           <div class="box_grid wow">
                                               <figure class="block-reveal">
                                                   <div class="block-horizzontal"></div>
                                                   <a href="#0" class="wish_bt"></a>
                                                   <a href="/home/course_detail/<?php echo $course['course_id']?>"><img src="/images/site/<?php echo $course['courses_image'];?>" class="img-fluid" alt=""></a>
                                                   <div class="price"><?php echo $course['course_price']?> $</div>
                                                   <div class="preview"><span>عرض الكورس  </span></div>
                                               </figure>
                                               <div class="wrapper">
                                                   <small>الصنف</small>
                                                   <h3> <?php echo Helper::Names($course['categories_ids'], 'Category') ?> </h3>
                                                   <p><?php echo $course['course_title']?></p>
                                                   <div class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i> <small>(145)</small></div>
                                               </div>
                                               <ul>
                                                   <li><i class="icon_clock_alt"></i> 1h 30min</li>
                                                   <li><i class="icon_like"></i> 890</li>
                                                   <li><a href="/home/course_detail/<?php echo $course['course_id']?>"> تسجيل الان</a></li>
                                               </ul>
                                           </div>
                                       </div>
                                       <?php }?>


                               <?php }?>
                                   </div>
                               </div>
                               <div class="carousel-item ">
                                   <div class="row">
   <?php      foreach ($this->view_data['latestCourses'] as $k=> $course) { ?>
       <?php
       if($k>2){
          
           ?>
           <div class="col-md-4 col-sm-6 col-12">
               <div class="box_grid wow">
                   <figure class="block-reveal">
                       <div class="block-horizzontal"></div>
                       <a href="#0" class="wish_bt"></a>
                       <a href="/home/course_detail"><img src="/images/site/<?php echo $course['courses_image']; ?>" class="img-fluid" alt=""></a>
                       <div class="price">$45</div>
                       <div class="preview"><span>Preview course</span></div>
                   </figure>
                   <div class="wrapper">
                       <small>Category</small>
                       <h3>At deseruisse scriptorem</h3>
                       <p>Id placerat tacimates definitionem.......</p>
                       <div class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i> <small>(145)</small></div>
                   </div>
                   <ul>
                       <li><i class="icon_clock_alt"></i> 1h 30min</li>
                       <li><i class="icon_like"></i> 890</li>
                       <li><a href="/home/course_detail">Enroll now</a></li>
                   </ul>
               </div>
           </div>

   <?php }
       }?>
                                        </div>
                               </div>
                           </div>
                           <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                               <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                               <span class="sr-only">Previous</span>
                           </a>
                           <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                               <span class="carousel-control-next-icon" aria-hidden="true"></span>
                               <span class="sr-only">Next</span>
                           </a>
                       </div>
<?php }?>
               </div>

           </div>



       </div>
</main>

<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>

<?php (Message::getMessage('errors')); ?>