<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>


<main>
    <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
    NextCopy

    <?php if (array_key_exists('latestCourses', $this->view_data)) {
        ?>
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <?php foreach ($this->view_data['latestCourses'] as $k => $course) { ?>

                    <li data-target="#carouselExampleCaptions"
                        data-slide-to="<?php echo $course['course_id'] ?>" <?php if ($k == 0) echo ' class="active"' ?> ></li>

                <?php } ?>
            </ol>
            <div class="carousel-inner">
                <?php foreach ($this->view_data['latestCourses'] as $k => $course) { ?>
                    <div class="carousel-item  <?php if ($k == 0) echo 'active' ?> ">
                        <img src="<?php echo $course['courses_image'] ?>" class="d-block w-100" alt="..." height="70%">
                        <div class="carousel-caption d-none d-md-block">
                            <h5><?php echo $course['course_title'] ?></h5>
                            <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button"
                           data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button"
                           data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                <?php } ?>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    <?php } ?>
    <div class="row" style="margin-top: 20px">
        <div class="container">

            <?php include VIEW . 'messages.phtml' ?>


            <div class="row">

                <div class=" card col-lg-12 col-md-12 col-ms-12" style="border-bottom: red">
                    <h2>Popular Courses</h2>

                </div>
                <div class="col-lg-12 col-md-12 col-ms-12">
                    <?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'coursesView.phtml' ?>
                </div>

            </div>


        </div>
</main>

<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'active.phtml' ?>

<script>
    AddToWish('/courses');
</script>
<?php (Message::getMessage('errors')); ?>
