<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>كورسات</title>

    <!-- Bootstrap 4.0-->
    <link rel="stylesheet" href="/design/site/css/bootstrap.css">
    <link rel="stylesheet" href="/design/site/css/bootstrap-rtl.min.css">
    <link rel="stylesheet" href="/design/site/fonts/font-awesome-4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="/design/site/css/custom.css">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="nav">
    <div class="container-fluid">
        <div class="row">
            <div class="col-4">
                <div class="hamburger">
                    <i class="fa fa-bars"></i>
                </div>
            </div>
            <div class="col-4">
                <div class="user-icon"></div>
            </div>
            <div class="col-4">
                <div class="user-icons">
                    <ul class="user-icons-list">
                        <?php if (!isset($_SESSION['user'])) { ?>
                            <li class="icon-login"><i class="fa fa-user"></i>
                                <form method="POST" class="my-login-validation login-form" action="/home/postLogin"
                                      id='first_form'>
                                    <div class="login-heading">   تسجيل الدخول</div>
                                    <div class="input-group user-email">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fa fa-user"></i></span>
                                        </div>
                                        <input type="text" value="<?php Helper::old('username'); ?>" id="user_email" name="username" class="form-control"
                                               placeholder="ادخل بريدك الالكتروني او اسم المستخدم">
                                    </div>

                                    <div class="input-group user-password">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fa fa-key"></i></span>
                                        </div>
                                        <input type="password" class="form-control" placeholder="ادخل كلمة المرور"
                                               id="password" name="password">
                                    </div>
                                    <button id="login-btn">تسجيل الدخول</button>
                                    <div class="create-new">
                                        لايوجد لديك حساب ؟ يمكنك التسجيل
                                        <a href="/home/register/student"> كطالب</a>
                                        <a href="/home/register/university"> او كجامعة</a>
                                    </div>
                                </form>
                            </li>
                        <?php } elseif (isset($_SESSION['user'])) { ?>
                            <li><i class="fa fa-heart"></i><span><?php echo Helper::wishListCount() ?></span></li>
                            <li>
                                <i class="fa fa-shopping-cart"></i><span><?php echo isset($_COOKIE['cartElements']) ? count($_COOKIE['cartElements']) : 0 ?></span>
                            </li>
                            <li><i class="fa fa-bell"></i><span>0</span></li>
                            <li>
                                <div class="user-name">
                                    <i class="fa fa-user"></i>
                                    <span> طاهر السماوي</span>
                                    <div class="user-settings">
                                        <ul>
                                            <li><a href="/profile"><i class="fa fa-user"></i> عرض الملف الشخصي</a></li>
                                            <li><a href="/admin/logout"><i class="fa fa-sign-out"></i> تسجيل الخروج</a>
                                            </li>
                                        </ul>

                                    </div>
                                </div>
                            </li>
                        <?php } ?>
                    </ul>


                </div>
            </div>

        </div>
    </div>


</div>


<?php //include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>


<!-- Start Content  -->
<div class="content collapse-content">
    <div class="container-fluid">
        <div class="row ">
            <!-- Start Sidebar-->
            <div class="col-2 sidebar">
                <div class="logo-site">
                    <img src="/images/logo-color.png">
                </div>
                <div class="logo-site-small">
                    <img src="/images/logo-icon.png">
                </div>
                <ul>
                    <li><a href="#" class="active">
                            <span class="icon"><i class="fa fa-home"></i></span>
                            <span class="title">الصفحة الرئيسية</span>
                        </a>
                    </li>

                    <li><a href="#">
                            <span class="icon"><i class="fa fa-star"></i></span>
                            <span class="title">المفضلة</span>
                        </a></li>

                    <li><a href="#">
                            <span class="icon"><i class="fa fa-line-chart"></i></span>
                            <span class="title">مستوى التقدم</span>

                        </a></li>

                    <li><a href="#">
                            <span class="icon"><i class="fa fa-cog"></i></span>
                            <span class="title">الأعدادات</span>
                        </a>
                    </li>


                    <li><a href="#">
                            <span class="icon"><i class="fa fa-book"></i></span>
                            <span class="title">الصفحة الرئيسية</span>
                        </a></li>
                    <li><a href="#">
                            <span class="icon"><i class="fa fa-book"></i></span>
                            <span class="title">الصفحة الرئيسية</span>
                        </a></li>
                    <li><a href="#">
                            <span class="icon"><i class="fa fa-book"></i></span>
                            <span class="title">من نحن </span>
                        </a></li>
                </ul>

            </div>
            <!-- End Sidebar-->

            <!-- Start main-content-->
            <div class="col-10 main-content ">
                <?php include VIEW . 'messages.phtml'; ?>

                <div class="general-courses">
                    <div class="row row-cols-3">
                        <div class="col ">
                            <div class="general-courses-content">
                                <img class="" src="/images/courses/photoshop.jpg">
                                <span class="icon-play-video"><i class="fa fa-play"></i></span>
                                <span class="course-title">كورس تعلم البرمجة</span>
                                <span class="course-duration">60:00 AM</span>
                            </div>
                        </div>

                        <div class="col ">
                            <div class="general-courses-content">
                                <img class="" src="/images/courses/photoshop.jpg">
                                <span class="icon-play-video"><i class="fa fa-play"></i></span>
                                <span class="course-title">كورس تعلم البرمجة</span>
                                <span class="course-duration">60:00 AM</span>
                            </div>
                        </div>

                        <div class="col ">
                            <div class="general-courses-content">
                                <img class="" src="/images/courses/photoshop.jpg">
                                <span class="icon-play-video"><i class="fa fa-play"></i></span>
                                <span class="course-title">كورس تعلم البرمجة</span>
                                <span class="course-duration">60:00 AM</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="top-courses">
                    <ul class="tabs-list">
                        <li class="active" data-content=".latest-courses">اخر الكورسات</li>
                        <li data-content=".most-popular-course">الاكثر شهرة</li>
                        <li data-content=".most-viewed-courses">الاكثر مشاهدة</li>
                    </ul>

                    <i class="fa fa-chevron-right"></i>
                    <i class="fa fa-chevron-left"></i>
                    <div class="courses-list">
                        <div class="latest-courses">
                            <div class="row row-cols-xl-4 row-cols-md-3 row-cols-xm-2">
                                <?php
                                foreach ($this->view_data['courses'] as $k => $course) { ?>
                                    <!-- Start Grid Column -->
                                    <div class="col">
                                        <div class="card" id="course_<?php echo $course['course_id'] ?>">
                                            <div class="course-img">
                                                <a href="/home/course_detail/<?php echo $course['course_id'] ?>">
                                                    <img class="card-img-top"
                                                         src="<?php echo $course['courses_image']; ?>">
                                                </a>
                                            </div>
                                            <div class="card-body">
                                                <a href="/home/course_detail/<?php echo $course['course_id'] ?>">
                                                    <h4 class="course-title">
                                                        <?php echo $course['course_title'] ?>
                                                    </h4>
                                                </a>


                                                <h6 class="course-category">التصنيف :
                                                    <span> <?php echo Helper::Names($course['categories_ids'], 'Category') ?> </span>
                                                </h6>
                                                <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                محاضرة
                                                </span>
                                                    <span class="course-time">
                                                <i class="fa fa-clock-o"></i>
                                                    12 ساعة
                                                </span>
                                                </div>

                                                <div class="cart-rating">
                                                    <ul class="stars-rating">
                                                        <li><i class="fa fa-star rating-done"></i></li>
                                                        <li><i class="fa fa-star rating-done"></i></li>
                                                        <li><i class="fa fa-star rating-done"></i></li>
                                                        <li><i class="fa fa-star rating-done"></i></li>
                                                        <li><i class="fa fa-star "></i></li>
                                                    </ul>
                                                    <span class="average-rating ">4.5</span>
                                                    <span class="total-rating">(  50354 تقييم )</span>

                                                </div>
                                            </div>
                                            <div class="course-footer">
                                            <span class="course-price">
                                         $ <?php echo $course['course_price'] ?>
                                            </span>
                                                <span class="show-course">
                                                    <a href="/home/course_detail/<?php echo $course['course_id'] ?>">
                                                     <i class="fa fa-eye"></i>
                                                     </a>

                                            </span>
                                            </div>
                                        </div>

                                    </div>
                                    <!-- End Grid Column -->

                                <?php } ?>


                            </div>
                        </div>


                        <div class="most-popular-course">
                            <div class="row row-cols-xl-4 row-cols-md-3 row-cols-xm-2">
                                <!-- Start Grid Column -->
                                <div class="col">
                                    <div class="card">
                                        <div class="course-img">
                                            <img class="card-img-top" src="/images/courses/photoshop.jpg">
                                        </div>
                                        <div class="card-body">
                                            <h4 class="course-title">كورس تعلم الفوتوشوب من الصفر حتى الاحتراف</h4>

                                            <h6 class="course-category">التصنيف :<span>تصميم </span></h6>
                                            <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                    15 محاضرة
                                                </span>
                                                <span class="course-time">
                                                <i class="fa fa-clock-o"></i>
                                                    12 ساعة
                                                </span>
                                            </div>

                                            <div class="cart-rating">
                                                <ul class="stars-rating">
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star "></i></li>
                                                </ul>
                                                <span class="average-rating ">4.5</span>
                                                <span class="total-rating">(  50354 تقييم )</span>

                                            </div>
                                        </div>
                                        <div class="course-footer">
                                            <span class="course-price">
                                              مجاني
                                            </span>
                                            <span class="show-course">
                                                <i class="fa fa-eye"></i>
                                            </span>
                                        </div>
                                    </div>

                                </div>
                                <!-- End Grid Column -->

                                <!-- Start Grid Column -->
                                <div class="col">
                                    <div class="card">
                                        <div class="course-img">
                                            <img class="card-img-top" src="/images/courses/photoshop.jpg">
                                        </div>
                                        <div class="card-body">
                                            <h4 class="course-title">كورس تعلم الفوتوشوب من الصفر حتى الاحتراف</h4>

                                            <h6 class="course-category">التصنيف :<span>تصميم </span></h6>
                                            <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                    15 محاضرة
                                                </span>
                                                <span class="course-time">
                                                <i class="fa fa-clock-o"></i>
                                                    12 ساعة
                                                </span>
                                            </div>

                                            <div class="cart-rating">
                                                <ul class="stars-rating">
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star "></i></li>
                                                </ul>
                                                <span class="average-rating ">4.5</span>
                                                <span class="total-rating">(  50354 تقييم )</span>

                                            </div>
                                        </div>
                                        <div class="course-footer">
                                            <span class="course-price">
                                              مجاني
                                            </span>
                                            <span class="show-course">
                                                <i class="fa fa-eye"></i>
                                            </span>
                                        </div>
                                    </div>

                                </div>
                                <!-- End Grid Column -->

                                <!-- Start Grid Column -->
                                <div class="col">
                                    <div class="card">
                                        <div class="course-img">
                                            <img class="card-img-top" src="/images/courses/photoshop.jpg">
                                        </div>
                                        <div class="card-body">
                                            <h4 class="course-title">كورس تعلم الفوتوشوب من الصفر حتى الاحتراف</h4>

                                            <h6 class="course-category">التصنيف :<span>تصميم </span></h6>
                                            <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                    15 محاضرة
                                                </span>
                                                <span class="course-time">
                                                <i class="fa fa-clock-o"></i>
                                                    12 ساعة
                                                </span>
                                            </div>

                                            <div class="cart-rating">
                                                <ul class="stars-rating">
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star "></i></li>
                                                </ul>
                                                <span class="average-rating ">4.5</span>
                                                <span class="total-rating">(  50354 تقييم )</span>

                                            </div>
                                        </div>
                                        <div class="course-footer">
                                            <span class="course-price">
                                              مجاني
                                            </span>
                                            <span class="show-course">
                                                <i class="fa fa-eye"></i>
                                            </span>
                                        </div>
                                    </div>

                                </div>
                                <!-- End Grid Column -->

                                <!-- Start Grid Column -->
                                <div class="col">
                                    <div class="card">
                                        <div class="course-img">
                                            <img class="card-img-top" src="/images/courses/photoshop.jpg">
                                        </div>
                                        <div class="card-body">
                                            <h4 class="course-title">كورس تعلم الفوتوشوب من الصفر حتى الاحتراف</h4>

                                            <h6 class="course-category">التصنيف :<span>تصميم </span></h6>
                                            <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                    15 محاضرة
                                                </span>
                                                <span class="course-time">
                                                <i class="fa fa-clock-o"></i>
                                                    12 ساعة
                                                </span>
                                            </div>

                                            <div class="cart-rating">
                                                <ul class="stars-rating">
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star "></i></li>
                                                </ul>
                                                <span class="average-rating ">4.5</span>
                                                <span class="total-rating">(  50354 تقييم )</span>

                                            </div>
                                        </div>
                                        <div class="course-footer">
                                            <span class="course-price">
                                              مجاني
                                            </span>
                                            <span class="show-course">
                                                <i class="fa fa-eye"></i>
                                            </span>
                                        </div>
                                    </div>

                                </div>
                                <!-- End Grid Column -->
                            </div>
                        </div>
                        <div class="most-viewed-courses">
                            <div class="row row-cols-xl-4 row-cols-md-3 row-cols-xm-2">


                                <!-- Start Grid Column -->
                                <div class="col">
                                    <div class="card">
                                        <div class="course-img">
                                            <img class="card-img-top" src="/images/courses/1.png">
                                        </div>
                                        <div class="card-body">
                                            <h4 class="course-title">كورس تعلم الفوتوشوب من الصفر حتى الاحتراف</h4
                                            <h6 class="course-category">التصنيف :<span>تصميم </span></h6>
                                            <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                    15 محاضرة
                                                </span>
                                                <span class="course-time">
                                                <i class="fa fa-clock-o"></i>
                                                    12 ساعة
                                                </span>
                                            </div>

                                            <div class="cart-rating">
                                                <ul class="stars-rating">
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star "></i></li>
                                                </ul>
                                                <span class="average-rating ">4.5</span>
                                                <span class="total-rating">(  50354 تقييم )</span>

                                            </div>
                                        </div>
                                        <div class="course-footer">
                                            <span class="course-price">
                                              مجاني
                                            </span>
                                            <span class="show-course">
                                                <i class="fa fa-eye"></i>
                                            </span>
                                        </div>
                                    </div>

                                </div>
                                <!-- End Grid Column -->

                                <!-- Start Grid Column -->
                                <div class="col">
                                    <div class="card">
                                        <div class="course-img">
                                            <img class="card-img-top" src="/images/courses/photoshop.jpg">
                                        </div>
                                        <div class="card-body">
                                            <h4 class="course-title">كورس تعلم الفوتوشوب من الصفر حتى الاحتراف</h4>

                                            <h6 class="course-category">التصنيف :<span>تصميم </span></h6>
                                            <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                    15 محاضرة
                                                </span>
                                                <span class="course-time">
                                                <i class="fa fa-clock-o"></i>
                                                    12 ساعة
                                                </span>
                                            </div>

                                            <div class="cart-rating">
                                                <ul class="stars-rating">
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star "></i></li>
                                                </ul>
                                                <span class="average-rating ">4.5</span>
                                                <span class="total-rating">(  50354 تقييم )</span>

                                            </div>
                                        </div>
                                        <div class="course-footer">
                                            <span class="course-price">
                                              مجاني
                                            </span>
                                            <span class="show-course">
                                                <i class="fa fa-eye"></i>
                                            </span>
                                        </div>
                                    </div>

                                </div>
                                <!-- End Grid Column -->

                                <!-- Start Grid Column -->
                                <div class="col">
                                    <div class="card">
                                        <div class="course-img">
                                            <img class="card-img-top" src="/images/courses/photoshop.jpg">
                                        </div>
                                        <div class="card-body">
                                            <h4 class="course-title">كورس تعلم الفوتوشوب من الصفر حتى الاحتراف</h4>

                                            <h6 class="course-category">التصنيف :<span>تصميم </span></h6>
                                            <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                    15 محاضرة
                                                </span>
                                                <span class="course-time">
                                                <i class="fa fa-clock-o"></i>
                                                    12 ساعة
                                                </span>
                                            </div>

                                            <div class="cart-rating">
                                                <ul class="stars-rating">
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star "></i></li>
                                                </ul>
                                                <span class="average-rating ">4.5</span>
                                                <span class="total-rating">(  50354 تقييم )</span>

                                            </div>
                                        </div>
                                        <div class="course-footer">
                                            <span class="course-price">
                                              مجاني
                                            </span>
                                            <span class="show-course">
                                                <i class="fa fa-eye"></i>
                                            </span>
                                        </div>
                                    </div>

                                </div>
                                <!-- End Grid Column -->

                                <!-- Start Grid Column -->
                                <div class="col">
                                    <div class="card">
                                        <div class="course-img">
                                            <img class="card-img-top" src="/images/courses/photoshop.jpg">
                                        </div>
                                        <div class="card-body">
                                            <h4 class="course-title">كورس تعلم الفوتوشوب من الصفر حتى الاحتراف</h4>

                                            <h6 class="course-category">التصنيف :<span>تصميم </span></h6>
                                            <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                    15 محاضرة
                                                </span>
                                                <span class="course-time">
                                                <i class="fa fa-clock-o"></i>
                                                    12 ساعة
                                                </span>
                                            </div>

                                            <div class="cart-rating">
                                                <ul class="stars-rating">
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star rating-done"></i></li>
                                                    <li><i class="fa fa-star "></i></li>
                                                </ul>
                                                <span class="average-rating ">4.5</span>
                                                <span class="total-rating">(  50354 تقييم )</span>

                                            </div>
                                        </div>
                                        <div class="course-footer">
                                            <span class="course-price">
                                              مجاني
                                            </span>
                                            <span class="show-course">
                                                <i class="fa fa-eye"></i>
                                            </span>
                                        </div>
                                    </div>

                                </div>
                                <!-- End Grid Column -->
                            </div>

                        </div>

                    </div>
                </div>
            </div>
            <!-- End main-content-->


        </div>
    </div>
</div>
<!-- End Content  -->


<!-- jQuery 3 -->
<script src="/design/site/js/jquery-3.3.1.min.js"></script>
<!-- popper -->
<script src="/design/site/js/popper.min.js"></script>
<!-- Bootstrap 4.0-->
<script src="/design/site/js/bootstrap.js"></script>

<script src="/design/site/js/main.js"></script>


</body>

</html>
