

<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>


<div class="nav">
    <div class="container-fluid">
        <div class="row">
            <div class="col-4">
                <div class="hamburger">
                    <i class="fa fa-bars"></i>
                </div>
            </div>
            <div class="col-8">
                <div class="user-icons">
                    <ul class="user-icons-list">
                        <?php if (!isset($_SESSION['user'])) { ?>
                            <li class="icon-login"><i class="fa fa-user"></i>
                                <form method="POST" class="my-login-validation login-form" action="/home/postLogin"
                                      id='first_form'>
                                    <div class="login-heading">تسجيل الدخول</div>
                                    <div class="input-group user-email">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fa fa-user"></i></span>
                                        </div>
                                        <input type="text" value="<?php Helper::old('username'); ?>" id="user_email"
                                               name="username" class="form-control"
                                               placeholder="ادخل بريدك الالكتروني او اسم المستخدم">
                                    </div>

                                    <div class="input-group user-password">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fa fa-key"></i></span>
                                        </div>
                                        <input type="password" class="form-control" placeholder="ادخل كلمة المرور"
                                               id="password" name="password">
                                    </div>
                                    <button id="login-btn">تسجيل الدخول</button>
                                    <div class="create-new">
                                        لايوجد لديك حساب ؟ يمكنك التسجيل
                                        <a href="/home/register/student"> كطالب</a>
                                        <a href="/home/register/university"> او كجامعة</a>
                                    </div>
                                </form>
                            </li>
                        <?php } elseif (isset($_SESSION['user'])) { ?>
                            <li><i class="fa fa-heart"></i><span
                                        id="n_whishList_items"><?php echo Helper::wishListCount() ?></span></li>
                            <li class="shopping-cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span id="n_cart_items"><?php echo isset($_COOKIE['cartElements']) ? count($_COOKIE['cartElements']) : 0 ?></span>
                            </li>
                            <li><i class="fa fa-bell"></i><span>2</span></li>
                            <li>
                                <div class="user-name">
                                    <i class="fa fa-user"></i>
                                    <span> طاهر السماوي</span>
                                    <div class="user-settings">
                                        <ul>
                                            <li><a href="/profile"><i class="fa fa-user"></i> عرض الملف الشخصي</a></li>
                                            <li><a href="/admin/logout"><i class="fa fa-sign-out"></i> تسجيل الخروج</a>
                                            </li>
                                        </ul>

                                    </div>
                                </div>
                            </li>
                        <?php } ?>
                    </ul>


                </div>
            </div>

        </div>
    </div>
</div>

<!-- Start Content  -->
<div class="content collapse-content">
    <div class="container-fluid">
        <div class="row ">
            <!-- Start Sidebar-->
            <div class="col-2 sidebar">
                <div class="logo-site">
                    <img src="/images/logo-color.png">
                </div>
                <div class="logo-site-small">
                    <img src="/images/logo-icon.png">
                </div>
                <ul>
                    <li><a href="#" class="active">
                            <span class="icon"><i class="fa fa-home"></i></span>
                            <span class="title">الصفحة الرئيسية</span>
                        </a>
                    </li>

                    <li><a href="#">
                            <span class="icon"><i class="fa fa-star"></i></span>
                            <span class="title">المفضلة</span>
                        </a></li>

                    <li><a href="#">
                            <span class="icon"><i class="fa fa-line-chart"></i></span>
                            <span class="title">مستوى التقدم</span>

                        </a></li>

                    <li><a href="#">
                            <span class="icon"><i class="fa fa-cog"></i></span>
                            <span class="title">الأعدادات</span>
                        </a>
                    </li>


                    <li><a href="#">
                            <span class="icon"><i class="fa fa-book"></i></span>
                            <span class="title">الصفحة الرئيسية</span>
                        </a></li>
                    <li><a href="#">
                            <span class="icon"><i class="fa fa-book"></i></span>
                            <span class="title">الصفحة الرئيسية</span>
                        </a></li>
                    <li><a href="#">
                            <span class="icon"><i class="fa fa-book"></i></span>
                            <span class="title">من نحن </span>
                        </a></li>
                </ul>

            </div>
            <!-- End Sidebar-->

            <!-- Start main-content-->
            <div class="col-10 main-content ">
                <?php include VIEW . 'messages.phtml'; ?>


                <div class="general-courses">
                    <div class="row row-cols-lg-3 row-cols-1">
                        <?php
                        foreach ($this->view_data['courses'] as $k => $course) { ?>
                        <?php if ($course['averageRating']>=1.5) {?>
                        <div class="col ">
                            <div class="general-courses-content">
                                <img class="" src="<?php echo  $course['courses_image'];?>">
                                <a href="/courses/course_review/<?php echo $course['course_id'] ?>"><span class="icon-play-video"><i class="fa fa-play"></i></span></a>
                                <span class="course-title"><?php echo  $course['course_title'] ?></span>
                                <span class="course-rating"><?php Helper::getNumberStars($course['averageRating']);  ?></span>
                                <span class="course-duration"><?php echo  $course['duration'] ?></span>
                            </div>
                        </div>
                        <?php }}?>

                    </div>
                </div>
                <div class="top-courses">
                    <ul class="tabs-list">
                        <li class="active" data-content=".latest-courses">اخر الكورسات</li>
<!--                        <li data-content=".most-popular-course">الاكثر شهرة</li>-->
                        <li data-content=".most-viewed-courses">الاكثر مشاهدة</li>
                    </ul>

                    <i class="fa fa-chevron-right"></i>
                    <i class="fa fa-chevron-left"></i>
                    <div class="courses-list">
                        <div class="latest-courses">
                            <div class="row row-cols-xl-4 row-cols-md-3 row-cols-sm-2">
                                <?php
                                foreach ($this->view_data['courses'] as $k => $course) { ?>
                                    <!-- Start Grid Column -->
                                    <div class="col">
                                        <div class="card" id="course_<?php echo $course['course_id'] ?>">
                                            <div class="course-img">
                                                <a href="/courses/course_review/<?php echo $course['course_id'] ?>">
                                                    <img class="card-img-top"
                                                         src="<?php echo $course['courses_image']; ?>">
                                                </a>
                                            </div>

                                            <div class="icon-wishlist">
                                                <?php if (isset($_SESSION['user'])) { ?>
                                                    <a <?php if (in_array($course['course_id'], $this->view_data['userWishList']))
                                                        echo 'class="fa fa-heart addToWishList"  data-status="1"';
                                                    else
                                                        echo 'class="fa fa-heart-o addToWishList"  data-status="0"'; ?>
                                                            data-id="<?php echo $course['course_id'] ?>">
                                                    </a>
                                                <?php } ?>
                                            </div>



                                            <div class="card-body">
                                                <a href="/courses/course_review/<?php echo $course['course_id'] ?>">
                                                    <h4 class="course-title">
                                                        <?php echo $course['course_title'] ?>
                                                    </h4>
                                                </a>


                                                <h6 class="course-category">التصنيف :
                                                    <span> <?php echo Helper::Names($course['categories_ids'], 'Category') ?> </span>
                                                </h6>
                                                <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                       <?php echo $course['course_count'];  ?>
                                                    فيديو
                                                </span>
                                                    <span class="course-time">
                                                <i class="fa fa-clock-o"></i>

                                                  <?php echo $course['duration'];  ?>
                                                </span>
                                                </div>

                                                <div class="cart-rating">
                                                    <ul class="stars-rating">
                                                        <?php Helper::getNumberStars($course['averageRating']);  ?>
                                                    </ul>
                                                    <span class="average-rating "><?php echo $course['averageRating'];  ?></span>
                                                    <span class="total-rating">(من اصل <?php echo $course['AllRatings'];  ?> تقييم )</span>

                                                </div>
                                            </div>
                                            <div class="course-footer">
                                                   <span class="show-course">
                                                  السعر :
                                                </span>
                                            <span class="course-price">


                                          <?php  if($course['course_price']>0){
                                           echo '$' . $course['course_price'];
                                             }else
                                                 echo  "مجاني";
                                                 ?>
                                            </span>

                                            </div>
                                        </div>

                                    </div>
                                    <!-- End Grid Column -->

                                <?php } ?>


                            </div>
                        </div>
                        <div class="most-popular-course">
                            <div class="row row-cols-xl-4 row-cols-md-3 row-cols-xm-2">
                                <?php
                                foreach ($this->view_data['courses'] as $k => $course) { ?>
                                    <!-- Start Grid Column -->
                                    <div class="col">
                                        <div class="card" id="course_<?php echo $course['course_id'] ?>">
                                            <div class="course-img">
                                                <a href="/courses/course_review/<?php echo $course['course_id'] ?>">
                                                    <img class="card-img-top"
                                                         src="<?php echo $course['courses_image']; ?>">
                                                </a>
                                            </div>

                                            <div class="icon-wishlist">
                                                <?php if (isset($_SESSION['user'])) { ?>
                                                    <a <?php if (in_array($course['course_id'], $this->view_data['userWishList']))
                                                        echo 'class="fa fa-heart addToWishList"  data-status="1"';
                                                    else
                                                        echo 'class="fa fa-heart-o addToWishList"  data-status="0"'; ?>
                                                            data-id="<?php echo $course['course_id'] ?>">
                                                    </a>
                                                <?php } ?>
                                            </div>



                                            <div class="card-body">
                                                <a href="/courses/course_review/<?php echo $course['course_id'] ?>">
                                                    <h4 class="course-title">
                                                        <?php echo $course['course_title'] ?>
                                                    </h4>
                                                </a>


                                                <h6 class="course-category">التصنيف :
                                                    <span> <?php echo Helper::Names($course['categories_ids'], 'Category') ?> </span>
                                                </h6>
                                                <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                       <?php echo $course['course_count'];  ?>
                                                    فيديو
                                                </span>
                                                    <span class="course-time">
                                                <i class="fa fa-clock-o"></i>

                                                  <?php echo $course['duration'];  ?>
                                                </span>
                                                </div>

                                                <div class="cart-rating">
                                                    <ul class="stars-rating">
                                                        <?php Helper::getNumberStars($course['averageRating']);  ?>
                                                    </ul>
                                                    <span class="average-rating "><?php echo $course['averageRating'];  ?></span>
                                                    <span class="total-rating">(من اصل <?php echo $course['AllRatings'];  ?> تقييم )</span>

                                                </div>
                                            </div>
                                            <div class="course-footer">
                                                   <span class="show-course">
                                                  السعر :
                                                </span>
                                                <span class="course-price">


                                          <?php  if($course['course_price']>0){
                                              echo '$' . $course['course_price'];
                                          }else
                                              echo  "مجاني";
                                          ?>
                                            </span>

                                            </div>
                                        </div>

                                    </div>
                                    <!-- End Grid Column -->

                                <?php } ?>


                            </div>
                        </div>
                        <div class="most-viewed-courses">
                            <div class="row row-cols-xl-4 row-cols-md-3 row-cols-sm-2 flex-row-reverse">
                                <?php
                                foreach ($this->view_data['courses'] as $k => $course) { ?>
                                    <!-- Start Grid Column -->
                                    <div class="col">
                                        <div class="card" id="course_<?php echo $course['course_id'] ?>">
                                            <div class="course-img">
                                                <a href="/courses/course_review/<?php echo $course['course_id'] ?>">
                                                    <img class="card-img-top"
                                                         src="<?php echo $course['courses_image']; ?>">
                                                </a>
                                            </div>

                                            <div class="icon-wishlist">
                                                <?php if (isset($_SESSION['user'])) { ?>
                                                    <a <?php if (in_array($course['course_id'], $this->view_data['userWishList']))
                                                        echo 'class="fa fa-heart addToWishList"  data-status="1"';
                                                    else
                                                        echo 'class="fa fa-heart-o addToWishList"  data-status="0"'; ?>
                                                            data-id="<?php echo $course['course_id'] ?>">
                                                    </a>
                                                <?php } ?>
                                            </div>



                                            <div class="card-body">
                                                <a href="/courses/course_review/<?php echo $course['course_id'] ?>">
                                                    <h4 class="course-title">
                                                        <?php echo $course['course_title'] ?>
                                                    </h4>
                                                </a>


                                                <h6 class="course-category">التصنيف :
                                                    <span> <?php echo Helper::Names($course['categories_ids'], 'Category') ?> </span>
                                                </h6>
                                                <div class="course-details">
                                                <span class="course-lectures">
                                               <i class="fa fa-play-circle-o"></i>
                                                       <?php echo $course['course_count'];  ?>
                                                    فيديو
                                                </span>
                                                    <span class="course-time">
                                                <i class="fa fa-clock-o"></i>

                                                  <?php echo $course['duration'];  ?>
                                                </span>
                                                </div>

                                                <div class="cart-rating">
                                                    <ul class="stars-rating">
                                                        <?php Helper::getNumberStars($course['averageRating']);  ?>
                                                    </ul>
                                                    <span class="average-rating "><?php echo $course['averageRating'];  ?></span>
                                                    <span class="total-rating">(من اصل <?php echo $course['AllRatings'];  ?> تقييم )</span>

                                                </div>
                                            </div>
                                            <div class="course-footer">
                                                   <span class="show-course">
                                                  السعر :
                                                </span>
                                                <span class="course-price">


                                          <?php  if($course['course_price']>0){
                                              echo '$' . $course['course_price'];
                                          }else
                                              echo  "مجاني";
                                          ?>
                                            </span>

                                            </div>
                                        </div>

                                    </div>
                                    <!-- End Grid Column -->

                                <?php } ?>

                            </div>

                        </div>

                    </div>
                </div>
            </div>
            <!-- End main-content-->


        </div>
    </div>
</div>
<!-- End Content  -->

<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'active.phtml' ?>


<script>
    AddToWish('/courses');




</script>
<?php (Message::getMessage('errors')); ?>

</body>

</html>


