<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>

<main>
    <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>

    </section>
    <div class="container">
        <div class="row wish_list">
            <div class="col-lg-12 col-md-12 col-ms-12">
                <h2>My Wish List</h2>

            </div>
        </div>
    </div>

    <div class="container margin_61_35">
        <div class="row">
            <div class="col-xl-4 col-lg-6 col-md-6">
                <div class="box_grid wow">
                    <figure class="block-reveal">
                        <div class="block-horizzontal"></div>
                        <div class="block-horizzontal"></div>
                        <a <?php if (in_array($course['course_id'], $this->view_data['userWishList']))
                            echo 'class="wish_bt_active addToWishList"    onclick="confirm(\'هل تريد الغاء هذا الكورس من المفضلة \')"  data-status="1"';
                        else
                            echo 'class="wish_bt addToWishList"   onclick="confirm(\'هل تريد اضافة هذا الكورس الى المفضلة \')"  data-status="0"'; ?>
                                data-id="<?php echo $course['course_id'] ?>">
                        </a>
                        <a href="/home/course_detail"><img src="/img/1.jpg" class="img-fluid" alt=""></a>
                        <div class="price">$54</div>
                        <div class="preview"><span>Preview course</span></div>
                    </figure>
                    <div class="wrapper">
                        <small>Category</small>
                        <h3>Persius delenit has cu</h3>
                        <p>Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.</p>
                        <div class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i
                                    class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i>
                            <small>(145)</small></div>
                    </div>
                    <ul>
                        <li><i class="icon_clock_alt"></i> 1h 30min</li>
                        <li><i class="icon_like"></i> 890</li>
                        <li><a href="/home/course_detail">Enroll now</a></li>
                    </ul>
                </div>
            </div>
            <!-- /box_grid -->
            <div class="col-xl-4 col-lg-6 col-md-6">
                <div class="box_grid wow">
                    <figure class="block-reveal">
                        <div class="block-horizzontal"></div>
                        <a href="#0" class="wish_bt"></a>
                        <a href="/home/course_detail"><img src="/img/1.jpg" class="img-fluid" alt=""></a>
                        <div class="price">$45</div>
                        <div class="preview"><span>Preview course</span></div>
                    </figure>
                    <div class="wrapper">
                        <small>Category</small>
                        <h3>At deseruisse scriptorem</h3>
                        <p>Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.</p>
                        <div class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i
                                    class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i>
                            <small>(145)</small></div>
                    </div>
                    <ul>
                        <li><i class="icon_clock_alt"></i> 1h 30min</li>
                        <li><i class="icon_like"></i> 890</li>
                        <li><a href="/home/course_detail">Enroll now</a></li>
                    </ul>
                </div>
            </div>
            <!-- /box_grid -->
            <div class="col-xl-4 col-lg-6 col-md-6">
                <div class="box_grid wow">
                    <figure class="block-reveal">
                        <div class="block-horizzontal"></div>
                        <a href="#0" class="wish_bt"></a>
                        <a href="/home/course_detail"><img src="/img/1.jpg" class="img-fluid" alt=""></a>
                        <div class="price">$39</div>
                        <div class="preview"><span>Preview course</span></div>
                    </figure>
                    <div class="wrapper">
                        <small>Category</small>
                        <h3>Ea vel semper quaerendum</h3>
                        <p>Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.</p>
                        <div class="rating"><i class="icon_star voted"></i><i class="icon_star voted"></i><i
                                    class="icon_star voted"></i><i class="icon_star"></i><i class="icon_star"></i>
                            <small>(145)</small></div>
                    </div>
                    <ul>
                        <li><i class="icon_clock_alt"></i> 1h 30min</li>
                        <li><i class="icon_like"></i> 890</li>
                        <li><a href="/home/course_detail">Enroll now</a></li>
                    </ul>
                </div>
            </div>


        </div>


</main>



<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
