<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml' ?>

<main>
    <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>

    <div class="container margin_60_35">
        <?php include VIEW . 'messages.phtml' ?>
        <div class="container">
            <div class="row">
                <div class=" card col-lg-12 col-md-12 col-ms-12" style="border-bottom: red">
                    <h2>Your wishList Courses</h2>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-ms-12">
                <?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'coursesView.phtml' ?>
            </div>
        </div>
</main>
<?php include VIEW . 'website' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'active.phtml' ?>

<script>
    AddToWish('/courses', 'whishList');
</script>