<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>

<link href="/design/dashboard/lib/google-code-prettify/bin/prettify.min.css" rel="stylesheet">

<!-- Select2 -->
<link href="/design/dashboard/lib/select2/dist/css/select2.min.css" rel="stylesheet">
<!-- Switchery -->
<link href="/design/dashboard/lib/switchery/dist/switchery.min.css" rel="stylesheet">
<!-- starrr -->
<link href="/design/dashboard/lib/starrr/dist/starrr.css" rel="stylesheet">
<link rel="stylesheet" href="/design/dashboard/lib/jquery-ui/jquery-ui.css">


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<!-- Start Main-content -->
<div class="container">
    <div class="row bg-white mb-4 ">
        <div class="text-right mt-auto col-6">
            <h3><i class="fa fa-university" style="color:#ec3901"></i> اضافة جامعة جديدة  </h3>
        </div>
    </div>

    <div class="row-cols-1">
        <form class=""  method="post" action=""  enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <label for="user_email">البريد الالكتروني :</label>
                    <input type="email"   data-validate-linked="email" class="form-control" placeholder="Enter email" id="user_email" name="user_email">
                    <label for="user_password">كلمة المرور:</label>
                    <input type="password" class="form-control" placeholder="Enter password" id="user_password" name="user_password">
                    <label for="user_full_name">User Full Name:</label>
                    <input type="text" class="form-control"   data-validate-words="2" placeholder="Enter User Full Name" id="user_full_name" name="user_full_name">
                    <label for="user_name">User Name:</label>
                    <input type="text" class="form-control" placeholder="Enter User Name" id="user_name" name="user_name">

                </div>
                <div class="col-md-6">
                    <label for="user_phone">User Image:</label>
                    <div class="custom-file">

                        <input type="file" class="custom-file-input" id="customFile">
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                    <label for="user_phone">User Phone:</label>
                    <input type="phone" class="form-control" placeholder="Enter User Phone" id="user_phone" name="user_phone">
                    <label for="user_gender">User Gender:</label>
                    <input type="text" class="form-control" placeholder="Enter User Gender" id="user_gender" name="user_gender">
                    <label for="user_qualification">User Qualification:</label>
                    <input type="phone" class="form-control" placeholder="Enter User Qualification" id="user_qualification" name="user_qualification">

                </div>
                <br>
                <div class="col-md-12">
                    <br> <input type="submit" class="btn btn-primary btn-block" name="submit">
                </div>
            </div>

        </form>

    </div>

</div>
<!-- End Main-content -->
</div>
<!-- End Content -->
</div>
</div>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<script src="/design/dashboard/lib/jquery.tagsinput/src/jquery.tagsinput.js"></script>
<!-- Switchery -->
<script src="/design/dashboard/lib/switchery/dist/switchery.min.js"></script>
<!-- Select2 -->
<script src="/design/dashboard/lib/select2/dist/js/select2.full.min.js"></script>
<!-- Parsley -->
<script src="/design/dashboard/lib/parsleyjs/dist/parsley.min.js"></script>
<script src="/design/dashboard/lib/parsleyjs/dist/i18n/ar.js"></script>
<!-- Autosize -->
<script src="/design/dashboard/lib/autosize/dist/autosize.min.js"></script>
<!-- jQuery autocomplete -->
<script src="/design/dashboard/lib/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
<!-- starrr -->
<script src="/design/dashboard/lib/starrr/dist/starrr.js"></script>

<script src="/design/dashboard/lib/jquery-ui/jquery-ui.js"></script>
<!-- validator -->
<script src="/design/dashboard/lib/validator/validator.js"></script>

<script>

    $(function () {
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2').select2()
    })
</script>
<script>


    $(document).on('change', '#logo', function () {


        if (window.File && window.FileReader && window.FileList && window.Blob) //check File API supported browser
        {
            var data = $(this)[0].files; //this file data
            $('#logo_image').html('');
            $.each(data, function (index, file) { //loop though each file
                if (/(\.|\/)(gif|jpe?g|png)$/i.test(file.type)) { //check supported file type
                    var fRead = new FileReader(); //new filereader
                    fRead.onload = (function (file) { //trigger function on successful read
                        return function (e) {
                            var img = $('<img/>').addClass('thumb').attr('src', e.target.result); //create image element
                            $('#logo_image').append(img); //append image to output element
                        };
                    })(file);
                    fRead.readAsDataURL(file); //URL representing the file's data.
                }
            });
        } else {
            alert("Your browser doesn't support File API!"); //if File API is absent
        }
    });

    CKEDITOR.replace('editor', {filebrowserImageBrowseUrl: '/file-manager/ckeditor'});
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>

