<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableCss.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<div class="content">
    <h2 class="text-center"><i class="fa fa-university" style="color:#ec3901"></i> University Accounts Manage</h2>

    <div class="row fa-pull-right">
        <div class="col-8">
            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                        id="dashboard_daterangepicker">
                    <i class="	fas fa-bullseye"></i> sorting data by
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Day</a>
                    <a class="dropdown-item" href="#">Week</a>
                    <a class="dropdown-item" href="#">Month</a>
                    <a class="dropdown-item" href="#">Range</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-4"><a href="/admin/universities/create" class="btn btn-success "><i class="fa fa-plus"> </i> Add</a>
    </div>
    <br>
    <table id="example1" class="table table-bordered table-striped">
        <thead class="thead-dark font-size-18">
        <tr>
            <th> Name</th>
            <th>Email</th>
            <th>User Display Name</th>
            <th>User Image</th>
            <th>User Phone</th>
            <th>Registration Date</th>
         <th>Control</th>

        </tr>
        </thead>

        <tbody>
        <?php if (array_key_exists('universities', $this->view_data)) {
            foreach ($this->view_data['universities'] as $university) { ?>

                <tr>
                    <td><?php echo $university['user_name'] ?></td>
                    <td><?php echo $university['user_email'] ?></td>
                    <td><?php echo $university['user_full_name'] ?></td>
                    <td><?php echo $university['user_image'] ?></td>
                    <td><?php echo $university['user_phone'] ?></td>
                    <td><?php echo $university['user_register_date'] ?></td>
                    <td>
                        <a href="" data-id="<?php echo $university['user_id'] ?>"
                                data-status="<?php echo $university['user_status'] ?>"
                                class=" active"><?php echo ($university['user_status'] == '1') ?  '<i class=\'fas fa-check\'></i>' :'<i class=\'ion ion-close\'></i>'  ?> </a>



                    <?php if ($this->view_data['deleted'] == false) { ?>
                       <a href="/admin/universities/edit/<?php echo $university['id'] ?>" ><i class="fa fa-edit"></i></a>


                            <a href="/admin/universities/delete/<?php echo $university['id'] ?>"
                               onclick="return confirm('هل أنت متأكد من الحذف');" ><i
                                        class="fa fa-trash-restore"></i></a>

                        </td>
                    <?php } else { ?>
                        <th>{{getUserName( $university['deleted_by'] )?></th>
                        <td><?php echo $university['deleted_at'] ?></td>


                        <td class="text-center">
                            <a href="{{  route('admin.universities.restore',encrypt( $university['']id)) }}"
                               class="btn btn-primary"><i
                                        class="fa fa-arrow-up"></i></a>
                        </td>

                    <?php } ?>


                </tr>
            <?php }
        } ?>
    </table>
</div>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableJs.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'active.phtml' ?>

<script>
    Active('universities') ;

    $(function () {
        $('#example1').DataTable({
            language: {url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Arabic.json"},
            dom: "Blfrtip",
            buttons: [{extend: "copy", text: "نسخ", className: "btn-sm"}, {
                extend: "csv",
                text: "ملف CSV",
                className: "btn-sm"
            }, {extend: "excel", text: "اکسل", className: "btn-sm"}, {
                extend: "pdfHtml5",
                text: "ملف PDF",
                className: "btn-sm"
            }, {extend: "print", text: "طباعة", className: "btn-sm"}],
            responsive: !0
        });
    });
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>




