<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>

<link href="/design/dashboard/lib/google-code-prettify/bin/prettify.min.css" rel="stylesheet">

<!-- Select2 -->
<link href="/design/dashboard/lib/select2/dist/css/select2.min.css" rel="stylesheet">
<!-- Switchery -->
<link href="/design/dashboard/lib/switchery/dist/switchery.min.css" rel="stylesheet">
<!-- starrr -->
<link href="/design/dashboard/lib/starrr/dist/starrr.css" rel="stylesheet">
<link rel="stylesheet" href="/design/dashboard/lib/jquery-ui/jquery-ui.css">


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<div class="container">
    <div class="row bg-white mb-4 ">
        <div class="text-right  mt-auto col-6">
            <h2 class="text-center"><i class="fa fa fa-user-cog" style="color:#ec3901"></i> إضافة الادوار في الحسابات
            </h2>
        </div>
    </div>
    <form action="/admin/role/store" method="post">
        <div class="row">
            <div class="col-md-12">
                <label for="role_name">اسم الدور:</label>
                <input type="text" class="form-control" placeholder="اسم الدور" id="role_name" name="role_name">
                <label for="role_description">Role Description:</label>
                <textarea class="form-control" placeholder="Enter Role Description" id="role_description"
                          name="role_description">
                    </textarea>
            </div>

            <br>
            <div class="col-md-12">
                <br>
                <button type="submit" class="btn btn-success btn-block" name="submit">لإضافة</button>
            </div>
        </div>

        <div class="form-group">
            <div class="clearfix"></div>
            <li><label><input type="checkbox" id="select_all"/> Select all </label></li>

            <?php if (array_key_exists('permissions', $this->view_data)) {


                foreach ($this->view_data['permissions'] as $k => $sub_permission) {
                    ?>

                    <label class="col-md-3 col-sm-3 col-xs-12 control-label"
                    <label><input type="checkbox" onclick="selectSub($(this),'<?php echo $k ?>')"
                                  data-selected="0"/> Select all <?php echo $k ?></label>
                    <br>
                    </label>

                    <div class="form-group row">

                        <br>
                        <?php
                        foreach ($sub_permission[0] as $k_sub => $permission) { ?>
                            <div class="col-md-3 col-sm-4 col-xs-12">
                                <div class="checkbox">
                                    <label class="">
                                        <input type="checkbox" name="permissions[]"
                                               class="selectAll select-message<?php echo $k ?>"
                                               value="<?php echo $permission['permission_id'] ?>">
                                        <ins class="iCheck-helper"
                                             style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins>
                                        <?php echo $permission['permissions_description'] ?>
                                    </label>
                                </div>

                            </div>

                        <?php }
                        ?>
                        <!--                        @error('categories') <span class="btn-block badge badge-danger">{{ $message }}</span> @enderror-->

                    </div>
                <?php }
            }
            ?>

            <div class="clearfix"></div>
            <div class="clearfix"></div>
        </div>

    </form>
    <br>

</div>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<script src="/design/dashboard/lib/jquery.tagsinput/src/jquery.tagsinput.js"></script>
<!-- Switchery -->
<script src="/design/dashboard/lib/switchery/dist/switchery.min.js"></script>
<!-- Select2 -->
<script src="/design/dashboard/lib/select2/dist/js/select2.full.min.js"></script>
<!-- Parsley -->
<script src="/design/dashboard/lib/parsleyjs/dist/parsley.min.js"></script>
<script src="/design/dashboard/lib/parsleyjs/dist/i18n/ar.js"></script>
<!-- Autosize -->
<script src="/design/dashboard/lib/autosize/dist/autosize.min.js"></script>
<!-- jQuery autocomplete -->
<script src="/design/dashboard/lib/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
<!-- starrr -->
<script src="/design/dashboard/lib/starrr/dist/starrr.js"></script>

<script src="/design/dashboard/lib/jquery-ui/jquery-ui.js"></script>

<script>

    $(function () {
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2').select2()
    })
</script>
<script>


    $(document).on('click', '#select_all', function () {
        if (this.checked) {
            // Iterate each checkbox
            $('input:checkbox.selectAll').each(function () {
                this.checked = true;
            });

        } else {
            $('input:checkbox.selectAll').each(function () {
                this.checked = false;
            });
        }
    });

    function selectSub(e, id) {
        // alert(e.attr('type'));
        // e.attr('data-selected');
        // console.log(e.attr('isSelected'));
        // alert(e);
        if (e.attr('data-selected') == 0) {
            // Iterate each checkbox
            $('input:checkbox.select-message' + id).each(function () {
                this.checked = true;
                e.attr('data-selected', 1);
            });

        } else {
            $('input:checkbox.select-message' + id).each(function () {
                this.checked = false;
                e.attr('data-selected', 0)
            });
        }
    }


    fetchCategories('#main_category_parents', '#sub_category');
    fetchCategories('#sub_category', '#sub_sub_category');

    function fetchCategories(input, select) {

        $(document).on('change', input, function () {
            var data = 'category_parents=' + encodeURIComponent($(this).val());
            var url = '/admin/Categories/fetchSubCategories';
            $.ajax({
                url: url,//   var url=$('#news').attr('action');
                method: 'POST',
                dataType: 'json',// data type that i want to return
                data: data,// var form=$('#news').serialize();
                success: function (data) {
                    $(select).html(data);

                }, error:
                    function (xhr, status, error) {
                        $(select).html(xhr.responseText);
                    }
            });
            return (false);
        });
    }


</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>

