<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>

<link href="/design/dashboard/lib/google-code-prettify/bin/prettify.min.css" rel="stylesheet">

<!-- Select2 -->
<link href="/design/dashboard/lib/select2/dist/css/select2.min.css" rel="stylesheet">
<!-- Switchery -->
<link href="/design/dashboard/lib/switchery/dist/switchery.min.css" rel="stylesheet">
<!-- starrr -->
<link href="/design/dashboard/lib/starrr/dist/starrr.css" rel="stylesheet">
<link rel="stylesheet" href="/design/dashboard/lib/jquery-ui/jquery-ui.css">


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>

<div class="content">
    <?php include VIEW . 'messages.phtml' ?>

    <h2 class="text-center"><i class="fa fa-chalkboard-teacher"></i> Teacher Accounts Add</h2>
    <form action="/admin/universities/addTeacher" method="post" enctype="multipart/form-data">
        <input type="hidden" name="addTeacher" value="true">

        <div class="row">


            <div class="col-md-6">
                <label for="user_email">Email address:</label>
                <input type="email" class="form-control" placeholder="Enter email" id="user_email"
                       value="<?php Helper::old('user_email'); ?>"
                       name="user_email">
                <?php echo Message::getInputErrorMessage('user_email') ?>
                <label for="user_password">Password:</label>

                <input type="password" class="form-control" placeholder="Enter password"
                       id="user_password" name="user_password">
                <?php echo Message::getInputErrorMessage('user_password') ?>


                <label for="user_password">Confirm Password:</label>
                <input type="password" class="form-control" placeholder="Enter password"
                       id="password_confirmation" name="password_confirmation">
                <?php echo Message::getInputErrorMessage('password_confirmation') ?>

                <label for="user_full_name">User Full Name:</label>
                <input type="text" class="form-control" placeholder="Enter User Full Name"
                       value="<?php Helper::old('user_full_name'); ?>"
                       id="user_full_name" name="user_full_name">
                <?php echo Message::getInputErrorMessage('user_full_name') ?>
                <label for="user_name">User Name:</label>
                <input type="text" class="form-control" placeholder="Enter User Name" id="user_name"
                       value="<?php Helper::old('user_name'); ?>"
                       name="user_name">
                <?php echo Message::getInputErrorMessage('user_name') ?>

            </div>

            <div class="col-md-6">
                <label for="user_image">User Image:</label>
                <div class="custom-file">

                    <input type="file" class="custom-file-input" name="user_image" id="user_image">
                    <label class="custom-file-label" for="user_image">Choose file</label>
                </div>
                <div id="user_image_dev">
                    <?php if (array_key_exists('news', $this->view_data)) { ?>
                        <img src="<?php echo($this->view_data['user']['user_image']); ?>"
                             width="100px">

                    <?php } ?>
                </div>
                <label for="user_phone">User Phone:</label>
                <input type="phone" class="form-control" placeholder="Enter User Phone"
                       value="<?php Helper::old('user_phone'); ?>"
                       id="user_phone" name="user_phone">
                <?php echo Message::getInputErrorMessage('user_phone') ?>


                <label for="user_gender">User Gender:</label>

                <select class="form-control" id="user_gender" name="user_gender">
                    <option value="male" selected>Male</option>
                    <option value="female">Female</option>

                </select>

                <div id="student">
                    <label for="user_qualification">User Qualification:</label>
                    <input type="text" class="form-control" placeholder="Enter User Qualification"
                           id="user_qualification"
                           value="<?php Helper::old('user_qualification'); ?>"
                           name="user_qualification">
                    <?php echo Message::getInputErrorMessage('user_qualification') ?>

                </div>


            </div>
            <br>
            <div class="col-md-12">
                <br> <input type="submit" class="btn btn-primary btn-block" name="submit">
            </div>
        </div>

    </form>


</div>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.php' ?>
<script src="/design/dashboard/lib/jquery.tagsinput/src/jquery.tagsinput.js"></script>
<!-- Switchery -->
<script src="/design/dashboard/lib/switchery/dist/switchery.min.js"></script>
<!-- Select2 -->
<script src="/design/dashboard/lib/select2/dist/js/select2.full.min.js"></script>
<!-- Parsley -->
<script src="/design/dashboard/lib/parsleyjs/dist/parsley.min.js"></script>
<script src="/design/dashboard/lib/parsleyjs/dist/i18n/ar.js"></script>
<!-- Autosize -->
<script src="/design/dashboard/lib/autosize/dist/autosize.min.js"></script>
<!-- jQuery autocomplete -->
<script src="/design/dashboard/lib/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
<!-- starrr -->
<script src="/design/dashboard/lib/starrr/dist/starrr.js"></script>

<script src="/design/dashboard/lib/jquery-ui/jquery-ui.js"></script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'readImageFile.phtml' ?>

<script>
    readFile('#user_image', '#user_image_dev');


    $(function () {
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2').select2()
    })
</script>
<script>

</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>
