<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableCss.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<div class="content">
    <?php include VIEW . 'messages.phtml' ?>
    <h2 class="text-center"><i class="fa fa-list"></i> Teachers Manage</h2>
    <div class="row fa-pull-right">
        <div class="col-8">
            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                        id="dashboard_daterangepicker">
                    <i class="	fas fa-bullseye"></i> sorting data by
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Day</a>
                    <a class="dropdown-item" href="#">Week</a>
                    <a class="dropdown-item" href="#">Month</a>
                    <a class="dropdown-item" href="#">Range</a>
                </div>
            </div>
        </div>
    </div>

    <div class="col-4"><a href="/admin/teachers/create" class="btn btn-success "><i class="fa fa-plus"> </i> Add</a>
    </div>
    <table id="example1" class="table table-bordered table-striped">
        <thead class="thead-dark font-size-18">
        <tr>
            <th> Name</th>
            <th>Email</th>
            <th>User Display Name</th>
            <th>User Image</th>
            <th>User Phone</th>
            <th>Registration Date</th>
            <th> Status</th>
            <th>update</th>
            <th>delete</th>


        </tr>
        </thead>

        <tbody>
        <?php if (array_key_exists('teachers', $this->view_data)) {
            foreach ($this->view_data['teachers'] as $teacher) { ?>

                <tr>
                    <td><?php echo $teacher['user_name'] ?></td>
                    <td><?php echo $teacher['user_email'] ?></td>
                    <td><?php echo $teacher['user_full_name'] ?></td>
                    <td><?php echo $teacher['user_image'] ?></td>
                    <td><?php echo $teacher['user_phone'] ?></td>
                    <td><?php echo $teacher['user_register_date'] ?></td>
                    <td>
                        <button data-id="<?php echo $teacher['user_id'] ?>"
                                data-status="<?php echo $teacher['user_status'] ?>"
                                class="btn btn-success active"><?php echo ($teacher['user_status'] == '1') ?  '<i class=\'fas fa-check\'></i>' :'<i class=\'ion ion-close\'></i>'  ?> </button>
                    </td>


                    <?php if ($this->view_data['deleted'] == false) { ?>
                        <td><a href="Categories.php?do=edit" class="btn btn-success"><i class="fa fa-edit"></i></a></td>

                        <td>
                            <a href="/admin/universities/delete/<?php echo $teacher['id'] ?>"
                               onclick="return confirm('هل أنت متأكد من الحذف');" class="btn btn-danger"><i
                                        class="fa fa-trash"></i></a>

                        </td>
                    <?php } else { ?>
                        <th>{{getUserName( $teacher['deleted_by'] )?></th>
                        <td><?php echo $teacher['deleted_at'] ?></td>


                        <td class="text-center">
                            <a href="{{  route('admin.universities.restore',encrypt( $teacher['']id)) }}"
                               class="btn btn-primary"><i
                                        class="fa fa-arrow-up"></i></a>
                        </td>

                    <?php } ?>


                </tr>
            <?php }
        } ?>
    </table>
</div>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.php' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableJs.phtml' ?>
<script>


    $(function () {
        $('#example1').DataTable({
            language: {url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Arabic.json"},
            dom: "Blfrtip",
            buttons: [{extend: "copy", text: "نسخ", className: "btn-sm"}, {
                extend: "csv",
                text: "ملف CSV",
                className: "btn-sm"
            }, {extend: "excel", text: "اکسل", className: "btn-sm"}, {
                extend: "pdfHtml5",
                text: "ملف PDF",
                className: "btn-sm"
            }, {extend: "print", text: "طباعة", className: "btn-sm"}],
            responsive: !0
        });
    });
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>




