<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>

<!-- Select2 -->
<link href="/design/dashboard/lib/select2/dist/css/select2.min.css" rel="stylesheet">
<!-- Switchery -->

<link rel="stylesheet" href="/design/dashboard/lib/jquery-ui/jquery-ui.css">


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<div class="container">
    <?php include VIEW . 'messages.phtml';
    ?>
    <div class="row bg-white mb-4 ">
        <div class="text-right  mt-auto col-6">
            <h3 ><i class="fa  fa-book" style="color:#b23e4a"></i>        إضافة كورس

            </h3>
        </div>
    </div>

    <form action="/admin/courses/store" method="post" enctype="multipart/form-data">

        <div class="form-group">
            <label for="course_title"> الاستاذ:</label>
            <select class="form-control"  name="course_owner" id="">
                <?php if (array_key_exists('teachers', $this->view_data)) {
                    foreach ($this->view_data['teachers'] as $k => $teacher) { ?>
                        <option  value="<?php echo $teacher['user_id'] ?>" > <?php echo $teacher['user_full_name'] ?>   </option>
                    <?php }
                } ?>
            </select>
            <?php echo Message::getInputErrorMessage('course_title') ?>
        </div>

        <div class="form-group">
            <label for="course_title">عنوان الكورس:</label>
            <input type="text"
                   value="<?php Helper::old('course_title'); ?>"
                   class="form-control" id="course_title" placeholder="عنوان الكورس" name="course_title">
            <?php echo Message::getInputErrorMessage('course_title') ?>
        </div>


        <div class="form-group">
            <label for="course_description">وصف الكورس:</label>
            <textarea class="form-control" placeholder="أهداف الكورس"
                      value="<?php Helper::old('course_description'); ?>"
                      id="course_description" name="course_description">
                </textarea>
            <?php echo Message::getInputErrorMessage('course_description') ?>
        </div>

        <div class="form-group">
            <label for="courses_image">صورة الكورس:</label>
            <div class="custom-file">

                <input type="file" class="custom-file-input" name="courses_image" id="courses_image">
                <label class="custom-file-label" for="courses_image">Choose file</label>
                <?php echo Message::getInputErrorMessage('courses_image') ?>
                <div id="courses_image_dev"></div>
            </div>
        </div>
        <div class="form-group">
            <label for="course_price">سعر الكورس:</label>
            <input type="number"
                   value="<?php Helper::old('course_price'); ?>"
                   class="form-control" id="course_price" placeholder="سعر الكورس" name="course_price">
            <?php echo Message::getInputErrorMessage('course_price') ?>
        </div>
        <div class="form-group">
            <label for="course_price">سعر الكورس بعد التحفيض :</label>
            <input type="number" placeholder="سعر الكورس بعد التحفيض"
                   value="<?php Helper::old('course_price_afterDiscount'); ?>"
                   class="form-control" id="course_price_afterDiscount" name="course_price_afterDiscount">
            <?php echo Message::getInputErrorMessage('course_price_afterDiscount') ?>
        </div>
        <div class="form-group">
            <label for="categories_input">الاصناف :</label>
            <input type="text"
                   value=""
                   class="form-control" id="categories_input" name="categories">
            <div id="categories_ids" class="well well-sm"
                 style="height: 50px; overflow: auto;">
                <?php if ((Helper::old('categories_ids') != '')) {
                    foreach (Helper::old('categories_ids') as $id) { ?>
                        <div id="categories_ids<?php echo $id ?>">
                            <svg class="svg-inline--fa fa-minus-circle fa-w-16" aria-hidden="true" focusable="false"
                                 data-prefix="fa" data-icon="minus-circle" role="img" xmlns="http://www.w3.org/2000/svg"
                                 viewBox="0 0 512 512" data-fa-i2svg="">
                                <path fill="currentColor"
                                      d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zM124 296c-6.6 0-12-5.4-12-12v-56c0-6.6 5.4-12 12-12h264c6.6 0 12 5.4 12 12v56c0 6.6-5.4 12-12 12H124z"></path>
                            </svg><!-- <i class="fa fa-minus-circle"></i> --> <?php echo Helper::getCategoryName($id) ?>
                            <input type="hidden"
                                   name="categories_ids[]"
                                   value="<?php echo $id ?>">
                        </div>
                    <?php }
                } ?>

            </div>

            <?php echo Message::getInputErrorMessage('categories_ids') ?>
        </div>

        <div class="form-group">
            <label for="course_requirements">متطلبات الكورس:</label>
            <textarea id="course_requirements" placeholder="متطلبات الكورس"
                      value="<?php Helper::old('course_requirements'); ?>"
                      name="course_requirements">
                    </textarea>
            <?php echo Message::getInputErrorMessage('course_requirements') ?>
        </div>
        <div class="form-group">
            <label for="course_students_target">الطلاب المستهدفين:</label>
            <textarea class="form-control" placeholder="الطلاب المستهدفين"
                      value="<?php Helper::old('course_students_target'); ?>"
                      id="course_students_target" name="course_students_target">
                </textarea>
            <?php echo Message::getInputErrorMessage('course_students_target') ?>
        </div>


        <div class="form-group">
            <label for="course_goals">أهداف الكورس:</label>
            <textarea class="form-control" placeholder="أهداف الكورس"
                      value="<?php Helper::old('course_goals'); ?>"
                      id="course_goals" name="course_goals">
                </textarea>
            <?php echo Message::getInputErrorMessage('course_goals') ?>
        </div>


        <button type="submit" name="submit" class="btn btn-success btn-block">إضافة </button>
    </form>
    <br>



<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<script src="/design/dashboard/lib/jquery.tagsinput/src/jquery.tagsinput.js"></script>
<!-- Switchery -->
<!-- Select2 -->
<script src="/design/dashboard/lib/select2/dist/js/select2.full.min.js"></script>
<!-- Parsley -->
<script src="/design/dashboard/lib/parsleyjs/dist/parsley.min.js"></script>
<script src="/design/dashboard/lib/parsleyjs/dist/i18n/ar.js"></script>
<!-- Autosize -->
<!-- jQuery autocomplete -->
<script src="/design/dashboard/lib/jquery-ui/jquery-ui.js"></script>

<script>


    $(function () {
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2').select2()
    })
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'readImageFile.phtml' ?>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'autocomplate.phtml' ?>


<script>

    autoComplate('categories', 'categories_ids[]', 'categories_ids', '/admin/categories/fetchCategory', 'name', true);
    readFile('#courses_image', '#courses_image_dev');

    fetchCategories('#main_category_parents', '#sub_category');
    fetchCategories('#sub_category', '#sub_sub_category');

    function fetchCategories(input, select) {

        $(document).on('change', input, function () {
            var data = 'category_parents=' + encodeURIComponent($(this).val());
            var url = '/admin/Categories/fetchSubCategories';
            $.ajax({
                url: url,//   var url=$('#news').attr('action');
                method: 'POST',
                dataType: 'json',// data type that i want to return
                data: data,// var form=$('#news').serialize();
                success: function (data) {
                    $(select).html(data);

                }, error:
                    function (xhr, status, error) {
                        $(select).html(xhr.responseText);
                    }
            });
            return (false);
        });
    }


    CKEDITOR.replace('editor', {filebrowserImageBrowseUrl: '/file-manager/ckeditor'});
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>

