<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>

<!-- Select2 -->
<link href="/design/dashboard/lib/select2/dist/css/select2.min.css" rel="stylesheet">
<!-- Switchery -->

<link rel="stylesheet" href="/design/dashboard/lib/jquery-ui/jquery-ui.css">


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<div class="content">
    <?php include VIEW . 'messages.phtml';
    ?>
    <h2 class="text-center"><i class="fa  fa-list"></i> Categories Add</h2>
    <form action="/admin/courses/store" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label for="course_title">Course Title:</label>
            <input type="text"
                   value="<?php Helper::old('course_title'); ?>"
                   class="form-control" id="course_title" name="course_title">
            <?php echo Message::getInputErrorMessage('course_title') ?>
        </div>
        <div class="form-group">
            <label for="course_description">Course Description:</label>
            <input type="text" class="form-control"
                   value="<?php Helper::old('course_description'); ?>"
                   id="course_description" name="course_description">
            <?php echo Message::getInputErrorMessage('course_description') ?>
        </div>

        <div class="form-group">
            <label for="courses_image">Course Imagefdd:</label>
            <div class="custom-file">

                <input type="file" class="custom-file-input" name="courses_image" id="courses_image">
                <label class="custom-file-label" for="courses_image">Choose file</label>
                <?php echo Message::getInputErrorMessage('courses_image') ?>
                <div id="courses_image_dev"></div>
            </div>
        </div>
        <div class="form-group">
            <label for="course_price">Course Price:</label>
            <input type="number"
                   value="<?php Helper::old('course_price'); ?>"
                   class="form-control" id="course_price" name="course_price">
            <?php echo Message::getInputErrorMessage('course_price') ?>
        </div>
        <div class="form-group">
            <label for="course_price">course price after Discount :</label>
            <input type="number"
                   value="<?php Helper::old('course_price_afterDiscount'); ?>"
                   class="form-control" id="course_price_afterDiscount" name="course_price_afterDiscount">
            <?php echo Message::getInputErrorMessage('course_price_afterDiscount') ?>
        </div>
        <div class="form-group">
            <label for="categories_input">categories :</label>
            <input type="text"
                   value="<?php Helper::old('categories_ids'); ?>"
                   class="form-control" id="categories_input" name="categories">
            <div id="categories_ids" class="well well-sm"
                 style="height: 50px; overflow: auto;">
            </div>
            <?php echo Message::getInputErrorMessage('categories_ids') ?>
        </div>

        <div class="form-group">
            <label for="course_requirements">Course Requirements:</label>
            <textarea id="course_requirements"
                      value="<?php Helper::old('course_requirements'); ?>"
                      name="course_requirements">
                    </textarea>
            <?php echo Message::getInputErrorMessage('course_requirements') ?>
        </div>
        <div class="form-group">
            <label for="course_students_target">Student Target:</label>
            <textarea class="form-control"
                      value="<?php Helper::old('course_students_target'); ?>"
                      id="course_students_target" name="course_students_target">
                </textarea>
            <?php echo Message::getInputErrorMessage('course_students_target') ?>
        </div>


        <div class="form-group">
            <label for="course_goals">Course Goals:</label>
            <textarea class="form-control"
                      value="<?php Helper::old('course_goals'); ?>"
                      id="course_goals" name="course_goals">
                </textarea>
            <?php echo Message::getInputErrorMessage('course_goals') ?>
        </div>


        <button type="submit" name="submit" class="btn btn-primary btn-block">Save</button>
    </form>
    <br>

</div>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.php' ?>
<script src="/design/dashboard/lib/jquery.tagsinput/src/jquery.tagsinput.js"></script>
<!-- Switchery -->
<!-- Select2 -->
<script src="/design/dashboard/lib/select2/dist/js/select2.full.min.js"></script>
<!-- Parsley -->
<script src="/design/dashboard/lib/parsleyjs/dist/parsley.min.js"></script>
<script src="/design/dashboard/lib/parsleyjs/dist/i18n/ar.js"></script>
<!-- Autosize -->
<!-- jQuery autocomplete -->
<script src="/design/dashboard/lib/jquery-ui/jquery-ui.js"></script>

<script>


    $(function () {
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2').select2()
    })
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'readImageFile.phtml' ?>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'autocomplate.phtml' ?>


<script>

    autoComplate('categories', 'categories_ids[]', 'categories_ids', '/admin/categories/fetchCategory', 'name', true);
    readFile('#courses_image', '#courses_image_dev');

    fetchCategories('#main_category_parents', '#sub_category');
    fetchCategories('#sub_category', '#sub_sub_category');

    function fetchCategories(input, select) {

        $(document).on('change', input, function () {
            var data = 'category_parents=' + encodeURIComponent($(this).val());
            var url = '/admin/Categories/fetchSubCategories';
            $.ajax({
                url: url,//   var url=$('#news').attr('action');
                method: 'POST',
                dataType: 'json',// data type that i want to return
                data: data,// var form=$('#news').serialize();
                success: function (data) {
                    $(select).html(data);

                }, error:
                    function (xhr, status, error) {
                        $(select).html(xhr.responseText);
                    }
            });
            return (false);
        });
    }


    CKEDITOR.replace('editor', {filebrowserImageBrowseUrl: '/file-manager/ckeditor'});
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>

