<?php use auth\Permissions;

include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableCss.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<div class="content">
    <?php include VIEW . 'messages.phtml' ?>
    <div class="row bg-white mb-4 ">
        <div class="text-right mt-auto col-6">
            <h3><i class="fa fa-book-open" style="color:#ec3901"></i>ادارة الكورسات </h3>
        </div>
    </div>
    <div class="row mb-4">
        <div class="col-6 text-right">
            <?php if (Permissions::getInstaince()->hasPermision('course_create') == true) { ?>
                <a href="/admin/courses/create" class="btn btn-success "><i class="fa fa-plus"> </i> اضافة كورس جديد</a>
                </a>
            <?php } ?>
        </div>
        <div class="col-6 text-left">
            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                        id="dashboard_daterangepicker">
                    <i class="	fas fa-bullseye"></i> sorting data by
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Day</a>
                    <a class="dropdown-item" href="#">Week</a>
                    <a class="dropdown-item" href="#">Month</a>
                    <a class="dropdown-item" href="#">Range</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table id="example1" class="table table-bordered table-striped">
                <thead class="thead-dark font-size-10">
                <tr>
                    <th>#الرقم</th>
                    <th>عنوان الكورس</th>
                    <th>صورة الكورس</th>
                    <th>سعر الكورس</th>
                    <th> السعر بعد التحفيض</th>
                    <th>اسم القسم</th>
                    <th>حالة الكورس</th>
                    <th>الدروس</th>
                    <th>إظهار الكورس</th>
                    <?php if (Permissions::getInstaince()->hasPermision('course_edit') == true
                        or Permissions::getInstaince()->hasPermision('course_delete') == true) { ?>
                        <th>الاعدادات</th>
                    <?php } ?>

                </tr>
                </thead>
                <tbody>

                <?php if (array_key_exists('courses', $this->view_data)) {
                    foreach ($this->view_data['courses'] as $k => $course) {
//                        echo "<pre>";
//                        var_dump($this->view_data['courses'][0]['course_id']);
//                        echo "</pre>";
                        ?>
                        <tr>
                            <td><?php echo $course['course_id'] ?></td>
                            <td><?php echo $course['course_title'] ?></td>
                            <td><img src="<?php echo $course['courses_image'] ?>" width="100px"></td>
                            <td><?php echo '$' . $course['course_price'] ?></td>
                            <td><?php echo '$' . $course['course_price_afterDiscount'] ?></td>
                            <td><?php echo Helper::Names($course['categories_ids'], 'Category') ?></td>
                            <td>
                                <button data-id="<?php echo $course['course_id'] ?>"
                                        data-status="<?php echo $course['course_status'] ?>"
                                        class="btn btn-success active">
                                    <?php echo ($course['course_status'] == '1') ? '<i class="fas fa-check"></i>' : '<i class="ion ion-close"></i>' ?>
                                </button>
                            </td>
                            <td><a href="/admin/lessons/index/<?php echo $course['course_id'] ?>"
                                   class="btn btn-info"><i
                                            class="fa fa-eye"></i></a></td>
                            <td>
                                <button data-id="<?php echo $course['course_id'] ?>"
                                        data-visibility="<?php echo $course['course_visibility'] ?>"
                                        class="btn btn-success btn_visibility"><?php echo ($course['course_visibility'] == '1') ? ' <i class="fa fa-eye"> </i>' : '  <i class="fa fa-eye-slash"> </i>' ?> </button>
                            </td>

                            <?php if ($this->view_data['deleted'] == false) { ?>
                                <?php if (Permissions::getInstaince()->hasPermision('course_edit') == true
                                    or Permissions::getInstaince()->hasPermision('course_delete') == true
                                ) { ?>
                                    <td>
                                        <?php if (Permissions::getInstaince()->hasPermision('course_edit') == true) { ?>
                                            <a href="Categories.php?do=edit" class="btn btn-success"><i
                                                        class="fa fa-edit"></i></a>
                                        <?php } ?>
                                        <?php if (Permissions::getInstaince()->hasPermision('course_delete') == true) { ?>

                                            <a href="/admin/universities/delete/<?php echo $course['id'] ?>"
                                               onclick="return confirm('هل أنت متأكد من الحذف');"
                                               class="btn btn-danger"><i
                                                        class="fa fa-trash"></i></a>
                                        <?php } ?>
                                    </td>
                                <?php } ?>
                            <?php } else { ?>
                                <td><?php echo $course['deleted_at'] ?></td>

                            <?php } ?>
                        </tr>
                    <?php }
                } ?>
                <tbody>
            </table>


            </tr>
            >
            </table>
        </div>

        <?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
        <?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableJs.phtml' ?>
        <?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'active.phtml' ?>
        <?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'visibility.phtml' ?>


        <script>
            Active('courses');
            Visible('courses');

            $(function () {
                $('#example1').DataTable({
                    language: {url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Arabic.json"},
                    dom: "Blfrtip",
                    buttons: [{extend: "copy", text: "نسخ", className: "btn-sm"}, {
                        extend: "csv",
                        text: "ملف CSV",
                        className: "btn-sm"
                    }, {extend: "excel", text: "اکسل", className: "btn-sm"}, {
                        extend: "pdfHtml5",
                        text: "ملف PDF",
                        className: "btn-sm"
                    }, {extend: "print", text: "طباعة", className: "btn-sm"}],
                    responsive: !0
                });
            });
        </script>
        <?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>
