<?php use auth\Permissions;

include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableCss.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>

<div class="container">
    <div class="row bg-white mb-4 ">
        <div class="text-right  mt-auto col-6">
            <h2><i class="fa fa fa-cogs" style="color:#ec3901"></i> إدارة الصلاحيات</h2>
        </div>
    </div>
    <div class="row mb-4">
        <div class="col-6 text-right">
            <?php if (Permissions::getInstaince()->hasPermision('permission_create') == true) { ?>
                <a href="/admin/permision/create" class="btn btn-success "><i class="fa fa-plus"> </i> إصافة صلاحية
                    جديدة</a>
            <?php } ?>
        </div>
        <div class="col-6 text-left">

            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                        id="dashboard_daterangepicker">
                    <i class="	fas fa-bullseye"></i>ترتيب حسب
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">اليوم</a>
                    <a class="dropdown-item" href="#">الاسبوع</a>
                    <a class="dropdown-item" href="#">الشهر</a>
                    <a class="dropdown-item" href="#">المدة</a>
                </div>
            </div>

        </div>
    </div>
    <div class="row ">
        <div class="col-12 ">
            <table id="example1" class="table table-bordered table-striped">
                <thead class="thead-dark font-size-18">
                <tr>
                    <th>اسم الصلاحية</th>
                    <th>وصف الصلاحية</th>

                    <?php if (Permissions::getInstaince()->hasPermision('permission_edit') == true
                        or Permissions::getInstaince()->hasPermision('permission_delete') == true) { ?>
                        <th>الاعدادات</th>
                    <?php } ?>

                </tr>
                </thead>

                <tbody>
                <?php if (array_key_exists('permision', $this->view_data)) {
                    foreach ($this->view_data['permision'] as $role) { ?>


                        <tr>
                            <td><?php echo $role['permission_name'] ?></td>
                            <td><?php echo $role['permissions_description'] ?></td>


                            <?php if ($this->view_data['deleted'] == false) { ?>
                                <?php if (Permissions::getInstaince()->hasPermision('permission_edit') == true
                                    or Permissions::getInstaince()->hasPermision('permission_delete') == true
                                ) { ?>
                                    <td>
                                        <?php if (Permissions::getInstaince()->hasPermision('permission_edit') == true) { ?>
                                            <a class="active" data-id="<?php echo $role['permission_id'] ?>"
                                               href="" data-status="<?php echo $role['permission_status'] ?>"
                                            ><?php echo ($role['permission_status'] == '1') ? '<i class=\'fas fa-check text-primary\'></i>' : '<i class=\'ion ion-close text-danger\'></i>' ?> </a>

                                            <a href="/admin/permision/edit/<?php echo $role['permission_id'] ?>"><i
                                                        class="fa fa-edit"></i></a>
                                        <?php } ?>
                                        <?php if (Permissions::getInstaince()->hasPermision('permission_delete') == true) { ?>

                                            <a href="/admin/permision/delete/<?php echo $role['permission_id'] ?>"
                                               onclick="return confirm('هل أنت متأكد من الحذف');"><i
                                                        class="fa fa-trash-restore"></i></a>
                                        <?php } ?>
                                    </td>
                                <?php } ?>
                            <?php } else { ?>

                                <th>{{getUserName( $role['deleted_by'] )?></th>
                                <td><?php echo $role['deleted_at'] ?></td>


                                <td class="text-center">
                                    <a href="{{  route('admin.universities.restore',encrypt( $role['']id)) }}"
                                       class="btn btn-primary"><i
                                                class="fa fa-arrow-up"></i></a>
                                </td>

                            <?php } ?>


                        </tr>
                    <?php }
                } ?>
            </table>
        </div>
    </div>



<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableJs.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'active.phtml' ?>

<script>
    $(document).on('click', '.btn_visibility', function () {
        var data = 'visibility=' + encodeURIComponent($(this).attr('data-visibility')) + '&data_id=' + encodeURIComponent($(this).attr('data-id'));
        var url = '/admin/categories/visibility';
        var _this = $(this);
        $.ajax({
            url: url,//   var url=$('#news').attr('action');
            method: 'POST',
            dataType: 'json',// data type that i want to return
            data: data,// var form=$('#news').serialize();
            success: function (data) {
                if (data == 1) {
                    _this.html("<i class=\"fa fa-eye\"> </i>");
                    _this.attr("data-visibility", data);
                } else {
                    _this.html("<i class=\"fa fa-eye-slash\"> </i>");
                    _this.attr("data-visibility", data);
                }
            },
            error: function (xhr, status, error) {
                alert(xhr.responseText);
            }
        });
        return (false);
    });
    Active('Permision');
    $(function () {
        $('#example1').DataTable({
            language: {url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Arabic.json"},
            dom: "Blfrtip",
            buttons: [{extend: "copy", text: "copy", className: "btn-sm"}, {
                extend: "csv",
                text: " CSV",
                className: "btn-sm"
            }, {extend: "excel", text: "excel", className: "btn-sm"}, {
                extend: "pdfHtml5",
                text: " PDF",
                className: "btn-sm"
            }, {extend: "print", text: "print", className: "btn-sm"}],
            responsive: !1
        });
    });
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>




