<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>
<!-- Select2 -->
<link href="/design/dashboard/lib/select2/dist/css/select2.min.css" rel="stylesheet">
<!-- Switchery -->
<link rel="stylesheet" href="/design/dashboard/lib/jquery-ui/jquery-ui.css">
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<div class="content">
    <?php include VIEW . 'messages.phtml';
    //    resources_video	resources_file	resources_chapter	course_id	resources_date	resources_status	resources_updates?>
    <h2 class="text-center"><i class="fa  fa-list"></i> Lesson Add</h2>


    <div id="video_details">
        <form id="upload_form" enctype="multipart/form-data" method="post">
            <input type="file" name="file1" id="file1"><br>
            <input type="button" value="Upload File" onclick="uploadFile()">
            <progress id="progressBar" value="0" max="100" style="width:300px;"></progress>
            <h3 id="status"></h3>
            <p id="loaded_n_total"></p>
        </form>
    </div>
    <div id="lesson_details">
        <form action="/admin/lessons/store" id="form_lesson_details" method="post" enctype="multipart/form-data">
            <input type="hidden" name="course_id" value="<?php echo $this->view_data['course_id'] ?>">
            <div id="video_info">
            </div>
            <div class="form-group">
                <label for="chapter">Chapter name :</label>
                <input type="text"
                       value=""
                       class="form-control" id="chapter" name="resources_chapter">
                <div id="categories_ids" class="well well-sm"
                     style="height: 50px; overflow: auto;">
                    <?php if ((Helper::old('resources_chapter') != '')) {
                        ?>
                        <div id="chapter<?php echo Helper::old('resources_chapter') ?>">
                            <svg class="svg-inline--fa fa-minus-circle fa-w-16" aria-hidden="true" focusable="false"
                                 data-prefix="fa" data-icon="minus-circle" role="img"
                                 xmlns="http://www.w3.org/2000/svg"
                                 viewBox="0 0 512 512" data-fa-i2svg="">
                                <path fill="currentColor"
                                      d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zM124 296c-6.6 0-12-5.4-12-12v-56c0-6.6 5.4-12 12-12h264c6.6 0 12 5.4 12 12v56c0 6.6-5.4 12-12 12H124z"></path>
                            </svg>
                            <!-- <i class="fa fa-minus-circle"></i> --> <?php echo Helper::old('resources_chapter') ?>
                            <input type="hidden"
                                   name="resources_chapter"
                                   value="<?php  Helper::old('resources_chapter') ?>">
                        </div>
                    <?php }
                    ?>

                </div>

                <?php echo Message::getInputErrorMessage('categories_ids') ?>
            </div>
            <button type="submit" name="submit" class="btn btn-primary btn-block">Save</button>
        </form>

    </div>
    <br>

</div>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<script src="/design/dashboard/lib/jquery.tagsinput/src/jquery.tagsinput.js"></script>
<!-- Switchery -->
<!-- Select2 -->
<script src="/design/dashboard/lib/select2/dist/js/select2.full.min.js"></script>
<!-- Parsley -->
<script src="/design/dashboard/lib/parsleyjs/dist/parsley.min.js"></script>
<script src="/design/dashboard/lib/parsleyjs/dist/i18n/ar.js"></script>
<!-- Autosize -->
<!-- jQuery autocomplete -->
<script src="/design/dashboard/lib/jquery-ui/jquery-ui.js"></script>

<script>


    $(function () {
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2').select2()
    })
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'readImageFile.phtml' ?>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'autocomplate.phtml' ?>

<script>
    function _(el) {
        return document.getElementById(el);
    }

    function uploadFile() {
        var file = _("file1").files[0];
        if (typeof file === "undefined") {

            _("status").innerHTML = "ERROR: Please browse for a file before clicking the upload button";
            _("progressBar").value = 0;

        } else {
            $.get('/admin/lessons/saveVideo/getsize', function (sizelimit) {
                if (sizelimit > file.size) {

                    var formdata = new FormData();
                    formdata.append("file1", file);
                    formdata.append("size", file.size);
                    var ajax = new XMLHttpRequest();
                    ajax.upload.addEventListener("progress", progressHandler, false);
                    ajax.addEventListener("load", completeHandler, false);
                    ajax.addEventListener("error", errorHandler, false);
                    ajax.addEventListener("abort", abortHandler, false);
                    ajax.open("POST", "/admin/lessons/saveVideo");
                    ajax.send(formdata);
                } else {
                    var sizewarn = "ERROR: The File is too big! The maximum file size is ";
                    sizewarn += sizelimit / (1024 * 1024);
                    sizewarn += "MB";
                    _("status").innerHTML = sizewarn;
                    _("progressBar").value = 0;

                }
            });
        }
    }

    function progressHandler(event) {
        _("loaded_n_total").innerHTML = "Uploaded " + event.loaded + " bytes of " + event.total;
        var percent = (event.loaded / event.total) * 100;
        _("progressBar").value = Math.round(percent);
        _("status").innerHTML = Math.round(percent) + "% uploaded... please wait";
    }

    function completeHandler(event) {
        _("status").innerHTML = event.target.responseText;
        $('#video_info').html('<input type="text"  name="resources_video" value="' + event.target.responseText + '"> ')
        _("progressBar").value = 0;
    }

    function errorHandler(event) {
        _("status").innerHTML = "Upload Failed";
    }

    function abortHandler(event) {
        _("status").innerHTML = "Upload Aborted";
    }
</script>
<script>
    autoComplate('chapter', 'resources_chapter', 'chapter', '/admin/lessons/fetchChapter', 'name', false);
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>

