<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>
<!-- Select2 -->
<link href="/design/dashboard/lib/select2/dist/css/select2.min.css" rel="stylesheet">
<!-- Switchery -->
<link rel="stylesheet" href="/design/dashboard/lib/jquery-ui/jquery-ui.css">
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<div class="content">
    <?php include VIEW . 'messages.phtml';
    //    resources_video	resources_file	resources_chapter	course_id	resources_date	resources_status	resources_updates?>
    <h2 class="text-center"><i class="fa  fa-book-open"></i> إضافة درس</h2>


    <div id="video_details">
        <form id="upload_form" enctype="multipart/form-data" method="post">
            <input type="file" name="file1" id="file1"><br>
            <input type="button" value="Upload File" onclick="uploadFile()">
            <progress id="progressBar" value="0" max="100" style="width:300px;"></progress>
            <h3 id="status"></h3>
            <p id="loaded_n_total"></p>
        </form>
    </div>
    <div id="lesson_details">
        <form action="/admin/lessons/store" id="form_lesson_details" method="post" enctype="multipart/form-data">
            <input type="hidden" name="course_id" value="<?php echo $this->view_data['course_id'] ?>">
            <input type="hidden" name="resources_video" value="<?php Helper::old('resources_video') ?>">
            <?php echo Message::getInputErrorMessage('resources_video') ?>
            <div id="video_info">
            </div>
            <div class="form-group">
                <label for="chapter">اسم الشباتر :</label>
                <input type="text"
                       value="" placeholder="اسم الشباتر"
                       class="form-control" id="chapter" name="resources_chapter">
                <div id="categories_ids" class="well well-sm"
                     style="height: 50px; overflow: auto;">
                    <?php echo Message::getInputErrorMessage('resources_chapter') ?>


                </div>

                <?php echo Message::getInputErrorMessage('categories_ids') ?>
            </div>
            <button type="submit" name="submit" class="btn btn-primary btn-block">إرسال الاستعلام</button>
        </form>

    </div>
    <br>

</div>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<script src="/design/dashboard/lib/jquery.tagsinput/src/jquery.tagsinput.js"></script>
<!-- Switchery -->
<!-- Select2 -->
<script src="/design/dashboard/lib/select2/dist/js/select2.full.min.js"></script>
<!-- Parsley -->
<script src="/design/dashboard/lib/parsleyjs/dist/parsley.min.js"></script>
<script src="/design/dashboard/lib/parsleyjs/dist/i18n/ar.js"></script>
<!-- Autosize -->
<!-- jQuery autocomplete -->
<script src="/design/dashboard/lib/jquery-ui/jquery-ui.js"></script>

<script>


    $(function () {
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2').select2()
    })
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'readImageFile.phtml' ?>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'autocomplate.phtml' ?>

<script>
    function _(el) {
        return document.getElementById(el);
    }

    function uploadFile() {
        var file = _("file1").files[0];
        if (typeof file === "undefined") {

            _("status").innerHTML = "خطا :يرجى اختيار ملف اولا قبل الرفع";
            _("progressBar").value = 0;

        } else {
            $.get('/admin/lessons/saveVideo/getsize', function (sizelimit) {
                if (sizelimit > file.size) {

                    var formdata = new FormData();
                    formdata.append("file1", file);
                    formdata.append("size", file.size);
                    var ajax = new XMLHttpRequest();
                    ajax.upload.addEventListener("progress", progressHandler, false);
                    ajax.addEventListener("load", completeHandler, false);
                    ajax.addEventListener("error", errorHandler, false);
                    ajax.addEventListener("abort", abortHandler, false);
                    ajax.open("POST", "/admin/lessons/saveVideo");
                    ajax.send(formdata);
                } else {
                    var sizewarn = "عفوا : حجم الملف كبير جدا ! اقصى حجم لرفع الملفات هو  ";
                    sizewarn += sizelimit / (1024 * 1024);
                    sizewarn += "MB";
                    _("status").innerHTML = sizewarn;
                    _("progressBar").value = 0;

                }
            });
        }
    }

    function progressHandler(event) {
        _("loaded_n_total").innerHTML = "تم تحميل  " + event.loaded + " bytes من اصل  " + event.total;
        var percent = (event.loaded / event.total) * 100;
        _("progressBar").value = Math.round(percent);
        _("status").innerHTML = Math.round(percent) + "% محمل ... يرجى  الانتظار ";
    }

    function completeHandler(event) {
        _("status").innerHTML = event.target.responseText;
        $('#video_info').html('<input type="hidden"  name="resources_video" value="' + event.target.responseText + '"> ')
        _("progressBar").value = 0;
    }

    function errorHandler(event) {
        _("status").innerHTML = "Upload Failed";
    }

    function abortHandler(event) {
        _("status").innerHTML = "Upload Aborted";
    }
</script>
<script>
    autoComplate('resources_chapter', 'resources_chapter11', 'chapter', '/admin/lessons/fetchChapter', 'name', false);
</script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>
