<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>
<style type="text/css">
    div.guide {
        margin: 12px 24px;
    }

    div.guide span {
        color: #ff0000;
        font: italic 14px Arial, Helvetica, sans-serif;
    }

    div.guide p {
        color: #000000;
        font: 14px Arial, Helvetica, sans-serif;
    }

    div.guide pre {
        color: #990000;
    }

    div.guide p.title {
        color: #df501f;
        font: 18px Arial, Helvetica, sans-serif;
    }
</style>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableCss.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<div class="content">
    <?php include VIEW . 'messages.phtml' ?>
    <h2 class="text-center"><i class="fa fa-list"></i> Courses Lessons </h2>
    <div class="row fa-pull-right">
        <div class="col-8">
            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                        id="dashboard_daterangepicker">
                    <i class="	fas fa-bullseye"></i> ترنيب حسب
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">اليوم</a>
                    <a class="dropdown-item" href="#">الاسبوع</a>
                    <a class="dropdown-item" href="#">الشهر</a>
                    <a class="dropdown-item" href="#">الفترة</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-4"><a href="/admin/lessons/create/<?php echo $this->view_data['course_id'] ?>"
                          class="btn btn-primary "><i class="fa fa-plus"> </i> Add</a>
    </div>
    <table id="example1" class="table table-bordered table-striped">
        <thead class="thead-dark font-size-18">
        <tr>
            <td>#</td>
            <td>الشبابتر</td>
            <td>الفيديو</td>
            <td>المدة</td>
            <td>الحجم</td>

            <!--            resources_id-->
            <!--            resources_video-->
            <!--            resources_file-->
            <!--            resources_chapter-->
            <!--            course_id-->
            <!--            resources_date-->

            <th>update</th>
            <th>delete</th>
        </tr>
        </thead>

        <tbody>


        <?php if (array_key_exists('courses', $this->view_data)) {
        foreach ($this->view_data['courses'] as $k => $course) { ?>
        <tr>
            <?php $file = Helper::getVideoDeatils(substr($course['resources_video'], 1)); ?>
            <td><?php echo $k ?></td>
            <td><?php echo $course['resources_chapter'] ?></td>
            <td>
                <div style="display:none;margin:0 auto;" class="html5gallery" data-html5player="true"
                     data-width="480" data-height="272" data-resizemode="fill" data-showsocialmedia="false"
                     data-src="<?php echo $course['resources_video'] ?>"
                     data-webm="<?php echo $course['resources_video'] ?>"
</div>
    </td>
    <td> <?php echo $file['playtime_string'] ?></td>
    <td> <?php echo round($file['filesize'] / 1014 / 1024, 2) . 'MB' ?></td>


<?php if ($this->view_data['deleted'] == false) { ?>
    <td><a href="/admin/lessons/edit/" class="btn btn-success"><i class="fa fa-edit"></i></a>


        <a href="/admin/lessons/delete/<?php echo $course['id'] ?>"
           onclick="return confirm('هل أنت متأكد من الحذف');" class="btn btn-danger"><i
                    class="fa fa-trash"></i></a>

    </td>
<?php } else { ?>

    <td class="text-center">
        <a href=""
           class="btn btn-primary"><i
                    class="fa fa-arrow-up"></i></a>
    </td>

<?php } ?>


    </tr>
<?php }
} ?>
</table>
</div>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableJs.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'active.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'visibility.phtml' ?>


<script>
    Active('courses');
    Visible('courses');

    $(function () {
        $('#example1').DataTable({
            language: {url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Arabic.json"},
            dom: "Blfrtip",
            buttons: [{extend: "copy", text: "نسخ", className: "btn-sm"}, {
                extend: "csv",
                text: "ملف CSV",
                className: "btn-sm"
            }, {extend: "excel", text: "اکسل", className: "btn-sm"}, {
                extend: "pdfHtml5",
                text: "ملف PDF",
                className: "btn-sm"
            }, {extend: "print", text: "طباعة", className: "btn-sm"}],
            responsive: !0
        });
    });
</script>
<script type=”text/javascript” src=”//cdn.jsdelivr.net/afterglow/latest/afterglow.min.js”></script>
<script type="text/javascript" src="/design/dashboard/lib/html5gallery/html5gallery.js"></script>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>




