<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'navbar.php' ?>
<?php //includes VIEW . 'messages.phtml' ?>

<!-- Start Main-content -->
<div class="container ">
    <?php include VIEW . 'messages.phtml' ?>
    <div class="row bg-white mb-4 ">
            <div class="text-right  mt-auto col-6">
                <h3 class=""><i class="fa fa-home" style="color:#b23e4a  "></i>  الصفحة الرئيسية</h3>
            </div>
            <div class="text-left m-auto col-6">
					<span class="subheader_daterange " id="dashboard_daterangepicker">
						<span class="subheader_daterange-label">
							<span class="subheader_daterange-title">Today:</span>
							<span class="subheader_daterange-date text-info">Jan 18</span>
						</span>
                        	<a href="#" class="btn btn-sm btn-info">
							<i class="fa fa-angle-down "></i>
						</a>
					</span>
            </div>
    </div>


    <div class="row">
        <div class="col-xl-4 col-12">
            <div class="card">
<?php
if (array_key_exists('cousres', $this->view_data)) {
foreach ($this->view_data['cousres'] as $cousre) {
    ?>

                <div class="card-body" >

                    <div class="flexcard mt-2">
                        <div class="row">
                            <div class="col-9 text-right">
                                <h6 class="text-uppercase font-size-20 text-dark">عدد الكورسات</h6>
                                <span class=" font-size-20 text-dark">
                                    <?php echo $cousre[0];?></span>
                            </div>
                            <div class="col-3 text-center mt-1">
                                <span class="ion ion-ios-book text-danger font-size-60 "></span>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
        <!-- /.col -->
<?php }}?>
        <div class="col-xl-4 col-12">
            <div class="card">
                <?php
                if (array_key_exists('users', $this->view_data)) {
                foreach ($this->view_data['users'] as $cousre) {
                ?>

                <div class="card-body" >

                    <div class="flexcard mt-2">
                        <div class="row">
                            <div class="col-9 text-right">
                                <h6 class="text-uppercase font-size-20 text-dark">عدد المستخدمين</h6>
                                <span class=" font-size-20 text-dark">
                                    <?php echo $cousre[0];?></span>
                            </div>
                            <div class="col-3 text-center mt-1">
                                <span class="ion ion-ios-person text-primary font-size-60 "></span>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
        <!-- /.col -->
    <?php }}?>
        <!-- /.col -->

        <div class="col-xl-4 col-12">
            <div class="card">
                <?php
                if (array_key_exists('categories', $this->view_data)) {
                foreach ($this->view_data['categories'] as $cousre) {
                ?>

                <div class="card-body" >

                    <div class="flexcard mt-2">
                        <div class="row">
                            <div class="col-9 text-right">
                                <h6 class="text-uppercase font-size-20 text-dark">عدد الاصناف</h6>
                                <span class=" font-size-20 text-dark">
                                    <?php echo $cousre[0];?></span>
                            </div>
                            <div class="col-3 text-center mt-1">
                                <span class="ion ion-android-list text-warning font-size-50 "></span>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
        <!-- /.col -->
    <?php }}?>
        <!-- /.col -->
    </div>
    <div class="row">
<!---->
<!--        <div class="col-xl-8">-->
<!--            <div class="card">-->
<!--                <div class="card-body analytics-info">-->
<!--                    <h4 class="card-title">Stacked Bar Chart</h4>-->
<!--                    <div id="basic-bar" style="height:400px;"></div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!---->
<!--        <div class="col-xl-4 col-lg-3">-->
<!--            <div class="card">-->
<!--                <div class="card-header">-->
<!--                    <h4 class="card-title">إخر الاعضاء المسجلين</h4>-->
<!--                </div>-->
<!--                <div class="card-body px-1">-->
<!--                    <div id="recent-buyers" class="media-list">-->
<!--                        <a href="#" class="media xs-media p-5">-->
<!--                            <div class="media-left pr-1">-->
<!--							  <span class="avatar avatar-lg">-->
<!--								<img class="media-object rounded-circle" src="/image/avatar/1.jpg"-->
<!--                                     alt="Generic placeholder image" width="50">-->
<!--								<i></i>-->
<!--							  </span>-->
<!--                            </div>-->
<!--                            <div class="media-body w-100">-->
<!--                                <h6 class="list-group-item-heading">Kristopher Candy-->
<!--                                    <span class="float-right pt-1">$1,021</span>-->
<!--                                </h6>-->
<!--                                <p class="list-group-item-text mt-5 mb-0">-->
<!--                                    <span class="badge badge-primary">Electronics</span>-->
<!--                                    <span class="badge badge-warning ml-1">Decor</span>-->
<!--                                </p>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                        <a href="#" class="media xs-media p-5">-->
<!--                            <div class="media-left pr-1">-->
<!--							  <span class="avatar avatar-lg">-->
<!--								<img class="media-object rounded-circle" src="/image/avatar/1.jpg"-->
<!--                                     alt="Generic placeholder image" width="50">-->
<!--								<i></i>-->
<!--							  </span>-->
<!--                            </div>-->
<!--                            <div class="media-body w-100">-->
<!--                                <h6 class="list-group-item-heading">Lawrence Fowler-->
<!--                                    <span class="float-right pt-1">$2,021</span>-->
<!--                                </h6>-->
<!--                                <p class="list-group-item-text mt-5 mb-0">-->
<!--                                    <span class="badge badge-danger">Appliances</span>-->
<!--                                </p>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                        <a href="#" class="media xs-media p-5">-->
<!--                            <div class="media-left pr-1">-->
<!--							  <span class="avatar avatar-lg">-->
<!--								<img class="media-object rounded-circle" src="/image/avatar/1.jpg"-->
<!--                                     alt="Generic placeholder image" width="50">-->
<!--								<i></i>-->
<!--							  </span>-->
<!--                            </div>-->
<!--                            <div class="media-body w-100">-->
<!--                                <h6 class="list-group-item-heading">Linda Olson-->
<!--                                    <span class="float-right pt-1">$1,112</span>-->
<!--                                </h6>-->
<!--                                <p class="list-group-item-text mt-5 mb-0">-->
<!--                                    <span class="badge badge-primary">Electronics</span>-->
<!--                                    <span class="badge badge-success ml-1">Office</span>-->
<!--                                </p>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                        <a href="#" class="media xs-media p-5">-->
<!--                            <div class="media-left pr-1">-->
<!--							  <span class="avatar avatar-lg">-->
<!--								<img class="media-object rounded-circle" src="/image/avatar/1.jpg"-->
<!--                                     alt="Generic placeholder image" width="50">-->
<!--								<i></i>-->
<!--							  </span>-->
<!--                            </div>-->
<!--                            <div class="media-body w-100">-->
<!--                                <h6 class="list-group-item-heading">Linda Olson-->
<!--                                    <span class="float-right pt-1">$1,112</span>-->
<!--                                </h6>-->
<!--                                <p class="list-group-item-text mt-5 mb-0">-->
<!--                                    <span class="badge badge-primary">Electronics</span>-->
<!--                                    <span class="badge badge-success ml-1">Office</span>-->
<!--                                </p>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                        <a href="#" class="media xs-media p-5">-->
<!--                            <div class="media-left pr-1">-->
<!--							  <span class="avatar avatar-lg">-->
<!--								<img class="media-object rounded-circle" src="/image/avatar/1.jpg"-->
<!--                                     alt="Generic placeholder image" width="50">-->
<!--								<i></i>-->
<!--							  </span>-->
<!--                            </div>-->
<!--                            <div class="media-body w-100">-->
<!--                                <h6 class="list-group-item-heading">Linda Olson-->
<!--                                    <span class="float-right pt-1">$1,112</span>-->
<!--                                </h6>-->
<!--                                <p class="list-group-item-text mt-5 mb-0">-->
<!--                                    <span class="badge badge-primary">Electronics</span>-->
<!--                                    <span class="badge badge-success ml-1">Office</span>-->
<!--                                </p>-->
<!--                            </div>-->
<!--                        </a><a href="#" class="media xs-media p-5">-->
<!--                            <div class="media-left pr-1">-->
<!--							  <span class="avatar avatar-lg">-->
<!--								<img class="media-object rounded-circle" src="/image/avatar/1.jpg"-->
<!--                                     alt="Generic placeholder image" width="50">-->
<!--								<i></i>-->
<!--							  </span>-->
<!--                            </div>-->
<!--                            <div class="media-body w-100">-->
<!--                                <h6 class="list-group-item-heading">Linda Olson-->
<!--                                    <span class="float-right pt-1">$1,112</span>-->
<!--                                </h6>-->
<!--                                <p class="list-group-item-text mt-5 mb-0">-->
<!--                                    <span class="badge badge-primary">Electronics</span>-->
<!--                                    <span class="badge badge-success ml-1">Office</span>-->
<!--                                </p>-->
<!--                            </div>-->
<!--                        </a>-->
<!---->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
    </div>

</div>
<!-- End Main-content -->


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml' ?>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>


