<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'head.phtml' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableCss.phtml' ?>


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterHead.phtml' ?>

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark"> الاخبار </h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active">الاخبار</li>
                    <li class="breadcrumb-item"><a href="/admin/index">البداية </a></li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<div class="d-flex justify-content-end">
    <a href="/admin/news/create" class="btn btn-primary"><i class="fa fa-plus"></i></a>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <!-- /.card-header -->
        <div class="x_content">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>

                    <th> العنوان</th>
                    <th> الشعار</th>
                    <th> التصنيفات</th>
                    <th> التعليقات</th>
                    <th>الناشر</th>
                    <?php if ($this->view_data['deleted'] == false) { ?>

                        <th> الحالة</th>
                        <th> تعديل</th>
                    <?php } else { ?>
                        <th>حذفة بواسطة</th>
                        <th>تاريخ الحذف</th>
                        <th>استعادة</th>
                    <?php } ?>

                    <th>حذف</th>
                </tr>
                </thead>

                <tbody>
                <?php if (array_key_exists('news', $this->view_data)) {
                    foreach ($this->view_data['news'] as $n) { ?>
                        <tr>
                            <td><?php echo $n['title'] ?> </td>

                            <td><img src="<?php echo $n['logo'] ?>" alt="لايوجد" width="50px"></td>
                            <td>   <?php echo Helper::Names($n['categories2'], 'Category') ?></td>


                            <td><?php echo ($n['has_comment'] == '1') ? 'مفعل' : 'معطل' ?></td>

                            <td> <?php echo Helper::userName($n['created_by']) ?></td>


                            <?php if ($this->view_data['deleted'] == false) { ?>
                                <td><?php echo ($n['status'] == '1') ? 'مفعل' : 'معطل' ?></td>


                                <td class="text-center">
                                    <a href="/admin/news/edit/<?php echo $n['id'] ?>"
                                       class="btn btn-primary"><i
                                                class="fa fa-pencil"></i></a>
                                </td>

                            <?php } else { ?>
                                <th>{{getUserName( $n['deleted_by'] )?></th>
                                <td><?php echo $n['deleted_at'] ?></td>


                                <td class="text-center">
                                    <a href="{{  route('admin.categories.restore',encrypt( $n['']id)) }}"
                                       class="btn btn-primary"><i
                                                class="fa fa-arrow-up"></i></a>
                                </td>

                            <?php } ?>


                            <td class="text-center">
                                <a href="/admin/news/delete/<?php echo $n['id'] ?>"
                                   onclick="return confirm('هل أنت متأكد من الحذف');" class="btn btn-danger"><i
                                            class="fa fa-trash"></i></a>
                            </td>


                        </tr>
                    <?php }
                } ?>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
</div>


<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.blade.php' ?>
<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'dataTableJs.phtml' ?>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterFooter.blade.php' ?>
<script>


    $(function () {
        $('#example1').DataTable({
            language: {url: "//cdn.datatables.net/plug-ins/1.10.19/i18n/Arabic.json"},
            dom: "Bfrtip",
            buttons: [{extend: "copy", text: "نسخ", className: "btn-sm"}, {
                extend: "csv",
                text: "ملف CSV",
                className: "btn-sm"
            }, {extend: "excel", text: "اکسل", className: "btn-sm"}, {
                extend: "pdfHtml5",
                text: "ملف PDF",
                className: "btn-sm"
            }, {extend: "print", text: "طباعة", className: "btn-sm"}],
            responsive: !0
        });
    });
</script>

<?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'afterScript.php' ?>


